// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { ActivityModel } from '../../models/activity.js'

// FALLBACK: codec inside union at .payload — this table carries its full model (per-table cost).
export default { doc: ActivityModel.schema.doc, insert: ActivityModel.schema.insert }
