// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod'
import { zx } from 'zodvex'
import { zDuration } from '../../codecs.js'
import { taggedEmail, taggedTag } from '../../tagged.js'

// Minimal schema: codec subtrees only; unknown keys pass through (loose).
const schema = z.looseObject({ createdAt: zx.date(), payload: z.union([z.looseObject({ type: z.literal("task_completed"), duration: zDuration, }), z.looseObject({ type: z.literal("user_invited"), email: taggedEmail, }), z.looseObject({})]), tags: z.optional(z.array(taggedTag)), })

export default { doc: schema, insert: schema }
