// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod'
import { zx } from 'zodvex'

// Minimal schema: codec subtrees only; unknown keys pass through (loose).
const schema = z.looseObject({ createdAt: zx.date(), })

export default { doc: schema, insert: schema }
