// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod'
import { zx } from 'zodvex'

// Minimal loose schema: codec fields only; unknown keys pass through.
const schema = z.looseObject({
  createdAt: zx.date(),
})

export default { doc: schema, insert: schema }
