// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import d_0 from './activities.js'
import d_1 from './comments.js'
import d_2 from './notifications.js'
import d_3 from './tasks.js'
import d_4 from './users.js'

/** Central tableMap: codec-bearing tables only at O(codec fields) cost.
 *  Tables absent here have no codecs — wrapper passthrough is correct. */
export const zodvexTableMap = {
  'activities': d_0,
  'comments': d_1,
  'notifications': d_2,
  'tasks': d_3,
  'users': d_4,
}

/** Fingerprint of the codec-path spec this map was generated from. */
export const zodvexTableMapFingerprint = 'cc4ce4563ffeab67c14a21ae2ad9a81cbe48c717d1c9594a245f5432e78b3af6'
