// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { NotificationModel } from '../../models/notification.js'

// FALLBACK: codec inside union at . — this table carries its full model (per-table cost).
export default { doc: NotificationModel.schema.doc, insert: NotificationModel.schema.insert }
