// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod'
import { zx } from 'zodvex'

// Minimal schema: codec subtrees only; unknown keys pass through (loose).
const schema = z.union([z.looseObject({ kind: z.literal("email"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("push"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("in_app"), createdAt: zx.date(), }), z.looseObject({})])

export default { doc: schema, insert: schema }
