// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod'
import { zx } from 'zodvex'
import { taggedEmail } from '../../tagged.js'

// Minimal loose schema: codec fields only; unknown keys pass through.
const schema = z.looseObject({
  createdAt: zx.date(),
  email: z.optional(taggedEmail),
})

export default { doc: schema, insert: schema }
