import type {
  OptionalRestArgsOrSkip,
  PaginatedQueryReference,
  UsePaginatedQueryResult
} from 'convex/react'
import * as convexReact from 'convex/react'
import { useMutation, usePaginatedQuery, useQuery } from 'convex/react'
import type {
  FunctionArgs,
  FunctionReference,
  FunctionReturnType,
  PaginationOptions
} from 'convex/server'
import { useMemo } from 'react'
import type { BoundaryHelpersOptions } from '../../internal/boundaryHelpers'
import { createBoundaryHelpers, resolveFunctionPath } from '../../internal/boundaryHelpers'
import { createPaginationCodec } from '../../internal/paginationCodec'
import type { AnyRegistry } from '../../internal/types'

/** Query state, with failures omitted when throwOnError is enabled. */
export type UseQueryResult<Result, ThrowOnError extends boolean = false> =
  | { status: 'pending' }
  | { status: 'success'; data: Result }
  | (ThrowOnError extends true ? never : { status: 'error'; error: Error })

type UseQueryOptions<
  Query extends FunctionReference<'query', any, any, any>,
  ThrowOnError extends boolean
> = {
  query: Query
  args: FunctionArgs<Query> | 'skip'
  throwOnError?: ThrowOnError
}

function codecError(error: unknown, operation: 'encode' | 'decode'): Error {
  return error instanceof Error
    ? error
    : new Error(`Failed to ${operation} query ${operation === 'encode' ? 'arguments' : 'result'}`, {
        cause: error
      })
}

/**
 * Creates zodvex-aware React hooks that automatically decode query results
 * and encode mutation arguments using the Zod schemas in the registry.
 *
 * Returned hooks are drop-in replacements for Convex's `useQuery` and
 * `useMutation` — they delegate to the real hooks, then apply codec
 * transforms so that runtime types (e.g. Date) are used instead of wire
 * types (e.g. number timestamps).
 *
 * @param registry - A map of function paths to `{ args?, returns? }` Zod schemas.
 *   Typically generated by zodvex codegen into `_zodvex/client.ts`.
 *
 * @example
 * ```typescript
 * import { zodvexRegistry } from '../_zodvex/client'
 * export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)
 *
 * // In a component:
 * const tasks = useZodQuery(api.tasks.list, { status: 'active' })
 * //    ^? Task[] — createdAt is Date, not number
 * ```
 */
export function createZodvexHooks<R extends AnyRegistry>(
  registry: R,
  options?: BoundaryHelpersOptions
) {
  const codec = createBoundaryHelpers(registry, options)
  const paginationCodec = createPaginationCodec(registry)
  const experimentalCodec = createBoundaryHelpers(registry, {
    ...options,
    onDecodeError: options?.onDecodeError ?? 'throw'
  })

  /**
   * Convex pagination with encoded filters and decoded items. Pagination metadata
   * stays under Convex's control. Codec errors throw, including in warn mode.
   * Outer object/array refinements and transforms require explicit page queries.
   */
  function useZodPaginatedQuery<
    Query extends FunctionReference<
      'query',
      'public',
      { paginationOpts?: PaginationOptions },
      { page: any[]; isDone: boolean; continueCursor: string }
    >
  >(
    ref: Query,
    args: Omit<FunctionArgs<Query>, 'paginationOpts'> | 'skip',
    paginationOptions: { initialNumItems: number }
  ): UsePaginatedQueryResult<FunctionReturnType<Query>['page'][number]> {
    let wireArgs: any = 'skip'
    let encodeFailure: { error: unknown } | undefined
    if (args !== 'skip') {
      try {
        wireArgs = paginationCodec.encodeArgs(ref, args)
      } catch (error) {
        encodeFailure = { error }
      }
    }
    const state = usePaginatedQuery(ref as PaginatedQueryReference, wireArgs, paginationOptions)
    const skipped = wireArgs === 'skip'
    const queryKey = resolveFunctionPath(ref) ?? ref
    const results = useMemo(
      () => (skipped ? state.results : paginationCodec.decodeResults(ref, state.results)),
      [queryKey, state.results, skipped]
    )
    // Call both hooks on failed encodes too, so a failure never changes hook order.
    if (encodeFailure) throw encodeFailure.error
    return { ...state, results }
  }

  /**
   * Convex's object-form query hook with decoded arguments and results (Convex >=1.37).
   * Codec failures return an error state unless throwOnError is true. Decoding is
   * strict by default; explicit onDecodeError: 'warn' preserves the raw fallback.
   */
  function useQuery_experimental<
    Query extends FunctionReference<'query', any, any, any>,
    ThrowOnError extends boolean = false
  >(
    queryOptions: UseQueryOptions<Query, ThrowOnError>
  ): UseQueryResult<FunctionReturnType<Query>, ThrowOnError>
  function useQuery_experimental(
    queryOptions: UseQueryOptions<FunctionReference<'query', any, any, any>, boolean>
  ): UseQueryResult<any> {
    // Optional namespace access keeps older SDK imports valid and allows tree shaking.
    const nativeHook = (
      convexReact as unknown as {
        useQuery_experimental?: (
          options: UseQueryOptions<FunctionReference<'query', any, any, any>, boolean>
        ) => UseQueryResult<any>
      }
    ).useQuery_experimental
    if (typeof nativeHook !== 'function') {
      throw new Error(
        'useQuery_experimental requires Convex >=1.37. Upgrade convex to use this hook.'
      )
    }
    const { query, args, throwOnError } = queryOptions
    let wireArgs: any = 'skip'
    let encodeFailure: Error | undefined
    if (args !== 'skip') {
      try {
        wireArgs = experimentalCodec.encodeArgs(query, args)
      } catch (error) {
        encodeFailure = codecError(error, 'encode')
      }
    }

    // Even failed encodes call the real hook; its own synchronous errors still propagate.
    const state = nativeHook({ query, args: wireArgs, throwOnError })
    if (encodeFailure) {
      if (throwOnError) throw encodeFailure
      return { status: 'error', error: encodeFailure }
    }
    if (state.status !== 'success') return state
    try {
      return { status: 'success', data: experimentalCodec.decodeResult(query, state.data) }
    } catch (error) {
      const failure = codecError(error, 'decode')
      if (throwOnError) throw failure
      return { status: 'error', error: failure }
    }
  }

  /**
   * Drop-in replacement for Convex's `useQuery` with automatic codec decode.
   *
   * Delegates to the real `useQuery` and then decodes the wire result through
   * the `returns` schema in the registry (if one exists for this function).
   *
   * Two overloads:
   * 1. Rest-args (Convex-compatible): `useZodQuery(ref, args)` or `useZodQuery(ref, 'skip')`
   * 2. Union args (composable): `useZodQuery(ref, args | 'skip')` — for wrappers
   *    and conditional skip patterns where the decision is made upstream.
   *
   * - Invalid arguments throw during render; use a React error boundary to handle them.
   * - Loading state (`undefined`) passes through unchanged.
   * - Functions not in the registry return the raw wire result.
   */
  // Overload 1: drop-in compatible with Convex's useQuery
  function useZodQuery<Query extends FunctionReference<'query', any, any, any>>(
    ref: Query,
    ...args: OptionalRestArgsOrSkip<Query>
  ): FunctionReturnType<Query> | undefined
  // Overload 2: composable — accepts Args | 'skip' union for wrappers
  function useZodQuery<Query extends FunctionReference<'query', any, any, any>>(
    ref: Query,
    args: Query['_args'] | 'skip'
  ): FunctionReturnType<Query> | undefined
  // Implementation
  function useZodQuery(ref: FunctionReference<'query', any, any, any>, ...restArgs: any[]) {
    const args = restArgs[0]

    // Always call useQuery, including failed encodes, to preserve hook order.
    // Then surface the error to React's error boundary instead of appearing to load forever.
    let wireArgs: any = 'skip'
    let encodeFailure: { error: unknown } | undefined
    if (args !== 'skip') {
      try {
        wireArgs = codec.encodeArgs(ref, args)
      } catch (error) {
        encodeFailure = { error }
      }
    }

    const wireResult = useQuery(
      ref,
      ...((wireArgs === 'skip' ? ['skip'] : [wireArgs]) as OptionalRestArgsOrSkip<typeof ref>)
    )

    if (encodeFailure) throw encodeFailure.error

    // Loading state — Convex returns undefined while the subscription is pending
    if (wireResult === undefined) return undefined

    // Decode: wire format -> runtime types (e.g., timestamp number -> Date)
    return codec.decodeResult(ref, wireResult)
  }

  /**
   * Drop-in replacement for Convex's `useMutation`.
   *
   * Returns an async function that:
   * 1. Encodes the args through the `args` schema (runtime -> wire format)
   * 2. Calls the real mutation with the wire args
   * 3. Decodes the result through the `returns` schema (wire -> runtime format)
   *
   * Functions not in the registry pass args and results through unchanged.
   */
  function useZodMutation<Mutation extends FunctionReference<'mutation', any, any, any>>(
    ref: Mutation
  ) {
    const rawMutate = useMutation(ref)

    return async (args: FunctionArgs<Mutation>): Promise<FunctionReturnType<Mutation>> => {
      // Encode args: runtime types -> wire format (e.g., Date -> timestamp)
      const wireArgs = codec.encodeArgs(ref, args)

      const wireResult = await (rawMutate as any)(wireArgs)

      // Decode result: wire format -> runtime types
      return codec.decodeResult(ref, wireResult)
    }
  }

  return { useZodQuery, useZodMutation, useZodPaginatedQuery, useQuery_experimental }
}

/**
 * The return type of `createZodvexHooks` — useful for typing module-level
 * exports in generated client files.
 */
export type ZodvexHooks = ReturnType<typeof createZodvexHooks>
