// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import type { ZodTypeAny } from 'zod'

export declare const zodvexRegistry: Record<string, { args: ZodTypeAny; returns: ZodTypeAny | undefined }>
