// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import type { ZodTypeAny } from 'zod'

export declare const zodvexReturnsRegistry: Record<string, { returns: ZodTypeAny }>
