// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod'
import { zx } from 'zodvex'
import { zDuration } from '../codecs.js'
import { taggedEmail, taggedTag } from '../tagged.js'

export const zodvexArgsRegistry = {
  'activities:update': {
    args: z.looseObject({ createdAt: z.optional(zx.date()), payload: z.optional(z.union([z.looseObject({ type: z.literal("task_completed"), duration: zDuration, }), z.looseObject({ type: z.literal("user_invited"), email: taggedEmail, }), z.looseObject({})])), tags: z.optional(z.array(taggedTag)), }),
  },
  'filters:namedRecentUsers': {
    args: z.looseObject({ after: zx.date(), }),
  },
  'filters:recentUsers': {
    args: z.looseObject({ after: zx.date(), }),
  },
  'filters:recentUsersWithHelper': {
    args: z.looseObject({ after: zx.date(), }),
  },
  'notifications:listByCreated': {
    args: z.looseObject({ after: zx.date(), }),
  },
  'tasks:create': {
    args: z.looseObject({ dueDate: z.optional(zx.date()), estimate: z.optional(zDuration), }),
  },
  'tasks:listByCreated': {
    args: z.looseObject({ after: zx.date(), }),
  },
  'tasks:update': {
    args: z.looseObject({ dueDate: z.optional(zx.date()), estimate: z.optional(zDuration), }),
  },
  'users:countByEmail': {
    args: z.looseObject({ email: taggedEmail, }),
  },
  'users:getByEmail': {
    args: z.looseObject({ email: taggedEmail, }),
  },
  'users:update': {
    args: z.looseObject({ createdAt: z.optional(zx.date()), email: z.optional(taggedEmail), }),
  },
}
