// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod'
import { zx, extractCodec, readFnArgs } from 'zodvex/core'
import { CommentModel } from '../models/comment'
import { UserModel } from '../models/user'
import { TaskModel } from '../models/task'
import { ActivityModel } from '../models/activity'
import { getByEmail } from '../users'
import { zDuration } from '../codecs'

const _mc0 = extractCodec(ActivityModel.schema.doc.shape.payload._zod.def.options[1].shape.email)
const _mc1 = extractCodec(ActivityModel.schema.doc.shape.tags._zod.def.innerType._zod.def.element)
const _mc2 = extractCodec(UserModel.schema.doc.shape.email)
const _fc0 = extractCodec(readFnArgs(getByEmail).shape.email)

export const zodvexRegistry = {
  'comments:create': {
    args: z.object({ taskId: zx.id("tasks"), authorId: zx.id("users"), body: z.string() }),
    returns: zx.id("comments"),
  },
  'comments:list': {
    args: z.object({ taskId: zx.id("tasks") }),
    returns: CommentModel.schema.docArray,
  },
  'users:create': {
    args: z.object({ name: z.string(), email: z.string(), avatarUrl: z.string().optional() }),
    returns: zx.id("users"),
  },
  'users:get': {
    args: z.object({ id: zx.id("users") }),
    returns: UserModel.schema.doc.nullable(),
  },
  'users:getByEmail': {
    args: z.object({ email: _fc0 }),
    returns: UserModel.schema.doc.nullable(),
  },
  'users:update': {
    args: z.object({ name: z.string().optional(), email: _mc2.optional().optional(), avatarUrl: z.string().optional().optional(), createdAt: zx.date().optional(), _id: zx.id("users"), _creationTime: z.number().optional() }),
    returns: undefined,
  },
  'tasks:complete': {
    args: z.object({ id: zx.id("tasks") }),
    returns: undefined,
  },
  'tasks:create': {
    args: z.object({ title: z.string(), description: z.string().optional(), status: z.enum(["todo", "in_progress", "done"]).optional(), priority: z.enum(["low", "medium", "high"]).nullable().optional(), ownerId: zx.id("users"), assigneeId: zx.id("users").optional(), dueDate: zx.date().optional(), estimate: zDuration.optional() }),
    returns: zx.id("tasks"),
  },
  'tasks:get': {
    args: z.object({ id: zx.id("tasks") }),
    returns: TaskModel.schema.doc.nullable(),
  },
  'tasks:list': {
    args: z.object({ status: z.enum(["todo", "in_progress", "done"]).optional(), ownerId: zx.id("users").optional(), paginationOpts: z.object({ numItems: z.number(), cursor: z.string().nullable() }) }),
    returns: TaskModel.schema.paginatedDoc,
  },
  'tasks:update': {
    args: z.object({ id: zx.id("tasks"), title: z.string().optional(), description: z.string().optional(), status: z.enum(["todo", "in_progress", "done"]).optional(), priority: z.enum(["low", "medium", "high"]).nullable().optional(), assigneeId: zx.id("users").optional(), dueDate: zx.date().optional(), estimate: zDuration.optional() }),
    returns: undefined,
  },
  'activities:get': {
    args: z.object({ id: zx.id("activities") }),
    returns: ActivityModel.schema.doc.nullable(),
  },
  'activities:listByActor': {
    args: z.object({ actorId: zx.id("users") }),
    returns: ActivityModel.schema.docArray,
  },
  'activities:update': {
    args: z.object({ actorId: zx.id("users").optional(), payload: z.union([z.object({ type: z.literal("task_completed"), taskId: zx.id("tasks"), duration: zDuration }), z.object({ type: z.literal("user_invited"), email: _mc0 })]).optional(), tags: z.array(_mc1).optional().optional(), createdAt: zx.date().optional(), _id: zx.id("activities"), _creationTime: z.number().optional() }),
    returns: undefined,
  },
  'api/reports:summary': {
    args: z.object({ ownerId: zx.id("users").optional() }),
    returns: z.object({ total: z.number(), done: z.number() }),
  },
  'api/reports:taskById': {
    args: z.object({ id: zx.id("tasks") }),
    returns: TaskModel.schema.doc.nullable(),
  },
} as const
