// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod'
import { zx, extractCodec } from 'zodvex/core'
import { CommentModel } from '../models/comment'
import { TaskModel } from '../models/task'
import { UserModel } from '../models/user'
import { ActivityModel } from '../models/activity'
import { zDuration } from '../codecs'

const _userEmail = extractCodec(UserModel.schema.doc.shape.email)

export const zodvexRegistry = {
  'comments:create': {
    args: z.object({ taskId: zx.id("tasks"), authorId: zx.id("users"), body: z.string() }),
    returns: zx.id("comments"),
  },
  'comments:list': {
    args: z.object({ taskId: zx.id("tasks") }),
    returns: CommentModel.schema.docArray,
  },
  'api/reports:summary': {
    args: z.object({ ownerId: zx.id("users").optional() }),
    returns: z.object({ total: z.number(), done: z.number() }),
  },
  'api/reports:taskById': {
    args: z.object({ id: zx.id("tasks") }),
    returns: TaskModel.schema.doc.nullable(),
  },
  'users:create': {
    args: z.object({ name: z.string(), email: z.string(), avatarUrl: z.string().optional() }),
    returns: zx.id("users"),
  },
  'users:get': {
    args: z.object({ id: zx.id("users") }),
    returns: UserModel.schema.doc.nullable(),
  },
  'users:getByEmail': {
    args: z.object({ email: _userEmail }),
    returns: UserModel.schema.doc.nullable(),
  },
  'users:update': {
    args: UserModel.schema.update,
    returns: undefined,
  },
  'tasks:complete': {
    args: z.object({ id: zx.id("tasks") }),
    returns: undefined,
  },
  'tasks:create': {
    args: z.object({ title: z.string(), description: z.string().optional(), status: z.enum(["todo", "in_progress", "done"]).optional(), priority: z.enum(["low", "medium", "high"]).nullable().optional(), ownerId: zx.id("users"), assigneeId: zx.id("users").optional(), dueDate: zx.date().optional(), estimate: zDuration.optional() }),
    returns: zx.id("tasks"),
  },
  'tasks:get': {
    args: z.object({ id: zx.id("tasks") }),
    returns: TaskModel.schema.doc.nullable(),
  },
  'tasks:list': {
    args: z.object({ status: z.enum(["todo", "in_progress", "done"]).optional(), ownerId: zx.id("users").optional(), paginationOpts: z.object({ numItems: z.number(), cursor: z.string().nullable() }) }),
    returns: TaskModel.schema.paginatedDoc,
  },
  'tasks:update': {
    args: z.object({ id: zx.id("tasks"), title: z.string().optional(), description: z.string().optional(), status: z.enum(["todo", "in_progress", "done"]).optional(), priority: z.enum(["low", "medium", "high"]).nullable().optional(), assigneeId: zx.id("users").optional(), dueDate: zx.date().optional(), estimate: zDuration.optional() }),
    returns: undefined,
  },
  'activities:get': {
    args: z.object({ id: zx.id("activities") }),
    returns: ActivityModel.schema.doc.nullable(),
  },
  'activities:listByActor': {
    args: z.object({ actorId: zx.id("users") }),
    returns: ActivityModel.schema.docArray,
  },
  'activities:update': {
    args: ActivityModel.schema.update,
    returns: undefined,
  },
} as const
