// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod'
import { zx } from 'zodvex'
import { ActivityModel } from '../models/activity.js'
import { UserModel } from '../models/user.js'
import { zDuration } from '../codecs.js'
import { taggedEmail } from '../tagged.js'

export const zodvexArgsRegistry = {
  'activities:update': {
    args: ActivityModel.schema.update,
  },
  'filters:namedRecentUsers': {
    args: z.object({ after: zx.date() }),
  },
  'filters:recentUsers': {
    args: z.object({ after: zx.date() }),
  },
  'filters:recentUsersWithHelper': {
    args: z.object({ after: zx.date() }),
  },
  'notifications:listByCreated': {
    args: z.object({ after: zx.date() }),
  },
  'tasks:create': {
    args: z.object({ title: z.string(), description: z.string().optional(), status: z.enum(["todo", "in_progress", "done"]).optional(), priority: z.enum(["low", "medium", "high"]).nullable().optional(), ownerId: zx.id("users"), assigneeId: zx.id("users").optional(), dueDate: zx.date().optional(), estimate: zDuration.optional() }),
  },
  'tasks:listByCreated': {
    args: z.object({ after: zx.date() }),
  },
  'tasks:update': {
    args: z.object({ id: zx.id("tasks"), title: z.string().optional(), description: z.string().optional(), status: z.enum(["todo", "in_progress", "done"]).optional(), priority: z.enum(["low", "medium", "high"]).nullable().optional(), assigneeId: zx.id("users").optional(), dueDate: zx.date().optional(), estimate: zDuration.optional() }),
  },
  'users:countByEmail': {
    args: z.object({ email: taggedEmail }),
  },
  'users:getByEmail': {
    args: z.object({ email: taggedEmail }),
  },
  'users:update': {
    args: UserModel.schema.update,
  },
}
