// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { mantineResolver as _mantineResolver } from 'zodvex/form/mantine'
import type { FunctionReference } from 'convex/server'
import { createZodvexHooks } from 'zodvex/react'
import { createZodvexReactClient, type ZodvexReactClientOptions } from 'zodvex/react'
import { createZodvexClient, type ZodvexClientOptions } from 'zodvex/client'
import { createBoundaryHelpers } from 'zodvex/core'
import { zodvexRegistry } from './api'

export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)

export const createClient = (options: ZodvexClientOptions) =>
  createZodvexClient(zodvexRegistry, options)

export const createReactClient = (options: ZodvexReactClientOptions) =>
  createZodvexReactClient(zodvexRegistry, options)

export const { encodeArgs, decodeResult } = createBoundaryHelpers(zodvexRegistry)

export const mantineResolver = (ref: FunctionReference<any, any, any, any>) =>
  _mantineResolver(zodvexRegistry, ref)
