// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { mantineResolver as _mantineResolver } from 'zodvex/form/mantine'
import { createZodvexHooks } from 'zodvex/react'
import { createZodvexReactClient } from 'zodvex/react'
import { createZodvexClient } from 'zodvex/client'
import { createBoundaryHelpers } from 'zodvex/core'
import { zodvexRegistry } from './api.js'

export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)

export const createClient = (options) =>
  createZodvexClient(zodvexRegistry, options)

export const createReactClient = (options) =>
  createZodvexReactClient(zodvexRegistry, options)

export const { encodeArgs, decodeResult } = createBoundaryHelpers(zodvexRegistry)

export const mantineResolver = (ref) =>
  _mantineResolver(zodvexRegistry, ref)
