// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import type { ZodvexHooks } from 'zodvex/react'
import type { ZodvexClientOptions, ZodvexClient } from 'zodvex/client'
import type { ZodvexReactClientOptions, ZodvexReactClient } from 'zodvex/react'
import type { BoundaryHelpers } from 'zodvex'

export declare const useZodQuery: ZodvexHooks['useZodQuery']
export declare const useZodMutation: ZodvexHooks['useZodMutation']

export declare const createClient: (options: ZodvexClientOptions) => ZodvexClient

export declare const createReactClient: (options: ZodvexReactClientOptions) => ZodvexReactClient

export declare const encodeArgs: BoundaryHelpers['encodeArgs']
export declare const decodeResult: BoundaryHelpers['decodeResult']
