// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { createZodvexHooks } from 'zodvex/react'
import { createZodvexClient, type ZodvexClientOptions } from 'zodvex/client'
import { zodvexRegistry } from './api'

export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)

export const createClient = (options: ZodvexClientOptions) =>
  createZodvexClient(zodvexRegistry, options)
