// AUTO-GENERATED by zodvex — do not edit
//
// Convex's CLI walker treats any subdirectory of convex/ that contains a
// convex.config.ts as a nested component definition and skips it during
// entrypoint discovery. zodvex emits this file so the codegen artifacts
// under _zodvex/ (api.js, client.js, tables.ts, etc.) are NOT analyzed as
// individual function-module entrypoints in their own 64 MB isolates —
// which is what was causing deploy OOMs as the registry grew with the
// number of zod-validated endpoints.
//
// This is NOT a real Convex component — it isn't registered via
// .use(...) in the parent convex.config.ts. The file's presence alone
// is the signal Convex's walker reads.
import { defineApp } from 'convex/server'
export default defineApp()
