// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { zx } from 'zodvex'
import { initZodvex as _libInitZodvex } from 'zodvex/server'
import type {
  ZodvexActionCtx,
  ZodvexBuilder,
  ZodvexMutationCtx,
  ZodvexQueryCtx,
} from 'zodvex/server'
import type {
  ActionBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  MutationBuilder,
  QueryBuilder,
} from 'convex/server'
import type { DataModel } from '../_generated/dataModel.js'
import _baseSchema from '../schema.js'
import { ActivityModel } from '../models/activity.js'
import { NotificationModel } from '../models/notification.js'
import { CommentModel } from '../models/comment.js'
import { UserModel } from '../models/user.js'
import { TaskModel } from '../models/task.js'


// --- Context types ---

// Decoded doc types are imported directly from the codegen-emitted
// tables.ts so userland `schema.ts` can use Convex's canonical
// `defineSchema(tables)` without carrying a zodvex-specific token.
import type { DecodedDocs as _DecodedDocs } from './tables'
type DecodedDocs = _DecodedDocs

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>

// --- Lazy registry (actions only) ---
// Dynamic import is safe here because the registry is only consumed by
// `za`/`zia` action handlers. Convex actions run in Node, where dynamic
// `import()` works. Q/M handlers run in a V8 sandbox that forbids
// dynamic imports — see ../tableMap below for that constraint.

let _cachedRegistry: Promise<typeof import('./api.js').zodvexRegistry> | undefined
const _registry = () => (_cachedRegistry ??= import('./api.js').then(m => m.zodvexRegistry))

// --- Static table map (Q/M-safe) ---
// Built sync from statically-imported models. Convex's Q/M V8 sandbox
// forbids dynamic `import()` with "dynamic module import unsupported",
// so the runtime tableMap can't be loaded lazily. Userland `functions.ts`
// imports this module → pulls every model into its analyzer isolate at
// deploy time.

const _tableMap = {
  "activities": { doc: zx.doc(ActivityModel), insert: zx.base(ActivityModel) },
  "notifications": { doc: zx.doc(NotificationModel), insert: zx.base(NotificationModel) },
  "comments": { doc: zx.doc(CommentModel), insert: zx.base(CommentModel) },
  "users": { doc: zx.doc(UserModel), insert: zx.base(UserModel) },
  "tasks": { doc: zx.doc(TaskModel), insert: zx.base(TaskModel) }
}

// --- Pre-wired initZodvex ---
// Calls the library's initZodvex with schema + lazy registry/tableMap
// already wired. Consumers pass only the Convex server builders.
// Override registry/tableMap/wrapDb via options if needed.

type Server = {
  query: QueryBuilder<DataModel, 'public'>
  mutation: MutationBuilder<DataModel, 'public'>
  action: ActionBuilder<DataModel, 'public'>
  internalQuery: QueryBuilder<DataModel, 'internal'>
  internalMutation: MutationBuilder<DataModel, 'internal'>
  internalAction: ActionBuilder<DataModel, 'internal'>
}

type Bundle = {
  zq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'public'>
  zm: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'public'>
  za: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'public'>
  ziq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'internal'>
  zim: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'internal'>
  zia: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'internal'>
}

export function initZodvex(server: Server, options: {
  wrapDb?: boolean
  registry?: () => any
  tableMap?: any
} = {}): Bundle {
  return (_libInitZodvex as any)(_baseSchema, server, {
    ...options,
    registry: options.registry ?? _registry,
    tableMap: options.tableMap ?? _tableMap,
  }) as Bundle
}

// --- Codec-aware schema re-export ---
// Userland code that wants `createZodDbReader`/`createZodDbWriter` outside
// a zq/zm handler imports `schema` from here (not from `../schema`). This
// object is the base schema with the sync tableMap attached as
// `__zodTableMap` plus a type-only `__decodedDocs` token.

type ZodvexSchema = typeof _baseSchema & {
  __zodTableMap: typeof _tableMap
  __decodedDocs: DecodedDocs
}

export const schema: ZodvexSchema = Object.assign(_baseSchema, {
  __zodTableMap: _tableMap,
  __decodedDocs: undefined as unknown as DecodedDocs,
})
