// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { initZodvex as _libInitZodvex } from 'zodvex/server'
import type {
  ZodvexActionCtx,
  ZodvexBuilder,
  ZodvexMutationCtx,
  ZodvexQueryCtx,
} from 'zodvex/server'
import type {
  ActionBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  MutationBuilder,
  QueryBuilder,
} from 'convex/server'
import type { DataModel } from '../_generated/dataModel.js'
import { zodvexArgsRegistry as _argsRegistry } from './api.args.js'
import { zodvexReturnsRegistry as _returnsRegistry } from './api.returns.js'
import { zodvexTableMap as _tableMap } from './models/index.js'

// --- Context types ---

// Decoded doc types are imported directly from the codegen-emitted
// tables.ts so userland `schema.ts` can use Convex's canonical
// `defineSchema(tables)` without carrying a zodvex-specific token.
import type { DecodedDocs as _DecodedDocs } from './tables'
type DecodedDocs = _DecodedDocs

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>

// --- Registries: static args (encode) + static minimal returns (decode) ---
// Both are statically imported (the Q/M V8 sandbox forbids dynamic
// `import()`) and both stay light by construction: args entries are
// MINIMAL codec-path schemas, and returns entries are MINIMAL codec-path
// schemas of each function's returns — never the model-doc graph that made
// the full registry too heavy to import statically. Under 0.8's codec-only
// semantics these two registries serve mutations AND actions alike; the
// FULL registry (./api.js, args + returns as full zod) is client-bundle
// territory and is deliberately not referenced here, even lazily.

const _schedulerRegistry = () => _argsRegistry
const _returnsRegistryThunk = () => _returnsRegistry

// --- Codec-paths table map (Q/M-safe, ~zero weight) ---
// The Q/M V8 sandbox forbids dynamic `import()`, so the runtime tableMap
// must be statically reachable — but it does NOT need the model graph:
// ./models/index.js carries one minimal loose schema per codec-bearing
// table (codec fields only), so this import costs O(codec fields) instead
// of the all-models graph that OOM'd real deploys at ~150 models.

// --- Pre-wired initZodvex ---
// Calls the library's initZodvex with schema + registry + tableMap
// already wired. Consumers pass only the Convex server builders.
// Override registry/tableMap/wrapDb via options if needed.

type Server = {
  query: QueryBuilder<DataModel, 'public'>
  mutation: MutationBuilder<DataModel, 'public'>
  action: ActionBuilder<DataModel, 'public'>
  internalQuery: QueryBuilder<DataModel, 'internal'>
  internalMutation: MutationBuilder<DataModel, 'internal'>
  internalAction: ActionBuilder<DataModel, 'internal'>
}

type Bundle = {
  zq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'public'>
  zm: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'public'>
  za: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'public'>
  ziq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'internal'>
  zim: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'internal'>
  zia: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'internal'>
}

export function initZodvex(server: Server, options: {
  wrapDb?: boolean
  registry?: () => any
  schedulerRegistry?: () => any
  returnsRegistry?: () => any
  tableMap?: any
  /** Compose native db wrappers (e.g. convex-helpers triggers) UNDER the
   *  codec layer — forwarded to the library's initZodvex (#92). */
  underlyingDb?: {
    query?: (ctx: GenericQueryCtx<DataModel>) => any
    mutation?: (ctx: GenericMutationCtx<DataModel>) => any
  }
} = {}): Bundle {
  return (_libInitZodvex as any)(_schemaToken, server, {
    ...options,
    schedulerRegistry: options.schedulerRegistry ?? _schedulerRegistry,
    returnsRegistry: options.returnsRegistry ?? _returnsRegistryThunk,
    tableMap: options.tableMap ?? _tableMap,
  }) as Bundle
}

// --- Codec-aware schema re-export (tokens only) ---
// Userland code that wants `createZodDbReader`/`createZodDbWriter` outside
// a zq/zm handler imports `schema` from here (not from `../schema`).
// NOTE: deliberately NOT a value-import of ../schema.js — that would pull
// the table definitions into EVERY endpoint bundle (~8 MB at N=800, the
// difference between hitting Convex's TooManyReads wall and OOMing just
// short of it). The TYPE carries the full schema (type-only import,
// erased); the runtime value carries only the zodvex tokens, which is all
// the db wrappers read.

type ZodvexSchema = typeof import('../schema.js').default & {
  __zodTableMap: typeof _tableMap
  __decodedDocs: DecodedDocs
}

const _schemaToken = {
  __zodTableMap: _tableMap,
  __decodedDocs: undefined as unknown as DecodedDocs,
} as unknown as ZodvexSchema

export const schema: ZodvexSchema = _schemaToken
