// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { zx } from 'zodvex'
import { initZodvex as _libInitZodvex } from 'zodvex/server'
import type {
  ZodvexActionCtx,
  ZodvexBuilder,
  ZodvexMutationCtx,
  ZodvexQueryCtx,
} from 'zodvex/server'
import type {
  ActionBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  MutationBuilder,
  QueryBuilder,
} from 'convex/server'
import type { DataModel } from '../_generated/dataModel.js'
import type { ActivityModel } from '../models/activity.js'
import type { NotificationModel } from '../models/notification.js'
import type { CommentModel } from '../models/comment.js'
import type { UserModel } from '../models/user.js'
import type { TaskModel } from '../models/task.js'
import schema from '../schema.js'

// --- Context types ---

// Decoded doc types are imported directly from the codegen-emitted
// tables.ts so userland `schema.ts` can use Convex's canonical
// `defineSchema(tables)` without carrying a zodvex-specific token.
import type { DecodedDocs as _DecodedDocs } from './tables'
type DecodedDocs = _DecodedDocs

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>

// --- Lazy registry ---
// Dynamic import keeps the registry's transitive schema graph out of any
// entrypoint that statically imports this file. esbuild hoists the target
// into a chunk under `_deps/`.

let _cachedRegistry: Promise<typeof import('./api.js').zodvexRegistry> | undefined
const _registry = () => (_cachedRegistry ??= import('./api.js').then(m => m.zodvexRegistry))

// --- Lazy table map ---
// One dynamic import per model file. Resolved + cached on first DB call.
// Builds the same { doc, insert } shape `defineZodSchema` previously
// attached to the schema synchronously.

let _cachedTableMap: Promise<Record<string, { doc: any; insert: any }>> | undefined
const _tableMap = () => (_cachedTableMap ??= (async () => {
  const refs = await Promise.all([
      import('../models/activity.js').then(m => m.ActivityModel),
      import('../models/notification.js').then(m => m.NotificationModel),
      import('../models/comment.js').then(m => m.CommentModel),
      import('../models/user.js').then(m => m.UserModel),
      import('../models/task.js').then(m => m.TaskModel)
  ])
  return {
      "activities": { doc: zx.doc(refs[0]), insert: zx.base(refs[0]) },
      "notifications": { doc: zx.doc(refs[1]), insert: zx.base(refs[1]) },
      "comments": { doc: zx.doc(refs[2]), insert: zx.base(refs[2]) },
      "users": { doc: zx.doc(refs[3]), insert: zx.base(refs[3]) },
      "tasks": { doc: zx.doc(refs[4]), insert: zx.base(refs[4]) }
  }
})())

// --- Pre-wired initZodvex ---
// Calls the library's initZodvex with schema + lazy registry/tableMap
// already wired. Consumers pass only the Convex server builders.
// Override registry/tableMap/wrapDb via options if needed.

type Server = {
  query: QueryBuilder<DataModel, 'public'>
  mutation: MutationBuilder<DataModel, 'public'>
  action: ActionBuilder<DataModel, 'public'>
  internalQuery: QueryBuilder<DataModel, 'internal'>
  internalMutation: MutationBuilder<DataModel, 'internal'>
  internalAction: ActionBuilder<DataModel, 'internal'>
}

type Bundle = {
  zq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'public'>
  zm: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'public'>
  za: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'public'>
  ziq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'internal'>
  zim: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'internal'>
  zia: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'internal'>
}

export function initZodvex(server: Server, options: {
  wrapDb?: boolean
  registry?: () => any
  tableMap?: () => any
} = {}): Bundle {
  return (_libInitZodvex as any)(schema, server, {
    ...options,
    registry: options.registry ?? _registry,
    tableMap: options.tableMap ?? _tableMap,
  }) as Bundle
}
