// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { zx } from 'zodvex'

let _cached
export const zodTableMap = () => (_cached ??= (async () => {
  const refs = await Promise.all([
    import('../models/activity.js').then(m => ["activities", m.ActivityModel]),
    import('../models/notification.js').then(m => ["notifications", m.NotificationModel]),
    import('../models/comment.js').then(m => ["comments", m.CommentModel]),
    import('../models/user.js').then(m => ["users", m.UserModel]),
    import('../models/task.js').then(m => ["tasks", m.TaskModel])
  ].map(p => p.then(([_, m]) => m)))
  return {
    "activities": { doc: zx.doc(refs[0]), insert: zx.base(refs[0]) },
    "notifications": { doc: zx.doc(refs[1]), insert: zx.base(refs[1]) },
    "comments": { doc: zx.doc(refs[2]), insert: zx.base(refs[2]) },
    "users": { doc: zx.doc(refs[3]), insert: zx.base(refs[3]) },
    "tasks": { doc: zx.doc(refs[4]), insert: zx.base(refs[4]) }
  }
})())
