// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

type ZodTableMap = Record<string, { doc: import('zod/v4/core').$ZodType; insert: import('zod/v4/core').$ZodType }>
export declare const zodTableMap: () => Promise<ZodTableMap>
