import type { OptionalRestArgsOrSkip } from 'convex/react'
import { useMutation, useQuery } from 'convex/react'
import type { FunctionArgs, FunctionReference, FunctionReturnType } from 'convex/server'
import { getFunctionName } from 'convex/server'
import { z } from 'zod'
import type { AnyRegistry } from '../types'
import { stripUndefined } from '../utils'

/**
 * Creates zodvex-aware React hooks that automatically decode query results
 * and encode mutation arguments using the Zod schemas in the registry.
 *
 * Returned hooks are drop-in replacements for Convex's `useQuery` and
 * `useMutation` — they delegate to the real hooks, then apply codec
 * transforms so that runtime types (e.g. Date) are used instead of wire
 * types (e.g. number timestamps).
 *
 * @param registry - A map of function paths to `{ args?, returns? }` Zod schemas.
 *   Typically generated by zodvex codegen into `_zodvex/client.ts`.
 *
 * @example
 * ```typescript
 * import { zodvexRegistry } from '../_zodvex/client'
 * export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)
 *
 * // In a component:
 * const tasks = useZodQuery(api.tasks.list, { status: 'active' })
 * //    ^? Task[] — createdAt is Date, not number
 * ```
 */
export function createZodvexHooks<R extends AnyRegistry>(registry: R) {
  /**
   * Drop-in replacement for Convex's `useQuery`.
   *
   * Delegates to the real `useQuery` and then decodes the wire result through
   * the `returns` schema in the registry (if one exists for this function).
   *
   * - Loading state (`undefined`) passes through unchanged.
   * - Functions not in the registry return the raw wire result.
   */
  function useZodQuery<Query extends FunctionReference<'query', any, any, any>>(
    ref: Query,
    ...restArgs: OptionalRestArgsOrSkip<Query>
  ): FunctionReturnType<Query> | undefined {
    const wireResult = useQuery(ref, ...restArgs)

    // Loading state — Convex returns undefined while the subscription is pending
    if (wireResult === undefined) return undefined

    const path = getFunctionName(ref)
    const entry = registry[path]

    // No codec registered for this function — pass through raw wire data
    if (!entry?.returns) return wireResult

    // Decode: wire format -> runtime types (e.g., timestamp number -> Date)
    return entry.returns.parse(wireResult)
  }

  /**
   * Drop-in replacement for Convex's `useMutation`.
   *
   * Returns an async function that:
   * 1. Encodes the args through the `args` schema (runtime -> wire format)
   * 2. Calls the real mutation with the wire args
   * 3. Decodes the result through the `returns` schema (wire -> runtime format)
   *
   * Functions not in the registry pass args and results through unchanged.
   */
  function useZodMutation<Mutation extends FunctionReference<'mutation', any, any, any>>(
    ref: Mutation
  ) {
    const rawMutate = useMutation(ref)
    const path = getFunctionName(ref)
    const entry = registry[path]

    return async (args: FunctionArgs<Mutation>): Promise<FunctionReturnType<Mutation>> => {
      // Encode args: runtime types -> wire format (e.g., Date -> timestamp)
      const wireArgs = entry?.args ? stripUndefined(z.encode(entry.args, args)) : args

      const wireResult = await (rawMutate as any)(wireArgs)

      // Decode result: wire format -> runtime types
      if (!entry?.returns) return wireResult
      return entry.returns.parse(wireResult)
    }
  }

  return { useZodQuery, useZodMutation }
}

/**
 * The return type of `createZodvexHooks` — useful for typing module-level
 * exports in generated client files.
 */
export type ZodvexHooks = ReturnType<typeof createZodvexHooks>
