import type { OptionalRestArgsOrSkip } from 'convex/react'
import { useMutation, useQuery } from 'convex/react'
import type { FunctionArgs, FunctionReference, FunctionReturnType } from 'convex/server'
import { getFunctionName } from 'convex/server'
import type { CodecHelpersOptions } from '../codecHelpers'
import { createCodecHelpers } from '../codecHelpers'
import type { AnyRegistry } from '../types'

/**
 * Creates zodvex-aware React hooks that automatically decode query results
 * and encode mutation arguments using the Zod schemas in the registry.
 *
 * Returned hooks are drop-in replacements for Convex's `useQuery` and
 * `useMutation` — they delegate to the real hooks, then apply codec
 * transforms so that runtime types (e.g. Date) are used instead of wire
 * types (e.g. number timestamps).
 *
 * @param registry - A map of function paths to `{ args?, returns? }` Zod schemas.
 *   Typically generated by zodvex codegen into `_zodvex/client.ts`.
 *
 * @example
 * ```typescript
 * import { zodvexRegistry } from '../_zodvex/client'
 * export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)
 *
 * // In a component:
 * const tasks = useZodQuery(api.tasks.list, { status: 'active' })
 * //    ^? Task[] — createdAt is Date, not number
 * ```
 */
export function createZodvexHooks<R extends AnyRegistry>(
  registry: R,
  options?: CodecHelpersOptions
) {
  const codec = createCodecHelpers(registry, options)

  /**
   * Drop-in replacement for Convex's `useQuery` with automatic codec decode.
   *
   * Delegates to the real `useQuery` and then decodes the wire result through
   * the `returns` schema in the registry (if one exists for this function).
   *
   * Two overloads:
   * 1. Rest-args (Convex-compatible): `useZodQuery(ref, args)` or `useZodQuery(ref, 'skip')`
   * 2. Union args (composable): `useZodQuery(ref, args | 'skip')` — for wrappers
   *    and conditional skip patterns where the decision is made upstream.
   *
   * - Loading state (`undefined`) passes through unchanged.
   * - Functions not in the registry return the raw wire result.
   */
  // Overload 1: drop-in compatible with Convex's useQuery
  function useZodQuery<Query extends FunctionReference<'query', any, any, any>>(
    ref: Query,
    ...args: OptionalRestArgsOrSkip<Query>
  ): FunctionReturnType<Query> | undefined
  // Overload 2: composable — accepts Args | 'skip' union for wrappers
  function useZodQuery<Query extends FunctionReference<'query', any, any, any>>(
    ref: Query,
    args: Query['_args'] | 'skip'
  ): FunctionReturnType<Query> | undefined
  // Implementation
  function useZodQuery(ref: FunctionReference<'query', any, any, any>, ...restArgs: any[]) {
    const args = restArgs[0]

    // Encode args: runtime types -> wire format (e.g., Date -> timestamp).
    // Unlike mutations (imperative, user-triggered), hooks fire synchronously
    // during render — an encode error would crash the page. On failure, warn
    // and auto-skip the query (return undefined = loading state).
    let wireArgs: any = 'skip'
    if (args !== 'skip') {
      try {
        wireArgs = codec.encodeArgs(ref, args)
      } catch (err) {
        const path = getFunctionName(ref)
        console.warn(
          `[zodvex] Encode args failed for ${path}, auto-skipping query: ${err instanceof Error ? err.message : String(err)}`
        )
        // wireArgs stays 'skip' — DO NOT early-return, useQuery must run every render
      }
    }

    const wireResult = useQuery(
      ref,
      ...((wireArgs === 'skip' ? ['skip'] : [wireArgs]) as OptionalRestArgsOrSkip<typeof ref>)
    )

    // Loading state — Convex returns undefined while the subscription is pending
    if (wireResult === undefined) return undefined

    // Decode: wire format -> runtime types (e.g., timestamp number -> Date)
    return codec.decodeResult(ref, wireResult)
  }

  /**
   * Drop-in replacement for Convex's `useMutation`.
   *
   * Returns an async function that:
   * 1. Encodes the args through the `args` schema (runtime -> wire format)
   * 2. Calls the real mutation with the wire args
   * 3. Decodes the result through the `returns` schema (wire -> runtime format)
   *
   * Functions not in the registry pass args and results through unchanged.
   */
  function useZodMutation<Mutation extends FunctionReference<'mutation', any, any, any>>(
    ref: Mutation
  ) {
    const rawMutate = useMutation(ref)

    return async (args: FunctionArgs<Mutation>): Promise<FunctionReturnType<Mutation>> => {
      // Encode args: runtime types -> wire format (e.g., Date -> timestamp)
      const wireArgs = codec.encodeArgs(ref, args)

      const wireResult = await (rawMutate as any)(wireArgs)

      // Decode result: wire format -> runtime types
      return codec.decodeResult(ref, wireResult)
    }
  }

  return { useZodQuery, useZodMutation }
}

/**
 * The return type of `createZodvexHooks` — useful for typing module-level
 * exports in generated client files.
 */
export type ZodvexHooks = ReturnType<typeof createZodvexHooks>
