import type { FunctionReference } from 'convex/server'
import type { z } from 'zod'
import type { $ZodIssue } from 'zod/v4/core'
import { safeEncode } from './normalizeCodecPaths'
import type { AnyRegistry } from './types'
import { stripUndefined } from './utils'
import { $ZodError, safeParse } from './zod-core'

/**
 * Resolves a Convex FunctionReference to its string path.
 *
 * Mirrors `getFunctionName` from `convex/server` but without the server import.
 * Reads the well-known `Symbol.for('functionName')` that Convex attaches to all
 * function references — the same symbol used by Convex's own browser client.
 */
const functionNameSymbol = Symbol.for('functionName')

function resolveFunctionPath(ref: FunctionReference<any, any, any, any>): string {
  if (typeof ref === 'string') return ref
  const name = (ref as any)[functionNameSymbol]
  if (!name) {
    throw new Error(
      `Expected a Convex function reference (e.g. api.file.func), but received ${JSON.stringify(ref)}`
    )
  }
  return name
}

/**
 * Options for codec helper behavior.
 */
export type BoundaryHelpersOptions = {
  /**
   * How to handle decode failures (schema validation errors on wire data).
   *
   * - `'warn'` (default): log a console.warn and return raw wire data untransformed.
   * - `'throw'`: throw a ZodvexDecodeError (extends z.ZodError).
   */
  onDecodeError?: 'warn' | 'throw'
}

/**
 * Decode error with function path and wire data context.
 * Extends $ZodError from zod/v4/core for compatibility with both zod and zod/mini.
 * instanceof $ZodError checks work in both variants.
 */
export class ZodvexDecodeError extends $ZodError {
  readonly functionPath: string
  readonly wireData: unknown

  constructor(functionPath: string, issues: $ZodIssue[], wireData: unknown) {
    super(issues)
    this.functionPath = functionPath
    this.wireData = wireData
    this.name = 'ZodvexDecodeError'
  }
}

/**
 * Creates shared encode/decode helpers bound to a zodvex registry.
 *
 * These are the core primitives used by all codec boundary implementations:
 * - `encodeArgs`: runtime types -> wire format (e.g., Date -> timestamp number)
 * - `decodeResult`: wire format -> runtime types (e.g., timestamp number -> Date)
 *
 * Both look up the function reference in the registry to find the appropriate
 * Zod schema, then apply the codec transform. Functions not in the registry
 * (or without the relevant schema) pass through unchanged.
 *
 * @param registry - A map of function paths to `{ args?, returns? }` Zod schemas.
 *   Typically generated by zodvex codegen into `_zodvex/api.ts`.
 * @param options - Optional configuration for decode error behavior.
 */
export function createBoundaryHelpers(registry: AnyRegistry, options?: BoundaryHelpersOptions) {
  const onDecodeError = options?.onDecodeError ?? 'warn'
  const warnedPaths = new Set<string>()

  /**
   * Encode args from runtime types to wire format.
   *
   * Uses `safeEncode` (not raw `z.encode`) to normalize codec-internal
   * error paths in ZodErrors, then strips undefined values for Convex
   * serialization compatibility.
   *
   * Passthrough when:
   * - args is null/undefined
   * - function is not in the registry
   * - registry entry has no args schema
   */
  function encodeArgs(ref: FunctionReference<any, any, any, any>, args: any): any {
    if (args == null) return args
    const path = resolveFunctionPath(ref)
    const entry = registry[path]
    if (!entry?.args) {
      if (entry === undefined && !warnedPaths.has(path)) {
        warnedPaths.add(path)
        console.debug(
          `[zodvex] No registry entry for "${path}" — args will not be codec-encoded. ` +
            'If this function uses zodvex wrappers, run `zodvex generate` to update the registry.'
        )
      }
      return args
    }
    return stripUndefined(safeEncode(entry.args, args))
  }

  /**
   * Decode a wire result back to runtime types.
   *
   * Uses `.safeParse()` to decode. On failure:
   * - 'warn' (default): logs warning, returns raw wireResult
   * - 'throw': throws ZodvexDecodeError (extends z.ZodError)
   *
   * Passthrough when:
   * - function is not in the registry
   * - registry entry has no returns schema
   */
  function decodeResult(ref: FunctionReference<any, any, any, any>, wireResult: any): any {
    const path = resolveFunctionPath(ref)
    const entry = registry[path]
    if (!entry?.returns) return wireResult

    const result = safeParse(entry.returns, wireResult)
    if (result.success) return result.data

    if (onDecodeError === 'throw') {
      throw new ZodvexDecodeError(path, result.error.issues, wireResult)
    }

    // Default: warn and return raw wire data
    const preview = JSON.stringify(wireResult)
    const truncated = preview.length > 200 ? `${preview.slice(0, 200)}...` : preview
    console.warn(
      `[zodvex] Decode failed for ${path}: ${result.error.issues.map((i: $ZodIssue) => `${i.path.join('.')}: ${i.message}`).join(', ')}. Returning raw wire data. Preview: ${truncated}`
    )
    return wireResult
  }

  return { encodeArgs, decodeResult }
}

export type BoundaryHelpers = ReturnType<typeof createBoundaryHelpers>
