import type { FunctionReference } from 'convex/server'
import { getFunctionName } from 'convex/server'
import { safeEncode } from './normalizeCodecPaths'
import type { AnyRegistry } from './types'
import { stripUndefined } from './utils'

/**
 * Creates shared encode/decode helpers bound to a zodvex registry.
 *
 * These are the core primitives used by all codec boundary implementations:
 * - `encodeArgs`: runtime types -> wire format (e.g., Date -> timestamp number)
 * - `decodeResult`: wire format -> runtime types (e.g., timestamp number -> Date)
 *
 * Both look up the function reference in the registry to find the appropriate
 * Zod schema, then apply the codec transform. Functions not in the registry
 * (or without the relevant schema) pass through unchanged.
 *
 * @param registry - A map of function paths to `{ args?, returns? }` Zod schemas.
 *   Typically generated by zodvex codegen into `_zodvex/api.ts`.
 */
export function createCodecHelpers(registry: AnyRegistry) {
  /**
   * Encode args from runtime types to wire format.
   *
   * Uses `safeEncode` (not raw `z.encode`) to normalize codec-internal
   * error paths in ZodErrors, then strips undefined values for Convex
   * serialization compatibility.
   *
   * Passthrough when:
   * - args is null/undefined
   * - function is not in the registry
   * - registry entry has no args schema
   */
  function encodeArgs(ref: FunctionReference<any, any, any, any>, args: any): any {
    const path = getFunctionName(ref)
    const entry = registry[path]
    return entry?.args && args != null ? stripUndefined(safeEncode(entry.args, args)) : args
  }

  /**
   * Decode a wire result back to runtime types.
   *
   * Uses `schema.parse(wireResult)` to decode — this runs the codec's
   * decode direction (e.g., timestamp number -> Date).
   *
   * Passthrough when:
   * - function is not in the registry
   * - registry entry has no returns schema
   */
  function decodeResult(ref: FunctionReference<any, any, any, any>, wireResult: any): any {
    const path = getFunctionName(ref)
    const entry = registry[path]
    if (!entry?.returns) return wireResult
    return entry.returns.parse(wireResult)
  }

  return { encodeArgs, decodeResult }
}
