import {
  $ZodCodec,
  $ZodNullable,
  $ZodObject,
  $ZodOptional,
  $ZodType
} from '../../internal/zod-core'
import { zx } from '../../internal/zx'
import type {
  DiscoveredFunction,
  DiscoveredModel,
  FunctionEmbeddedCodec,
  ModelEmbeddedCodec
} from './discover'
import { type CodecRef, type ZodToSourceContext, zodToSource } from './zodToSource'
import { tableFromModel } from '../../internal/schema'

const HEADER = `// AUTO-GENERATED by zodvex — do not edit
// Run \`zodvex generate\` to regenerate
`

// ---------------------------------------------------------------------------
// Convex validator → source code walker
//
// Walks a Convex validator graph (output of zodToConvex) and emits an
// equivalent `v.*` source expression. Used by generateTablesFile so the
// schema-eval isolate can import `_zodvex/tables.ts` without loading zod,
// zodvex, or any model file.
// ---------------------------------------------------------------------------

interface ConvexValidator {
  kind: string
  isOptional?: 'required' | 'optional'
  tableName?: string
  value?: unknown
  fields?: Record<string, ConvexValidator>
  element?: ConvexValidator
  members?: ConvexValidator[]
  keys?: ConvexValidator
  values?: ConvexValidator
}

function validatorToSource(val: ConvexValidator): string {
  const opt = val.isOptional === 'optional'
  const wrap = (s: string) => (opt ? `v.optional(${s})` : s)

  switch (val.kind) {
    case 'string':
      return wrap('v.string()')
    case 'float64':
      return wrap('v.float64()')
    case 'int64':
      return wrap('v.int64()')
    case 'boolean':
      return wrap('v.boolean()')
    case 'null':
      return wrap('v.null()')
    case 'any':
      return wrap('v.any()')
    case 'bytes':
      return wrap('v.bytes()')
    case 'id':
      return wrap(`v.id(${JSON.stringify(val.tableName)})`)
    case 'literal':
      return wrap(`v.literal(${JSON.stringify(val.value)})`)
    case 'array':
      return wrap(`v.array(${validatorToSource(val.element as ConvexValidator)})`)
    case 'object': {
      const entries = Object.entries(val.fields ?? {})
        .map(([k, v]) => `${JSON.stringify(k)}: ${validatorToSource(v)}`)
        .join(', ')
      return wrap(`v.object({ ${entries} })`)
    }
    case 'union': {
      const members = (val.members ?? []).map(validatorToSource).join(', ')
      return wrap(`v.union(${members})`)
    }
    case 'record': {
      const keys = validatorToSource(val.keys as ConvexValidator)
      const values = validatorToSource(val.values as ConvexValidator)
      return wrap(`v.record(${keys}, ${values})`)
    }
    default:
      throw new Error(`generateTablesFile: unsupported validator kind '${val.kind}'`)
  }
}

interface ConvexTable {
  validator: ConvexValidator
  indexes: Array<{ indexDescriptor: string; fields: string[] }>
  stagedDbIndexes: Array<{ indexDescriptor: string; fields: string[] }>
  searchIndexes: Array<{ indexDescriptor: string; searchField: string; filterFields: string[] }>
  stagedSearchIndexes: Array<{
    indexDescriptor: string
    searchField: string
    filterFields: string[]
  }>
  vectorIndexes: Array<{
    indexDescriptor: string
    vectorField: string
    dimensions: number
    filterFields: string[]
  }>
  stagedVectorIndexes: Array<{
    indexDescriptor: string
    vectorField: string
    dimensions: number
    filterFields: string[]
  }>
}

function tableToSource(t: ConvexTable): string {
  const lines = [`defineTable(${validatorToSource(t.validator)})`]
  for (const ix of t.indexes) {
    lines.push(`    .index(${JSON.stringify(ix.indexDescriptor)}, ${JSON.stringify(ix.fields)})`)
  }
  for (const ix of t.searchIndexes) {
    lines.push(
      `    .searchIndex(${JSON.stringify(ix.indexDescriptor)}, ${JSON.stringify({
        searchField: ix.searchField,
        filterFields: ix.filterFields
      })})`
    )
  }
  for (const ix of t.vectorIndexes) {
    lines.push(
      `    .vectorIndex(${JSON.stringify(ix.indexDescriptor)}, ${JSON.stringify({
        vectorField: ix.vectorField,
        dimensions: ix.dimensions,
        filterFields: ix.filterFields
      })})`
    )
  }
  return lines.join('\n')
}

export type GeneratedFile = { js: string; dts: string }

/**
 * Produces a structural fingerprint for a ZodCodec by serializing its
 * wire (in) and runtime (out) schemas. Two factory-created codec instances
 * with the same arguments produce the same fingerprint, enabling dedup
 * even when object identity differs.
 */
function fingerprintCodec(schema: $ZodType): string {
  if (!(schema instanceof $ZodCodec)) return ''
  return `${zodToSource(schema._zod.def.in)}|${zodToSource(schema._zod.def.out)}`
}

/**
 * Generates the schema file content — re-exports of all discovered models.
 * Returns { js, dts } with .js import extensions (TS resolves types from .js targets).
 */
export function generateSchemaFile(models: DiscoveredModel[]): GeneratedFile {
  const exports = models
    .map(m => {
      const importPath = `../${m.sourceFile.replace(/\.ts$/, '.js')}`
      return `export { ${m.exportName} } from '${importPath}'`
    })
    .join('\n')

  const content = `${HEADER}\n${exports}\n`
  return { js: content, dts: content }
}

type SchemaRef = {
  importPath: string
  exportName: string
  /**
   * Property path relative to the model export, e.g. "schema.doc" for full
   * models or "schema" for union-slim. Emitted as `${exportName}.${schemaKey}`
   * unless `expression` is set.
   */
  schemaKey: string
  /**
   * Complete access expression to emit, e.g. "zx.doc(TaskModel)". Used for
   * slim models where there's no plain property path. When present, emitted
   * verbatim (the `zx` import is auto-added).
   */
  expression?: string
}

/** Emission helper: returns the full access expression for a SchemaRef. */
function refExpression(ref: SchemaRef): string {
  return ref.expression ?? `${ref.exportName}.${ref.schemaKey}`
}

export type CodecForGeneration = {
  exportName: string
  sourceFile: string
  schema: $ZodType
}

/**
 * Peels .optional() and .nullable() wrappers from a schema and checks
 * the identity map at each level. Returns the matched ref plus a
 * function that wraps an inner source string with the appropriate
 * optional/nullable syntax (chaining or functional for mini mode).
 */
function tryUnwrapToIdentity(
  schema: $ZodType,
  identityMap: Map<$ZodType, SchemaRef>,
  mini?: boolean
): { ref: SchemaRef; wrapSource: (inner: string) => string } | null {
  let current = schema
  const wrappers: Array<'optional' | 'nullable'> = []
  const maxDepth = 5

  for (let i = 0; i < maxDepth; i++) {
    if (current instanceof $ZodOptional) {
      wrappers.push('optional')
      current = current._zod.def.innerType
    } else if (current instanceof $ZodNullable) {
      wrappers.push('nullable')
      current = current._zod.def.innerType
    } else {
      break
    }

    const ref = identityMap.get(current)
    if (ref) {
      // Wrappers collected outermost-first, apply innermost-first
      const reversed = [...wrappers].reverse()
      return {
        ref,
        wrapSource: (inner: string) => {
          let result = inner
          for (const w of reversed) {
            result = mini ? `z.${w}(${result})` : `${result}.${w}()`
          }
          return result
        }
      }
    }
  }

  return null
}

/**
 * Checks if a ZodObject schema is structurally equivalent to
 * someModelSchema.partial() by comparing field-by-field identity.
 *
 * Zod's .partial() wraps each field in ZodOptional, preserving
 * the inner type identity. So we check: same keys, each field
 * is ZodOptional, and each inner type === the original model field.
 */
function tryMatchPartial(
  schema: $ZodType,
  identityMap: Map<$ZodType, SchemaRef>,
  mini?: boolean
): { ref: SchemaRef; wrapSource: (inner: string) => string } | null {
  if (!(schema instanceof $ZodObject)) return null
  const candidateShape = schema._zod.def.shape as Record<string, $ZodType>
  const candidateKeys = Object.keys(candidateShape).sort()

  for (const [modelSchema, ref] of identityMap) {
    if (!(modelSchema instanceof $ZodObject)) continue
    const modelShape = modelSchema._zod.def.shape as Record<string, $ZodType>
    const modelKeys = Object.keys(modelShape).sort()

    // Same key count and same keys
    if (candidateKeys.length !== modelKeys.length) continue
    if (candidateKeys.some((k, i) => k !== modelKeys[i])) continue

    // Every candidate field must be ZodOptional wrapping the model field by identity
    let allMatch = true
    for (const key of candidateKeys) {
      const candidateField = candidateShape[key]
      if (!(candidateField instanceof $ZodOptional)) {
        allMatch = false
        break
      }
      const inner = candidateField._zod.def.innerType
      if (inner !== modelShape[key]) {
        allMatch = false
        break
      }
    }

    if (allMatch) {
      return {
        ref,
        wrapSource: (inner: string) => (mini ? `z.partial(${inner})` : `${inner}.partial()`)
      }
    }
  }

  return null
}

/**
 * Derives a descriptive variable name for a model-embedded codec from
 * the model export name and the access path.
 *
 * Examples:
 *   ('UserModel', '.shape.email')                                      → '_userEmail'
 *   ('ActivityModel', '.shape.payload._zod.def.options[0].shape.email') → '_activityPayloadEmail'
 *   ('patients', '.shape.firstName')                                    → '_patientsFirstName'
 */
function deriveCodecVarName(modelExportName: string, accessPath: string): string {
  const base = modelExportName.replace(/Model$/, '')
  const prefix = base[0].toLowerCase() + base.slice(1)

  const fields = [...accessPath.matchAll(/\.shape\.(\w+)/g)].map(m => m[1])
  if (fields.length === 0) return `_${prefix}Codec`

  const fieldPart = fields.map((f, i) => (i === 0 ? f : f[0].toUpperCase() + f.slice(1))).join('')

  return `_${prefix}${fieldPart[0].toUpperCase() + fieldPart.slice(1)}`
}

/**
 * Generates the api.ts file content — function-to-schema registry.
 */
export function generateApiFile(
  functions: DiscoveredFunction[],
  models: DiscoveredModel[],
  codecs?: CodecForGeneration[],
  modelCodecs?: ModelEmbeddedCodec[],
  functionCodecs?: FunctionEmbeddedCodec[],
  options?: { mini?: boolean }
): GeneratedFile {
  // Build identity map: runtime schema object → model reference string
  const identityMap = new Map<$ZodType, SchemaRef>()
  const neededModelImports = new Set<string>()

  for (const model of models) {
    const importPath = `../${model.sourceFile.replace(/\.ts$/, '.js')}`

    if (model.schemas) {
      // Full model: existing behavior — schema.doc, schema.insert, etc.
      for (const key of ['doc', 'insert', 'update', 'docArray', 'paginatedDoc'] as const) {
        identityMap.set(model.schemas[key] as $ZodType, {
          importPath,
          exportName: model.exportName,
          schemaKey: `schema.${key}`
        })
      }
    } else if (model._modelRef) {
      // Slim model: schemas live in the per-model zx WeakMap cache, not on the
      // model object. Populate identityMap with cached `zx.*` instances so
      // function code like `returns: zx.doc(SlimModel)` resolves by identity.
      // Emit `zx.doc(SlimModel)` (not `SlimModel.doc`) since slim models have
      // no such property.
      const ref = model._modelRef as any
      const slimKeys = [
        { key: 'doc', schema: zx.doc(ref) as $ZodType, expr: `zx.doc(${model.exportName})` },
        { key: 'insert', schema: zx.base(ref) as $ZodType, expr: `zx.base(${model.exportName})` },
        { key: 'base', schema: zx.base(ref) as $ZodType, expr: `zx.base(${model.exportName})` },
        {
          key: 'update',
          schema: zx.update(ref) as $ZodType,
          expr: `zx.update(${model.exportName})`
        },
        {
          key: 'docArray',
          schema: zx.docArray(ref) as $ZodType,
          expr: `zx.docArray(${model.exportName})`
        }
      ]
      for (const { key, schema, expr } of slimKeys) {
        identityMap.set(schema, {
          importPath,
          exportName: model.exportName,
          schemaKey: key,
          expression: expr
        })
      }
      // Union slim retains `.schema` on the model object — map that too so
      // `returns: SlimModel.schema` resolves as a direct property reference.
      if (ref.schema instanceof $ZodType) {
        identityMap.set(ref.schema, {
          importPath,
          exportName: model.exportName,
          schemaKey: 'schema'
        })
      }
    }
  }

  // Build codec identity map for zodToSource
  const codecMap = new Map<$ZodType, CodecRef>()
  if (codecs) {
    for (const codec of codecs) {
      const importPath = `../${codec.sourceFile.replace(/\.ts$/, '.js')}`
      codecMap.set(codec.schema, {
        exportName: codec.exportName,
        sourceFile: importPath
      })
    }
  }

  // Add model-embedded codecs to the codecMap (exported codecs take precedence)
  const modelCodecVars: { varName: string; expression: string; modelExportName: string }[] = []
  const MODEL_CODEC_SENTINEL = '__model_codec__'
  // Build slim model lookup for codec expression generation
  const slimModelNames = new Set(
    models.filter(m => !m.schemas && m._modelRef).map(m => m.exportName)
  )
  if (modelCodecs) {
    for (const mc of modelCodecs) {
      // Skip if this codec is already in codecMap (exported codec takes precedence)
      if (codecMap.has(mc.codec)) continue

      const varName = deriveCodecVarName(mc.modelExportName, mc.accessPath)
      // Slim models: schemas are cached in the zx WeakMap, accessed via
      //   zx.doc(Model) / zx.base(Model) / zx.update(Model).
      // Full models: schema bundle is at Model.schema.{doc,insert,update,...}.
      const isSlim = slimModelNames.has(mc.modelExportName)
      let schemaAccess: string
      if (isSlim) {
        // Map walkModelCodecs keys (doc/insert/update) to their zx equivalents.
        const slimKey = mc.schemaKey === 'insert' ? 'base' : mc.schemaKey
        schemaAccess = `zx.${slimKey}(${mc.modelExportName})`
      } else {
        schemaAccess = `${mc.modelExportName}.schema.${mc.schemaKey}`
      }
      const expression = `extractCodec(${schemaAccess}${mc.accessPath})`
      modelCodecVars.push({ varName, expression, modelExportName: mc.modelExportName })
      codecMap.set(mc.codec, {
        exportName: varName,
        sourceFile: MODEL_CODEC_SENTINEL
      })
    }
  }

  // Resolve function-embedded codecs against existing codecs by structural fingerprint.
  // Factory-created codecs (like tagged(), encrypted()) produce new instances each call,
  // so identity matching fails. Fingerprinting matches by wire+runtime schema structure,
  // allowing us to reference the model/standalone codec instead of importing the function.
  // This avoids circular imports: functions.ts → _zodvex/api.ts → functionFile.ts → functions.ts
  if (functionCodecs) {
    const fingerprintMap = new Map<string, CodecRef>()
    for (const [codecSchema, ref] of codecMap) {
      const fp = fingerprintCodec(codecSchema)
      if (fp) fingerprintMap.set(fp, ref)
    }

    for (const fc of functionCodecs) {
      if (codecMap.has(fc.codec)) continue

      const fp = fingerprintCodec(fc.codec)
      const matchingRef = fp ? fingerprintMap.get(fp) : undefined
      if (matchingRef) {
        codecMap.set(fc.codec, matchingRef)
      } else {
        console.warn(
          `[zodvex] Warning: Codec in ${fc.functionExportName}() (${fc.accessPath}) has no matching model or exported codec. ` +
            `Export it standalone for full client-side codec support.`
        )
      }
    }
  }

  const zodToSourceCtx: ZodToSourceContext = {
    codecMap,
    neededCodecImports: new Map(),
    undiscoverableCodecs: [],
    mini: options?.mini
  }

  // Track which imports we need
  let needsZod = false
  let needsZx = false

  function emitRef(ref: SchemaRef): string {
    neededModelImports.add(ref.exportName)
    const expr = refExpression(ref)
    // Slim-model refs use zx.* helpers; ensure `zx` is imported in the output.
    if (ref.expression?.startsWith('zx.')) needsZx = true
    return expr
  }

  // Resolve each schema to either a model reference or serialized source
  function resolveSchema(schema: $ZodType | unknown): string {
    if (!schema) return 'undefined'
    const s = schema as $ZodType

    // 1. Direct identity match
    const ref = identityMap.get(s)
    if (ref) return emitRef(ref)

    // 2. Wrapper-aware identity match (peel .nullable()/.optional())
    const unwrapped = tryUnwrapToIdentity(s, identityMap, options?.mini)
    if (unwrapped) return unwrapped.wrapSource(emitRef(unwrapped.ref))

    // 3. Partial-aware match (detect .partial() of a model schema)
    const partialMatch = tryMatchPartial(s, identityMap, options?.mini)
    if (partialMatch) return partialMatch.wrapSource(emitRef(partialMatch.ref))

    // 4. Fall back to zodToSource (with codec context)
    const source = zodToSource(s, zodToSourceCtx)
    if (source.includes('z.')) needsZod = true
    if (source.includes('zx.')) needsZx = true
    return source
  }

  // Build registry entries
  const entries = functions
    .map(fn => {
      const args = resolveSchema(fn.zodArgs)
      const returns = resolveSchema(fn.zodReturns)
      return `  '${fn.functionPath}': {\n    args: ${args},\n    returns: ${returns},\n  }`
    })
    .join(',\n')

  // Determine which model codec vars were actually used (referenced by zodToSource)
  const usedModelCodecVars = modelCodecVars.filter(mc => {
    const sentinelExports = zodToSourceCtx.neededCodecImports.get(MODEL_CODEC_SENTINEL)
    return sentinelExports?.has(mc.varName)
  })

  // Add model imports for models referenced by used model codec vars.
  // Slim codec vars use zx.base(Model)/zx.doc(Model) expressions — require zx import.
  if (usedModelCodecVars.length > 0) {
    for (const mc of usedModelCodecVars) {
      neededModelImports.add(mc.modelExportName)
      if (mc.expression.includes('zx.')) needsZx = true
    }
  }

  // Build imports
  const imports: string[] = []
  const zodImport = options?.mini ? 'zod/mini' : 'zod'
  if (needsZod) imports.push(`import { z } from '${zodImport}'`)

  // Build single client-safe zodvex import (root full path or zodvex/mini)
  const zodvexImport = options?.mini ? 'zodvex/mini' : 'zodvex'
  const coreImports: string[] = []
  if (needsZx) coreImports.push('zx')
  if (usedModelCodecVars.length > 0) coreImports.push('extractCodec')
  if (coreImports.length > 0) {
    imports.push(`import { ${coreImports.join(', ')} } from '${zodvexImport}'`)
  }

  for (const exportName of neededModelImports) {
    const model = models.find(m => m.exportName === exportName)
    if (model) {
      const importPath = `../${model.sourceFile.replace(/\.ts$/, '.js')}`
      imports.push(`import { ${exportName} } from '${importPath}'`)
    }
  }

  // Codec imports (collected by zodToSource via context)
  for (const [importPath, exportNames] of zodToSourceCtx.neededCodecImports) {
    if (importPath === MODEL_CODEC_SENTINEL) continue
    const names = Array.from(exportNames).sort().join(', ')
    imports.push(`import { ${names} } from '${importPath}'`)
  }

  const importSection = imports.length > 0 ? `${imports.join('\n')}\n\n` : ''

  // Build codec helper var declarations
  const allCodecVars = usedModelCodecVars.map(mc => `const ${mc.varName} = ${mc.expression}`)
  const codecVarSection = allCodecVars.length > 0 ? `${allCodecVars.join('\n')}\n\n` : ''

  const registryEntries = entries.length > 0 ? `${entries},\n` : ''
  const js = `${HEADER}\n${importSection}${codecVarSection}export const zodvexRegistry = {\n${registryEntries}}\n`

  const dts = options?.mini
    ? `${HEADER}
import type { $ZodType } from 'zod/v4/core'

export declare const zodvexRegistry: Record<string, { args: $ZodType; returns: $ZodType | undefined }>
`
    : `${HEADER}
import type { ZodTypeAny } from 'zod'

export declare const zodvexRegistry: Record<string, { args: ZodTypeAny; returns: ZodTypeAny | undefined }>
`

  return { js, dts }
}

/**
 * Generates the server.ts file content — concrete context types for the app's schema.
 *
 * These parallel Convex's _generated/server.ts exports (QueryCtx, MutationCtx, ActionCtx)
 * but with zodvex's codec-wrapped db types baked in.
 */
export function generateServerFile(): GeneratedFile {
  const js = `${HEADER}`

  const dts = `${HEADER}
import type { DataModel } from '../_generated/dataModel.js'
import type { ZodvexActionCtx, ZodvexMutationCtx, ZodvexQueryCtx } from 'zodvex/server'
import type schema from '../schema.js'

type DecodedDocs = (typeof schema)['__decodedDocs']

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>
`

  return { js, dts }
}

/**
 * Generates the client file content — pre-bound hooks and client factory.
 * Returns { js, dts } for .js + .d.ts output.
 */
/**
 * Generates the api.lazy file content — a tiny wrapper that exposes the
 * `zodvexRegistry` as a thunk that dynamic-imports `_zodvex/api.js`.
 *
 * Server-side consumers (e.g. `convex/functions.ts`) should pass this thunk
 * as `initZodvex`'s `registry` option:
 *
 *     import { zodvexRegistry } from './_zodvex/api.lazy.js'
 *     export const { zq, zm, za } = initZodvex(schema, server, {
 *       registry: zodvexRegistry,   // no arrow wrap — this is already a thunk
 *     })
 *
 * The dynamic import lets esbuild hoist the registry's transitive schema
 * graph out of the entrypoint's static bundle and into a chunk under
 * `_deps/`. Per-entrypoint heap drops drastically under Convex's new
 * per-entrypoint analysis without changing the registry's runtime
 * behavior.
 */
export function generateApiLazyFile(): GeneratedFile {
  const js = `${HEADER}
let _cached
export const zodvexRegistry = () => (_cached ??= import('./api.js').then(m => m.zodvexRegistry))
`

  const dts = `${HEADER}
import type { zodvexRegistry as RegistryData } from './api'

export declare const zodvexRegistry: () => Promise<typeof RegistryData>
`

  return { js, dts }
}

/**
 * Generates the tables file — a pure Convex `_zodvex/tables.ts` default-export
 * object mapping table-name → `defineTable(...).index(...)`.
 *
 * The whole point of this file is to be importable from `convex/schema.ts`
 * WITHOUT pulling zod or zodvex into the schema-eval isolate. Convex's
 * per-entrypoint analyzer loads schema.ts independently in a 64 MB budget,
 * and the only way to keep large model graphs under that is to strip the
 * zod runtime from schema-eval entirely.
 *
 * User schema.ts becomes:
 *
 *     import { defineSchema } from 'convex/server'
 *     import tables from './_zodvex/tables'
 *     export default defineSchema(tables)
 *
 * Implementation: walks each model's live `TableDefinition` (built via
 * `tableFromModel`) and round-trips the validator + indexes back to
 * source. Each model's `name` property is the key in the default export.
 */
export function generateTablesFile(models: DiscoveredModel[]): GeneratedFile {
  const entries: string[] = []
  const typeImports: string[] = []
  const decodedDocsEntries: string[] = []

  for (const m of models) {
    if (!m._liveModel) continue
    const live = m._liveModel as { name: string; fields?: unknown; indexes?: unknown }
    // tableFromModel only knows about defineZodModel results — hand-rolled
    // models that use attachMeta directly may not have the expected shape.
    // Skip rather than throw so a project mixing styles still generates
    // the entries it can.
    if (live.fields === undefined || live.indexes === undefined) {
      console.warn(
        `[zodvex] Skipping tables.ts entry for '${m.exportName}' in ${m.sourceFile}: ` +
          'model is not a defineZodModel() result. Use defineZodModel() to enable the lazy-tables shape.'
      )
      continue
    }
    let table: ConvexTable
    try {
      table = tableFromModel(live as any) as unknown as ConvexTable
    } catch (err) {
      console.warn(
        `[zodvex] Skipping tables.ts entry for '${m.exportName}' in ${m.sourceFile}: ` +
          `${(err as Error).message}`
      )
      continue
    }
    const tableSrc = tableToSource(table)
    entries.push(`  ${JSON.stringify(live.name)}: ${tableSrc},`)

    // Type-only import + DecodedDocs entry for this table. Type imports
    // are erased at compile so this adds ZERO runtime cost to the
    // schema-eval isolate; we still get decoded doc types end-to-end.
    const importPath = `../${m.sourceFile.replace(/\.ts$/, '.js')}`
    typeImports.push(`import type { ${m.exportName} } from '${importPath}'`)
    decodedDocsEntries.push(`  ${JSON.stringify(live.name)}: typeof ${m.exportName}`)
  }

  // Single TypeScript source — Convex accepts .ts modules and tsc infers
  // per-table TableDefinition<VObject<...>> from the literal expression.
  // A separate .d.ts that says `Record<string, TableDefinition>` would
  // erase the per-table types and weaken the DataModel.
  const ts = `${HEADER}
import { defineTable } from 'convex/server'
import { v } from 'convex/values'
${typeImports.length > 0 ? `\n${typeImports.join('\n')}` : ''}
import type { DecodedDocFor } from 'zodvex/server'

export default {
${entries.join('\n')}
}

/**
 * Decoded document types per table — derived from each model's zod doc
 * schema. Used by \`defineZodvexSchema\` to attach \`__decodedDocs\` so
 * ctx.db return types in queries/mutations reflect codec-decoded shapes
 * (e.g. \`Date\` instead of \`number\` for \`zx.date()\` fields).
 *
 * Type-only — does NOT load zod at module init. Schema-eval stays thin.
 */
export type DecodedDocs = DecodedDocFor<{
${decodedDocsEntries.join('\n')}
}>
`

  // Returned in the .js slot for the existing emit pipeline; commands.ts
  // writes it to tables.ts (see writeIfChanged path below).
  return { js: ts, dts: '' }
}

/**
 * Generates the tableMap.lazy file — a tiny wrapper that exposes the
 * runtime `__zodTableMap` (consumed by initZodvex's DB codec wrappers)
 * as a thunk that dynamic-imports the heavy zod schemas.
 *
 * Mirrors api.lazy.js: schema.ts loads pure convex; the zod schemas
 * needed at runtime are reached only through this dynamic import.
 *
 * User functions.ts:
 *
 *     import { zodTableMap } from './_zodvex/tableMap.lazy'
 *     export const { zq, zm, za } = initZodvex(schema, server, {
 *       registry: zodvexRegistry,
 *       tableMap: zodTableMap,
 *     })
 */
export function generateTableMapLazyFile(models: DiscoveredModel[]): GeneratedFile {
  // The thunk dynamically imports each model file and rebuilds the
  // tableMap structure that defineZodSchema would have produced. Each
  // entry is `{ doc, insert }` — only the two schemas the DB wrapper
  // consumes at runtime.
  const imports: string[] = []
  const entries: string[] = []
  let included = 0
  for (const m of models) {
    if (!m._liveModel) continue
    const live = m._liveModel as { name: string; fields?: unknown; indexes?: unknown }
    // Same defineZodModel-shape guard as generateTablesFile — keep both
    // codegen outputs aligned on the same set of tables.
    if (live.fields === undefined || live.indexes === undefined) continue
    const importPath = `../${m.sourceFile.replace(/\.ts$/, '.js')}`
    const idx = included++
    imports.push(
      `    import('${importPath}').then(m => [${JSON.stringify(live.name)}, m.${m.exportName}])`
    )
    entries.push(
      `    ${JSON.stringify(live.name)}: { doc: zx.doc(refs[${idx}]), insert: zx.base(refs[${idx}]) }`
    )
  }

  const js = `${HEADER}
import { zx } from 'zodvex'

let _cached
export const zodTableMap = () => (_cached ??= (async () => {
  const refs = await Promise.all([
${imports.join(',\n')}
  ].map(p => p.then(([_, m]) => m)))
  return {
${entries.join(',\n')}
  }
})())
`

  const dts = `${HEADER}
type ZodTableMap = Record<string, { doc: import('zod/v4/core').$ZodType; insert: import('zod/v4/core').$ZodType }>
export declare const zodTableMap: () => Promise<ZodTableMap>
`

  return { js, dts }
}

export function generateClientFile(options?: { mini?: boolean }): GeneratedFile {
  const zodvexClientImport = options?.mini ? 'zodvex/mini' : 'zodvex'
  // --- JS ---
  const jsImports = [
    "import { createZodvexHooks } from 'zodvex/react'",
    "import { createZodvexReactClient } from 'zodvex/react'",
    "import { createZodvexClient } from 'zodvex/client'",
    `import { createBoundaryHelpers } from '${zodvexClientImport}'`,
    "import { zodvexRegistry } from './api.js'"
  ]

  const jsExports = [
    'export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)',
    '',
    'export const createClient = (options) =>',
    '  createZodvexClient(zodvexRegistry, options)',
    '',
    'export const createReactClient = (options) =>',
    '  createZodvexReactClient(zodvexRegistry, options)',
    '',
    'export const { encodeArgs, decodeResult } = createBoundaryHelpers(zodvexRegistry)'
  ]

  const js = `${HEADER}\n${jsImports.join('\n')}\n\n${jsExports.join('\n')}\n`

  // --- DTS ---
  const dtsImports = [
    "import type { ZodvexHooks } from 'zodvex/react'",
    "import type { ZodvexClientOptions, ZodvexClient } from 'zodvex/client'",
    "import type { ZodvexReactClientOptions, ZodvexReactClient } from 'zodvex/react'",
    `import type { BoundaryHelpers } from '${zodvexClientImport}'`
  ]

  const dtsDeclarations = [
    "export declare const useZodQuery: ZodvexHooks['useZodQuery']",
    "export declare const useZodMutation: ZodvexHooks['useZodMutation']",
    '',
    'export declare const createClient: (options: ZodvexClientOptions) => ZodvexClient',
    '',
    'export declare const createReactClient: (options: ZodvexReactClientOptions) => ZodvexReactClient',
    '',
    "export declare const encodeArgs: BoundaryHelpers['encodeArgs']",
    "export declare const decodeResult: BoundaryHelpers['decodeResult']"
  ]

  const dts = `${HEADER}\n${dtsImports.join('\n')}\n\n${dtsDeclarations.join('\n')}\n`

  return { js, dts }
}
