import { readCodecBrand } from '../../internal/meta'
import { tableFromModel } from '../../internal/schema'
import {
  $ZodCodec,
  $ZodNullable,
  $ZodObject,
  $ZodOptional,
  $ZodType
} from '../../internal/zod-core'
import { zx } from '../../internal/zx'
import type {
  DiscoveredFunction,
  DiscoveredModel,
  FunctionEmbeddedCodec,
  ModelEmbeddedCodec
} from './discover'
import { type CodecRef, type ZodToSourceContext, zodToSource } from './zodToSource'

const HEADER = `// AUTO-GENERATED by zodvex — do not edit
// Run \`zodvex generate\` to regenerate
`

// ---------------------------------------------------------------------------
// Convex validator → source code walker
//
// Walks a Convex validator graph (output of zodToConvex) and emits an
// equivalent `v.*` source expression. Used by generateTablesFile so the
// schema-eval isolate can import `_zodvex/tables.ts` without loading zod,
// zodvex, or any model file.
// ---------------------------------------------------------------------------

interface ConvexValidator {
  kind: string
  isOptional?: 'required' | 'optional'
  tableName?: string
  value?: unknown
  fields?: Record<string, ConvexValidator>
  element?: ConvexValidator
  members?: ConvexValidator[]
  keys?: ConvexValidator
  values?: ConvexValidator
}

function validatorToSource(val: ConvexValidator): string {
  const opt = val.isOptional === 'optional'
  const wrap = (s: string) => (opt ? `v.optional(${s})` : s)

  switch (val.kind) {
    case 'string':
      return wrap('v.string()')
    case 'float64':
      return wrap('v.float64()')
    case 'int64':
      return wrap('v.int64()')
    case 'boolean':
      return wrap('v.boolean()')
    case 'null':
      return wrap('v.null()')
    case 'any':
      return wrap('v.any()')
    case 'bytes':
      return wrap('v.bytes()')
    case 'id':
      return wrap(`v.id(${JSON.stringify(val.tableName)})`)
    case 'literal':
      return wrap(`v.literal(${JSON.stringify(val.value)})`)
    case 'array':
      return wrap(`v.array(${validatorToSource(val.element as ConvexValidator)})`)
    case 'object': {
      const entries = Object.entries(val.fields ?? {})
        .map(([k, v]) => `${JSON.stringify(k)}: ${validatorToSource(v)}`)
        .join(', ')
      return wrap(`v.object({ ${entries} })`)
    }
    case 'union': {
      const members = (val.members ?? []).map(validatorToSource).join(', ')
      return wrap(`v.union(${members})`)
    }
    case 'record': {
      const keys = validatorToSource(val.keys as ConvexValidator)
      const values = validatorToSource(val.values as ConvexValidator)
      return wrap(`v.record(${keys}, ${values})`)
    }
    default:
      throw new Error(`generateTablesFile: unsupported validator kind '${val.kind}'`)
  }
}

interface ConvexTable {
  validator: ConvexValidator
  indexes: Array<{ indexDescriptor: string; fields: string[] }>
  stagedDbIndexes: Array<{ indexDescriptor: string; fields: string[] }>
  searchIndexes: Array<{ indexDescriptor: string; searchField: string; filterFields: string[] }>
  stagedSearchIndexes: Array<{
    indexDescriptor: string
    searchField: string
    filterFields: string[]
  }>
  vectorIndexes: Array<{
    indexDescriptor: string
    vectorField: string
    dimensions: number
    filterFields: string[]
  }>
  stagedVectorIndexes: Array<{
    indexDescriptor: string
    vectorField: string
    dimensions: number
    filterFields: string[]
  }>
}

function tableToSource(t: ConvexTable): string {
  const lines = [`defineTable(${validatorToSource(t.validator)})`]
  for (const ix of t.indexes) {
    lines.push(`    .index(${JSON.stringify(ix.indexDescriptor)}, ${JSON.stringify(ix.fields)})`)
  }
  for (const ix of t.searchIndexes) {
    lines.push(
      `    .searchIndex(${JSON.stringify(ix.indexDescriptor)}, ${JSON.stringify({
        searchField: ix.searchField,
        filterFields: ix.filterFields
      })})`
    )
  }
  for (const ix of t.vectorIndexes) {
    lines.push(
      `    .vectorIndex(${JSON.stringify(ix.indexDescriptor)}, ${JSON.stringify({
        vectorField: ix.vectorField,
        dimensions: ix.dimensions,
        filterFields: ix.filterFields
      })})`
    )
  }
  return lines.join('\n')
}

export type GeneratedFile = { js: string; dts: string }

/**
 * Produces a structural fingerprint for a ZodCodec by serializing its
 * wire (in) and runtime (out) schemas. Two factory-created codec instances
 * with the same arguments produce the same fingerprint, enabling dedup
 * even when object identity differs.
 *
 * The wire/runtime schemas are serialized via zodToSource, then suffixed
 * with a stable representation of any checks (`.max(n)`, `.min(n)`, etc.)
 * so that `sensitive(z.string())` and `sensitive(z.string().max(100))`
 * land on distinct fingerprints. Without this, codecs that differ only by
 * a constraint collide and the ambiguity-resolution path can't tell them
 * apart by structure alone.
 *
 * The transform bodies (decode/encode) are folded in too: two codecs with the
 * same wire+runtime shape but different transform logic must NOT share a
 * fingerprint, or the ambiguity path could reference a behaviorally-wrong
 * codec. `.toString()` discriminates transform source (a residual gap remains
 * for identical source with different captured closure config — documented).
 */
function fingerprintCodec(schema: $ZodType): string {
  if (!(schema instanceof $ZodCodec)) return ''
  const def = schema._zod.def as {
    in: $ZodType
    out: $ZodType
    transform?: unknown
    reverseTransform?: unknown
  }
  const transform = typeof def.transform === 'function' ? def.transform.toString() : ''
  const reverse = typeof def.reverseTransform === 'function' ? def.reverseTransform.toString() : ''
  return `${fingerprintLeaf(def.in)}|${fingerprintLeaf(def.out)}|${transform}|${reverse}`
}

function fingerprintLeaf(schema: $ZodType): string {
  return `${zodToSource(schema)}#${fingerprintChecks(schema)}`
}

function fingerprintChecks(schema: $ZodType): string {
  const checks = (schema as any)?._zod?.def?.checks
  if (!Array.isArray(checks) || checks.length === 0) return ''
  const parts: string[] = []
  for (const check of checks) {
    const def = (check as any)?._zod?.def
    if (!def) continue
    const checkType = def.check ?? def.type ?? 'check'
    // Stringify only the data that distinguishes one check from another —
    // numeric bounds, regex sources, format names. Skip non-serializable
    // fields (functions, error contributors) so the fingerprint stays stable.
    const data: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(def)) {
      if (k === 'check' || k === 'type' || k === 'error' || k === 'message') continue
      const t = typeof v
      if (t === 'string' || t === 'number' || t === 'boolean' || v === null) {
        data[k] = v
      } else if (v instanceof RegExp) {
        data[k] = v.source
      }
    }
    parts.push(`${checkType}(${JSON.stringify(data)})`)
  }
  return parts.sort().join('&')
}

/**
 * Generates the schema file content — re-exports of all discovered models.
 * Returns { js, dts } with .js import extensions (TS resolves types from .js targets).
 */
export function generateSchemaFile(models: DiscoveredModel[]): GeneratedFile {
  const exports = models
    .map(m => {
      const importPath = `../${m.sourceFile.replace(/\.ts$/, '.js')}`
      return `export { ${m.exportName} } from '${importPath}'`
    })
    .join('\n')

  const content = `${HEADER}\n${exports}\n`
  return { js: content, dts: content }
}

type SchemaRef = {
  importPath: string
  exportName: string
  /**
   * Property path relative to the model export, e.g. "schema.doc" for full
   * models or "schema" for union-slim. Emitted as `${exportName}.${schemaKey}`
   * unless `expression` is set.
   */
  schemaKey: string
  /**
   * Complete access expression to emit, e.g. "zx.doc(TaskModel)". Used for
   * slim models where there's no plain property path. When present, emitted
   * verbatim (the `zx` import is auto-added).
   */
  expression?: string
}

/** Emission helper: returns the full access expression for a SchemaRef. */
function refExpression(ref: SchemaRef): string {
  return ref.expression ?? `${ref.exportName}.${ref.schemaKey}`
}

export type CodecForGeneration = {
  exportName: string
  sourceFile: string
  schema: $ZodType
}

/**
 * Peels .optional() and .nullable() wrappers from a schema and checks
 * the identity map at each level. Returns the matched ref plus a
 * function that wraps an inner source string with the appropriate
 * optional/nullable syntax (chaining or functional for mini mode).
 */
function tryUnwrapToIdentity(
  schema: $ZodType,
  identityMap: Map<$ZodType, SchemaRef>,
  mini?: boolean
): { ref: SchemaRef; wrapSource: (inner: string) => string } | null {
  let current = schema
  const wrappers: Array<'optional' | 'nullable'> = []
  const maxDepth = 5

  for (let i = 0; i < maxDepth; i++) {
    if (current instanceof $ZodOptional) {
      wrappers.push('optional')
      current = current._zod.def.innerType
    } else if (current instanceof $ZodNullable) {
      wrappers.push('nullable')
      current = current._zod.def.innerType
    } else {
      break
    }

    const ref = identityMap.get(current)
    if (ref) {
      // Wrappers collected outermost-first, apply innermost-first
      const reversed = [...wrappers].reverse()
      return {
        ref,
        wrapSource: (inner: string) => {
          let result = inner
          for (const w of reversed) {
            result = mini ? `z.${w}(${result})` : `${result}.${w}()`
          }
          return result
        }
      }
    }
  }

  return null
}

/**
 * Checks if a ZodObject schema is structurally equivalent to
 * someModelSchema.partial() by comparing field-by-field identity.
 *
 * Zod's .partial() wraps each field in ZodOptional, preserving
 * the inner type identity. So we check: same keys, each field
 * is ZodOptional, and each inner type === the original model field.
 */
function tryMatchPartial(
  schema: $ZodType,
  identityMap: Map<$ZodType, SchemaRef>,
  mini?: boolean
): { ref: SchemaRef; wrapSource: (inner: string) => string } | null {
  if (!(schema instanceof $ZodObject)) return null
  const candidateShape = schema._zod.def.shape as Record<string, $ZodType>
  const candidateKeys = Object.keys(candidateShape).sort()

  for (const [modelSchema, ref] of identityMap) {
    if (!(modelSchema instanceof $ZodObject)) continue
    const modelShape = modelSchema._zod.def.shape as Record<string, $ZodType>
    const modelKeys = Object.keys(modelShape).sort()

    // Same key count and same keys
    if (candidateKeys.length !== modelKeys.length) continue
    if (candidateKeys.some((k, i) => k !== modelKeys[i])) continue

    // Every candidate field must be ZodOptional wrapping the model field by identity
    let allMatch = true
    for (const key of candidateKeys) {
      const candidateField = candidateShape[key]
      if (!(candidateField instanceof $ZodOptional)) {
        allMatch = false
        break
      }
      const inner = candidateField._zod.def.innerType
      if (inner !== modelShape[key]) {
        allMatch = false
        break
      }
    }

    if (allMatch) {
      return {
        ref,
        wrapSource: (inner: string) => (mini ? `z.partial(${inner})` : `${inner}.partial()`)
      }
    }
  }

  return null
}

/**
 * Derives a descriptive variable name for a model-embedded codec from
 * the model export name and the access path.
 *
 * Examples:
 *   ('UserModel', '.shape.email')                                      → '_userEmail'
 *   ('ActivityModel', '.shape.payload._zod.def.options[0].shape.email') → '_activityPayloadEmail'
 *   ('patients', '.shape.firstName')                                    → '_patientsFirstName'
 */
function deriveCodecVarName(modelExportName: string, accessPath: string): string {
  const base = modelExportName.replace(/Model$/, '')
  const prefix = base[0].toLowerCase() + base.slice(1)

  const fields = [...accessPath.matchAll(/\.shape\.(\w+)/g)].map(m => m[1])
  if (fields.length === 0) return `_${prefix}Codec`

  const fieldPart = fields.map((f, i) => (i === 0 ? f : f[0].toUpperCase() + f.slice(1))).join('')

  return `_${prefix}${fieldPart[0].toUpperCase() + fieldPart.slice(1)}`
}

/**
 * Generates the api.ts file content — function-to-schema registry.
 */
export function generateApiFile(
  functions: DiscoveredFunction[],
  models: DiscoveredModel[],
  codecs?: CodecForGeneration[],
  modelCodecs?: ModelEmbeddedCodec[],
  functionCodecs?: FunctionEmbeddedCodec[],
  options?: { mini?: boolean }
): GeneratedFile {
  // Sort every input collection by a stable key BEFORE walking. Discovery
  // order can vary across platforms (different filesystem traversal); we
  // need byte-identical output regardless of how the upstream walk ordered
  // things. See MR 206 in hotpot / zodvex codegen determinism investigation.
  const sortedModels = [...models].sort((a, b) =>
    `${a.sourceFile}|${a.exportName}`.localeCompare(`${b.sourceFile}|${b.exportName}`)
  )
  const sortedFunctions = [...functions].sort((a, b) =>
    a.functionPath.localeCompare(b.functionPath)
  )
  const sortedCodecs = codecs
    ? [...codecs].sort((a, b) =>
        `${a.sourceFile}|${a.exportName}`.localeCompare(`${b.sourceFile}|${b.exportName}`)
      )
    : undefined
  const sortedModelCodecs = modelCodecs
    ? [...modelCodecs].sort((a, b) =>
        `${a.modelSourceFile}|${a.modelExportName}|${a.schemaKey}|${a.accessPath}`.localeCompare(
          `${b.modelSourceFile}|${b.modelExportName}|${b.schemaKey}|${b.accessPath}`
        )
      )
    : undefined
  const sortedFunctionCodecs = functionCodecs
    ? [...functionCodecs].sort((a, b) =>
        `${a.functionSourceFile}|${a.functionExportName}|${a.schemaSource}|${a.accessPath}`.localeCompare(
          `${b.functionSourceFile}|${b.functionExportName}|${b.schemaSource}|${b.accessPath}`
        )
      )
    : undefined

  // Replace the parameter bindings with sorted views so the rest of the
  // function operates against deterministic order without further changes.
  models = sortedModels
  functions = sortedFunctions
  codecs = sortedCodecs
  modelCodecs = sortedModelCodecs
  functionCodecs = sortedFunctionCodecs

  // Build identity map: runtime schema object → model reference string
  const identityMap = new Map<$ZodType, SchemaRef>()
  const neededModelImports = new Set<string>()

  for (const model of models) {
    const importPath = `../${model.sourceFile.replace(/\.ts$/, '.js')}`

    if (model.schemas) {
      // Full model: existing behavior — schema.doc, schema.insert, etc.
      for (const key of ['doc', 'insert', 'update', 'docArray', 'paginatedDoc'] as const) {
        identityMap.set(model.schemas[key] as $ZodType, {
          importPath,
          exportName: model.exportName,
          schemaKey: `schema.${key}`
        })
      }
    } else if (model._modelRef) {
      // Slim model: schemas live in the per-model zx WeakMap cache, not on the
      // model object. Populate identityMap with cached `zx.*` instances so
      // function code like `returns: zx.doc(SlimModel)` resolves by identity.
      // Emit `zx.doc(SlimModel)` (not `SlimModel.doc`) since slim models have
      // no such property.
      const ref = model._modelRef as any
      const slimKeys = [
        { key: 'doc', schema: zx.doc(ref) as $ZodType, expr: `zx.doc(${model.exportName})` },
        { key: 'insert', schema: zx.base(ref) as $ZodType, expr: `zx.base(${model.exportName})` },
        { key: 'base', schema: zx.base(ref) as $ZodType, expr: `zx.base(${model.exportName})` },
        {
          key: 'update',
          schema: zx.update(ref) as $ZodType,
          expr: `zx.update(${model.exportName})`
        },
        {
          key: 'docArray',
          schema: zx.docArray(ref) as $ZodType,
          expr: `zx.docArray(${model.exportName})`
        }
      ]
      for (const { key, schema, expr } of slimKeys) {
        identityMap.set(schema, {
          importPath,
          exportName: model.exportName,
          schemaKey: key,
          expression: expr
        })
      }
      // Union slim retains `.schema` on the model object — map that too so
      // `returns: SlimModel.schema` resolves as a direct property reference.
      if (ref.schema instanceof $ZodType) {
        identityMap.set(ref.schema, {
          importPath,
          exportName: model.exportName,
          schemaKey: 'schema'
        })
      }
    }
  }

  // Build codec identity map for zodToSource
  const codecMap = new Map<$ZodType, CodecRef>()
  if (codecs) {
    for (const codec of codecs) {
      const importPath = `../${codec.sourceFile.replace(/\.ts$/, '.js')}`
      codecMap.set(codec.schema, {
        exportName: codec.exportName,
        sourceFile: importPath
      })
    }
  }

  // Add model-embedded codecs to the codecMap (exported codecs take precedence)
  const modelCodecVars: { varName: string; expression: string; modelExportName: string }[] = []
  const MODEL_CODEC_SENTINEL = '__model_codec__'
  // Build slim model lookup for codec expression generation
  const slimModelNames = new Set(
    models.filter(m => !m.schemas && m._modelRef).map(m => m.exportName)
  )
  if (modelCodecs) {
    for (const mc of modelCodecs) {
      // Skip if this codec is already in codecMap (exported codec takes precedence)
      if (codecMap.has(mc.codec)) continue

      const varName = deriveCodecVarName(mc.modelExportName, mc.accessPath)
      // Slim models: schemas are cached in the zx WeakMap, accessed via
      //   zx.doc(Model) / zx.base(Model) / zx.update(Model).
      // Full models: schema bundle is at Model.schema.{doc,insert,update,...}.
      const isSlim = slimModelNames.has(mc.modelExportName)
      let schemaAccess: string
      if (isSlim) {
        // Map walkModelCodecs keys (doc/insert/update) to their zx equivalents.
        const slimKey = mc.schemaKey === 'insert' ? 'base' : mc.schemaKey
        schemaAccess = `zx.${slimKey}(${mc.modelExportName})`
      } else {
        schemaAccess = `${mc.modelExportName}.schema.${mc.schemaKey}`
      }
      const expression = `extractCodec(${schemaAccess}${mc.accessPath})`
      modelCodecVars.push({ varName, expression, modelExportName: mc.modelExportName })
      codecMap.set(mc.codec, {
        exportName: varName,
        sourceFile: MODEL_CODEC_SENTINEL
      })
    }
  }

  // Resolve function-embedded codecs against existing codecs by structural fingerprint.
  // Factory-created codecs (like tagged(), encrypted()) produce new instances each call,
  // so identity matching fails. Fingerprinting matches by wire+runtime+transform,
  // allowing us to reference the model/standalone codec instead of importing the function.
  // This avoids circular imports: functions.ts → _zodvex/api.ts → functionFile.ts → functions.ts
  //
  // Ambiguity handling: when multiple codecs share a fingerprint they are, by the
  // fingerprint contract, behaviorally interchangeable — so any one is a correct
  // reference. We prefer a same-source-file candidate, otherwise we pick the
  // stable-sorted-first so output is byte-identical across discovery orders
  // (hotpot MR 206). We MUST NOT fall through to inline serialization: a codec
  // inlined via zodToSource loses its transform (emits the wire schema only),
  // which silently breaks the client encode/decode path with no build signal.
  //
  // Zero candidates means the codec exists only inside the function (no model
  // twin, not exported standalone) and has no importable reference. We collect
  // every such case and hard-error after the loop — a loud build-time failure
  // beats silent boundary corruption.
  if (functionCodecs) {
    type Candidate = { ref: CodecRef; sourceFile: string | undefined; brand: string | undefined }
    const fingerprintMap = new Map<string, Candidate[]>()
    // brand → importable candidates that declared it. Brand is the author's
    // explicit identity (see docs/decisions/2026-06-08-codec-provenance-brands.md),
    // matched ahead of the structural fingerprint and namespaced across factories.
    const brandMap = new Map<string, Candidate[]>()

    // Build a lookup from codec schema → source file when we know it. Standalone
    // exported codecs carry a sourceFile in their CodecRef; model-embedded codecs
    // do not (their sourceFile is the MODEL_CODEC_SENTINEL).
    const codecSchemaToSourceFile = new Map<$ZodType, string>()
    for (const c of codecs ?? []) {
      codecSchemaToSourceFile.set(c.schema, c.sourceFile)
    }
    for (const mc of modelCodecs ?? []) {
      codecSchemaToSourceFile.set(mc.codec, mc.modelSourceFile)
    }

    for (const [codecSchema, ref] of codecMap) {
      const sourceFile = codecSchemaToSourceFile.get(codecSchema)
      const brand = readCodecBrand(codecSchema)
      const candidate: Candidate = { ref, sourceFile, brand }
      const fp = fingerprintCodec(codecSchema)
      if (fp) {
        const existing = fingerprintMap.get(fp)
        if (existing) existing.push(candidate)
        else fingerprintMap.set(fp, [candidate])
      }
      if (brand) {
        const existing = brandMap.get(brand)
        if (existing) existing.push(candidate)
        else brandMap.set(brand, [candidate])
      }
    }

    const undiscoverable: { fn: string; path: string }[] = []

    for (const fc of functionCodecs) {
      if (codecMap.has(fc.codec)) continue

      // 1. Brand match — declared identity. Collision-free and namespaced: a
      //    branded codec resolves only against codecs that declared the same brand.
      const brand = readCodecBrand(fc.codec)
      let candidates: Candidate[] | undefined = brand ? brandMap.get(brand) : undefined

      // 2. Fingerprint fallback — structural identity. Exclude any candidate that
      //    declared a *different* brand (a cross-factory match would violate the
      //    brand's intent); unbranded candidates are always eligible.
      if (!candidates || candidates.length === 0) {
        const fp = fingerprintCodec(fc.codec)
        candidates = (fp ? fingerprintMap.get(fp) : undefined)?.filter(
          c => c.brand === undefined || c.brand === brand
        )
      }

      if (!candidates || candidates.length === 0) {
        undiscoverable.push({ fn: fc.functionExportName, path: fc.accessPath })
        continue
      }

      let chosen: CodecRef
      if (candidates.length === 1) {
        chosen = candidates[0].ref
      } else {
        // Prefer a unique same-source-file candidate; otherwise pick the
        // stable-sorted-first. Either way we reference a real codec — never
        // inline a transform-less husk.
        const sameFile = candidates.filter(c => c.sourceFile === fc.functionSourceFile)
        if (sameFile.length === 1) {
          chosen = sameFile[0].ref
        } else {
          const sorted = [...candidates].sort((a, b) =>
            `${a.sourceFile ?? ''}|${a.ref.exportName}`.localeCompare(
              `${b.sourceFile ?? ''}|${b.ref.exportName}`
            )
          )
          chosen = sorted[0].ref
          // Branded cohorts are interchangeable by the author's explicit
          // declaration — only flag ambiguity for inferred (unbranded) matches.
          if (!brand) {
            console.warn(
              `[zodvex] Note: Codec in ${fc.functionExportName}() (${fc.accessPath}) matches ${candidates.length} fingerprint-equivalent codecs ` +
                `(${candidates.map(c => c.ref.exportName).join(', ')}). Referencing '${chosen.exportName}'. ` +
                `Export the codec standalone or give it a brand if you want the reference to be explicit.`
            )
          }
        }
      }

      codecMap.set(fc.codec, chosen)
    }

    if (undiscoverable.length > 0) {
      const list = undiscoverable.map(u => `  - ${u.fn}() at ${u.path}`).join('\n')
      throw new Error(
        `[zodvex] ${undiscoverable.length} codec(s) in function args/returns have no importable reference ` +
          `(not exported standalone, not embedded in a model). The generated client cannot encode or decode ` +
          `them, which silently breaks the codec boundary. Export each codec standalone (or add it to a model) ` +
          `so codegen can import it:\n${list}`
      )
    }
  }

  const zodToSourceCtx: ZodToSourceContext = {
    codecMap,
    neededCodecImports: new Map(),
    undiscoverableCodecs: [],
    mini: options?.mini
  }

  // Track which imports we need
  let needsZod = false
  let needsZx = false

  function emitRef(ref: SchemaRef): string {
    neededModelImports.add(ref.exportName)
    const expr = refExpression(ref)
    // Slim-model refs use zx.* helpers; ensure `zx` is imported in the output.
    if (ref.expression?.startsWith('zx.')) needsZx = true
    return expr
  }

  // Resolve each schema to either a model reference or serialized source
  function resolveSchema(schema: $ZodType | unknown): string {
    if (!schema) return 'undefined'
    const s = schema as $ZodType

    // 1. Direct identity match
    const ref = identityMap.get(s)
    if (ref) return emitRef(ref)

    // 2. Wrapper-aware identity match (peel .nullable()/.optional())
    const unwrapped = tryUnwrapToIdentity(s, identityMap, options?.mini)
    if (unwrapped) return unwrapped.wrapSource(emitRef(unwrapped.ref))

    // 3. Partial-aware match (detect .partial() of a model schema)
    const partialMatch = tryMatchPartial(s, identityMap, options?.mini)
    if (partialMatch) return partialMatch.wrapSource(emitRef(partialMatch.ref))

    // 4. Fall back to zodToSource (with codec context)
    const source = zodToSource(s, zodToSourceCtx)
    if (source.includes('z.')) needsZod = true
    if (source.includes('zx.')) needsZx = true
    return source
  }

  // Build registry entries
  const entries = functions
    .map(fn => {
      const args = resolveSchema(fn.zodArgs)
      const returns = resolveSchema(fn.zodReturns)
      return `  '${fn.functionPath}': {\n    args: ${args},\n    returns: ${returns},\n  }`
    })
    .join(',\n')

  // Determine which model codec vars were actually used (referenced by zodToSource)
  const usedModelCodecVars = modelCodecVars.filter(mc => {
    const sentinelExports = zodToSourceCtx.neededCodecImports.get(MODEL_CODEC_SENTINEL)
    return sentinelExports?.has(mc.varName)
  })

  // Add model imports for models referenced by used model codec vars.
  // Slim codec vars use zx.base(Model)/zx.doc(Model) expressions — require zx import.
  if (usedModelCodecVars.length > 0) {
    for (const mc of usedModelCodecVars) {
      neededModelImports.add(mc.modelExportName)
      if (mc.expression.includes('zx.')) needsZx = true
    }
  }

  // Build imports
  const imports: string[] = []
  const zodImport = options?.mini ? 'zod/mini' : 'zod'
  if (needsZod) imports.push(`import { z } from '${zodImport}'`)

  // Build single client-safe zodvex import (root full path or zodvex/mini)
  const zodvexImport = options?.mini ? 'zodvex/mini' : 'zodvex'
  const coreImports: string[] = []
  if (needsZx) coreImports.push('zx')
  if (usedModelCodecVars.length > 0) coreImports.push('extractCodec')
  if (coreImports.length > 0) {
    imports.push(`import { ${coreImports.join(', ')} } from '${zodvexImport}'`)
  }

  for (const exportName of [...neededModelImports].sort()) {
    const model = models.find(m => m.exportName === exportName)
    if (model) {
      const importPath = `../${model.sourceFile.replace(/\.ts$/, '.js')}`
      imports.push(`import { ${exportName} } from '${importPath}'`)
    }
  }

  // Codec imports (collected by zodToSource via context). Sort the map's
  // outer keys (import paths) and the inner Set values (export names) so
  // the final import section is byte-stable across discovery orders.
  const sortedCodecImportPaths = [...zodToSourceCtx.neededCodecImports.keys()].sort()
  for (const importPath of sortedCodecImportPaths) {
    if (importPath === MODEL_CODEC_SENTINEL) continue
    const exportNames = zodToSourceCtx.neededCodecImports.get(importPath) ?? new Set<string>()
    const names = Array.from(exportNames).sort().join(', ')
    imports.push(`import { ${names} } from '${importPath}'`)
  }

  const importSection = imports.length > 0 ? `${imports.join('\n')}\n\n` : ''

  // Build codec helper var declarations
  const allCodecVars = usedModelCodecVars.map(mc => `const ${mc.varName} = ${mc.expression}`)
  const codecVarSection = allCodecVars.length > 0 ? `${allCodecVars.join('\n')}\n\n` : ''

  const registryEntries = entries.length > 0 ? `${entries},\n` : ''
  const js = `${HEADER}\n${importSection}${codecVarSection}export const zodvexRegistry = {\n${registryEntries}}\n`

  const dts = options?.mini
    ? `${HEADER}
import type { $ZodType } from 'zod/v4/core'

export declare const zodvexRegistry: Record<string, { args: $ZodType; returns: $ZodType | undefined }>
`
    : `${HEADER}
import type { ZodTypeAny } from 'zod'

export declare const zodvexRegistry: Record<string, { args: ZodTypeAny; returns: ZodTypeAny | undefined }>
`

  return { js, dts }
}

/**
 * Generates _zodvex/server.ts — the single entry point for consumer code.
 *
 * Consolidates everything the consumer's `convex/functions.ts` would
 * otherwise wire by hand:
 *
 *  1. Concrete context types (QueryCtx, MutationCtx, ActionCtx) baked
 *     against the app's schema's `__decodedDocs`.
 *  2. A statically-imported registry and a statically-built table map
 *     (supersedes the `_zodvex/api.lazy.js` / `_zodvex/tableMap.lazy.js`
 *     pair — both consumers now run in the Q/M V8 sandbox where dynamic
 *     `import()` is forbidden).
 *  3. A pre-wired `initZodvex(server, options?)` that calls the
 *     library's initZodvex with `schema`, registry, and tableMap
 *     defaulted from the statics above. Consumers can still pass
 *     `registry` / `tableMap` in `options` to override.
 *
 * Result: userland `convex/functions.ts` becomes one import + one call:
 *
 *     import { initZodvex } from './_zodvex/server'
 *     import { query, mutation, ... } from './_generated/server'
 *     export const { zq, zm, za, ziq, zim, zia } = initZodvex({
 *       query, mutation, action, internalQuery, internalMutation, internalAction,
 *     })
 *
 * No async/await syntax, no lazy-* imports, no need to know the
 * registry exists.
 */
export function generateServerFile(
  models: DiscoveredModel[],
  options?: { mini?: boolean }
): GeneratedFile {
  const serverImport = options?.mini ? 'zodvex/mini/server' : 'zodvex/server'
  const zxImport = options?.mini ? 'zodvex/mini' : 'zodvex'

  // Static model imports + sync tableMap construction. Convex's Q/M V8
  // sandbox forbids dynamic `import()`, so the runtime tableMap (used by
  // every codec-wrapped query/mutation) must be statically reachable from
  // this file. The cost: any entrypoint that imports this module pulls
  // every model file into its analyzer isolate at deploy time. We accept
  // that — runtime correctness beats analyzer-memory headroom.
  const modelImports: string[] = []
  const tableMapEntries: string[] = []
  for (const m of models) {
    if (!m._liveModel) continue
    const live = m._liveModel as { name: string; fields?: unknown; indexes?: unknown }
    if (live.fields === undefined || live.indexes === undefined) continue
    const importPath = `../${m.sourceFile.replace(/\.ts$/, '.js')}`
    modelImports.push(`import { ${m.exportName} } from '${importPath}'`)
    tableMapEntries.push(
      `  ${JSON.stringify(live.name)}: { doc: zx.doc(${m.exportName}), insert: zx.base(${m.exportName}) }`
    )
  }
  const modelImportSection = modelImports.length > 0 ? modelImports.join('\n') + '\n' : ''
  const tableMapBody = tableMapEntries.length > 0 ? tableMapEntries.join(',\n') + '\n' : ''

  const ts = `${HEADER}
import { zx } from '${zxImport}'
import { initZodvex as _libInitZodvex } from '${serverImport}'
import type {
  ZodvexActionCtx,
  ZodvexBuilder,
  ZodvexMutationCtx,
  ZodvexQueryCtx,
} from '${serverImport}'
import type {
  ActionBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  MutationBuilder,
  QueryBuilder,
} from 'convex/server'
import type { DataModel } from '../_generated/dataModel.js'
import _baseSchema from '../schema.js'
import { zodvexRegistry as _staticRegistry } from './api.js'
${modelImportSection}

// --- Context types ---

// Decoded doc types are imported directly from the codegen-emitted
// tables.ts so userland \`schema.ts\` can use Convex's canonical
// \`defineSchema(tables)\` without carrying a zodvex-specific token.
import type { DecodedDocs as _DecodedDocs } from './tables'
type DecodedDocs = _DecodedDocs

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>

// --- Registry (static, Q/M-safe) ---
// The registry feeds cross-function codec auto-encoding in BOTH actions
// (runQuery/runMutation arg encode + result decode, scheduler arg encode)
// and mutations (scheduler.runAfter/runAt arg encode). Mutations run in
// Convex's Q/M V8 sandbox, which forbids dynamic \`import()\` — so the
// registry must be statically imported, the same constraint as the
// tableMap below. (An earlier draft dynamic-imported ./api.js lazily;
// that only worked while actions — Node runtime — were the registry's
// sole consumer.)

const _registry = () => _staticRegistry

// --- Static table map (Q/M-safe) ---
// Built sync from statically-imported models. Convex's Q/M V8 sandbox
// forbids dynamic \`import()\` with "dynamic module import unsupported",
// so the runtime tableMap can't be loaded lazily. Userland \`functions.ts\`
// imports this module → pulls every model into its analyzer isolate at
// deploy time.

const _tableMap = {
${tableMapBody}}

// --- Pre-wired initZodvex ---
// Calls the library's initZodvex with schema + registry + tableMap
// already wired. Consumers pass only the Convex server builders.
// Override registry/tableMap/wrapDb via options if needed.

type Server = {
  query: QueryBuilder<DataModel, 'public'>
  mutation: MutationBuilder<DataModel, 'public'>
  action: ActionBuilder<DataModel, 'public'>
  internalQuery: QueryBuilder<DataModel, 'internal'>
  internalMutation: MutationBuilder<DataModel, 'internal'>
  internalAction: ActionBuilder<DataModel, 'internal'>
}

type Bundle = {
  zq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'public'>
  zm: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'public'>
  za: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'public'>
  ziq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'internal'>
  zim: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'internal'>
  zia: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'internal'>
}

export function initZodvex(server: Server, options: {
  wrapDb?: boolean
  registry?: () => any
  tableMap?: any
} = {}): Bundle {
  return (_libInitZodvex as any)(_baseSchema, server, {
    ...options,
    registry: options.registry ?? _registry,
    tableMap: options.tableMap ?? _tableMap,
  }) as Bundle
}

// --- Codec-aware schema re-export ---
// Userland code that wants \`createZodDbReader\`/\`createZodDbWriter\` outside
// a zq/zm handler imports \`schema\` from here (not from \`../schema\`). This
// object is the base schema with the sync tableMap attached as
// \`__zodTableMap\` plus a type-only \`__decodedDocs\` token.

type ZodvexSchema = typeof _baseSchema & {
  __zodTableMap: typeof _tableMap
  __decodedDocs: DecodedDocs
}

export const schema: ZodvexSchema = Object.assign(_baseSchema, {
  __zodTableMap: _tableMap,
  __decodedDocs: undefined as unknown as DecodedDocs,
})
`

  return { js: ts, dts: '' }
}

/**
 * Generates the tables file — a pure Convex `_zodvex/tables.ts` default-export
 * object mapping table-name → `defineTable(...).index(...)`.
 *
 * The whole point of this file is to be importable from `convex/schema.ts`
 * WITHOUT pulling zod or zodvex into the schema-eval isolate. Convex's
 * per-entrypoint analyzer loads schema.ts independently in a 64 MB budget,
 * and the only way to keep large model graphs under that is to strip the
 * zod runtime from schema-eval entirely.
 *
 * User schema.ts becomes:
 *
 *     import { defineSchema } from 'convex/server'
 *     import tables from './_zodvex/tables'
 *     export default defineSchema(tables)
 *
 * Implementation: walks each model's live `TableDefinition` (built via
 * `tableFromModel`) and round-trips the validator + indexes back to
 * source. Each model's `name` property is the key in the default export.
 */
export function generateTablesFile(models: DiscoveredModel[]): GeneratedFile {
  const entries: string[] = []
  const typeImports: string[] = []
  const decodedDocsEntries: string[] = []

  for (const m of models) {
    if (!m._liveModel) continue
    const live = m._liveModel as { name: string; fields?: unknown; indexes?: unknown }
    // tableFromModel only knows about defineZodModel results — hand-rolled
    // models that use attachMeta directly may not have the expected shape.
    // Skip rather than throw so a project mixing styles still generates
    // the entries it can.
    if (live.fields === undefined || live.indexes === undefined) {
      console.warn(
        `[zodvex] Skipping tables.ts entry for '${m.exportName}' in ${m.sourceFile}: ` +
          'model is not a defineZodModel() result. Use defineZodModel() to enable the lazy-tables shape.'
      )
      continue
    }
    let table: ConvexTable
    try {
      table = tableFromModel(live as any) as unknown as ConvexTable
    } catch (err) {
      console.warn(
        `[zodvex] Skipping tables.ts entry for '${m.exportName}' in ${m.sourceFile}: ` +
          `${(err as Error).message}`
      )
      continue
    }
    const tableSrc = tableToSource(table)
    entries.push(`  ${JSON.stringify(live.name)}: ${tableSrc},`)

    // Type-only import + DecodedDocs entry for this table. Type imports
    // are erased at compile so this adds ZERO runtime cost to the
    // schema-eval isolate; we still get decoded doc types end-to-end.
    const importPath = `../${m.sourceFile.replace(/\.ts$/, '.js')}`
    typeImports.push(`import type { ${m.exportName} } from '${importPath}'`)
    decodedDocsEntries.push(`  ${JSON.stringify(live.name)}: typeof ${m.exportName}`)
  }

  // Single TypeScript source — Convex accepts .ts modules and tsc infers
  // per-table TableDefinition<VObject<...>> from the literal expression.
  // A separate .d.ts that says `Record<string, TableDefinition>` would
  // erase the per-table types and weaken the DataModel.
  const ts = `${HEADER}
import { defineTable } from 'convex/server'
import { v } from 'convex/values'
${typeImports.length > 0 ? `\n${typeImports.join('\n')}` : ''}
import type { DecodedDocFor } from 'zodvex/server'

export default {
${entries.join('\n')}
}

/**
 * Decoded document types per table — derived from each model's zod doc
 * schema. Used by \`defineZodvexSchema\` to attach \`__decodedDocs\` so
 * ctx.db return types in queries/mutations reflect codec-decoded shapes
 * (e.g. \`Date\` instead of \`number\` for \`zx.date()\` fields).
 *
 * Type-only — does NOT load zod at module init. Schema-eval stays thin.
 */
export type DecodedDocs = DecodedDocFor<{
${decodedDocsEntries.join('\n')}
}>
`

  // Returned in the .js slot for the existing emit pipeline; commands.ts
  // writes it to tables.ts (see writeIfChanged path below).
  return { js: ts, dts: '' }
}

export function generateClientFile(options?: { mini?: boolean }): GeneratedFile {
  const zodvexClientImport = options?.mini ? 'zodvex/mini' : 'zodvex'
  // --- JS ---
  const jsImports = [
    "import { createZodvexHooks } from 'zodvex/react'",
    "import { createZodvexReactClient } from 'zodvex/react'",
    "import { createZodvexClient } from 'zodvex/client'",
    `import { createBoundaryHelpers } from '${zodvexClientImport}'`,
    "import { zodvexRegistry } from './api.js'"
  ]

  const jsExports = [
    'export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)',
    '',
    'export const createClient = (options) =>',
    '  createZodvexClient(zodvexRegistry, options)',
    '',
    'export const createReactClient = (options) =>',
    '  createZodvexReactClient(zodvexRegistry, options)',
    '',
    'export const { encodeArgs, decodeResult } = createBoundaryHelpers(zodvexRegistry)'
  ]

  const js = `${HEADER}\n${jsImports.join('\n')}\n\n${jsExports.join('\n')}\n`

  // --- DTS ---
  const dtsImports = [
    "import type { ZodvexHooks } from 'zodvex/react'",
    "import type { ZodvexClientOptions, ZodvexClient } from 'zodvex/client'",
    "import type { ZodvexReactClientOptions, ZodvexReactClient } from 'zodvex/react'",
    `import type { BoundaryHelpers } from '${zodvexClientImport}'`
  ]

  const dtsDeclarations = [
    "export declare const useZodQuery: ZodvexHooks['useZodQuery']",
    "export declare const useZodMutation: ZodvexHooks['useZodMutation']",
    '',
    'export declare const createClient: (options: ZodvexClientOptions) => ZodvexClient',
    '',
    'export declare const createReactClient: (options: ZodvexReactClientOptions) => ZodvexReactClient',
    '',
    "export declare const encodeArgs: BoundaryHelpers['encodeArgs']",
    "export declare const decodeResult: BoundaryHelpers['decodeResult']"
  ]

  const dts = `${HEADER}\n${dtsImports.join('\n')}\n\n${dtsDeclarations.join('\n')}\n`

  return { js, dts }
}
