import type {
  DiscoveredFunction,
  DiscoveredModel,
  FunctionEmbeddedCodec,
  ModelEmbeddedCodec
} from './discover'
import { type CodecForGeneration, resolveSchemaReferences } from './schemaReferences'

export type { CodecForGeneration } from './schemaReferences'

const HEADER = `// AUTO-GENERATED by zodvex — do not edit
// Run \`zodvex generate\` to regenerate
`

/**
 * Memoizing helper emitted above the registry. Registry entries are getters
 * that call this so each entry's schemas are constructed on first access and
 * reused afterwards (stable identity per module instance).
 */
const LAZY_HELPER = `const __memo = new Map()
const __lazy = (key, build) => {
  let entry = __memo.get(key)
  if (entry === undefined) {
    entry = build()
    __memo.set(key, entry)
  }
  return entry
}
`

export type GeneratedFile = { js: string; dts: string }

/**
 * Generates the schema file content — re-exports of all discovered models.
 * Returns { js, dts } with .js import extensions (TS resolves types from .js targets).
 */
export function generateSchemaFile(models: DiscoveredModel[]): GeneratedFile {
  const exports = models
    .map(m => {
      const importPath = `../${m.sourceFile.replace(/\.ts$/, '.js')}`
      return `export { ${m.exportName} } from '${importPath}'`
    })
    .join('\n')

  const content = `${HEADER}\n${exports}\n`
  return { js: content, dts: content }
}

/**
 * Generates the api.ts file content — function-to-schema registry.
 */
export function generateApiFile(
  functions: DiscoveredFunction[],
  models: DiscoveredModel[],
  codecs?: CodecForGeneration[],
  modelCodecs?: ModelEmbeddedCodec[],
  functionCodecs?: FunctionEmbeddedCodec[],
  options?: { mini?: boolean }
): GeneratedFile {
  const {
    entries: resolvedEntries,
    imports,
    codecDeclarations
  } = resolveSchemaReferences({ functions, models, codecs, modelCodecs, functionCodecs }, options)
  const entries = resolvedEntries
    .map(({ functionPath, args, returns }) => {
      const key = `'${functionPath}'`
      return `  get ${key}() {\n    return __lazy(${key}, () => ({\n      args: ${args},\n      returns: ${returns},\n    }))\n  }`
    })
    .join(',\n')

  const importSection = imports.length > 0 ? `${imports.join('\n')}\n\n` : ''

  // Build codec helper var declarations
  const codecVarSection = codecDeclarations.length > 0 ? `${codecDeclarations.join('\n')}\n\n` : ''

  const registryEntries = entries.length > 0 ? `${entries},\n` : ''
  const lazySection = entries.length > 0 ? `${LAZY_HELPER}\n` : ''
  const js = `${HEADER}\n${importSection}${codecVarSection}${lazySection}export const zodvexRegistry = {\n${registryEntries}}\n`

  const dts = options?.mini
    ? `${HEADER}
import type { $ZodType } from 'zod/v4/core'

export declare const zodvexRegistry: Record<string, { args: $ZodType; returns: $ZodType | undefined }>
`
    : `${HEADER}
import type { ZodTypeAny } from 'zod'

export declare const zodvexRegistry: Record<string, { args: ZodTypeAny; returns: ZodTypeAny | undefined }>
`

  return { js, dts }
}

/**
 * Generates the server.ts file content — concrete context types for the app's schema.
 *
 * These parallel Convex's _generated/server.ts exports (QueryCtx, MutationCtx, ActionCtx)
 * but with zodvex's codec-wrapped db types baked in.
 */
export function generateServerFile(): GeneratedFile {
  const js = `${HEADER}`

  const dts = `${HEADER}
import type { DataModel } from '../_generated/dataModel.js'
import type { ZodvexActionCtx, ZodvexMutationCtx, ZodvexQueryCtx } from 'zodvex/server'
import type schema from '../schema.js'

type DecodedDocs = (typeof schema)['__decodedDocs']

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>
`

  return { js, dts }
}

/**
 * Generates the client file content — pre-bound hooks and client factory.
 * Returns { js, dts } for .js + .d.ts output.
 */
export function generateClientFile(options?: { mini?: boolean }): GeneratedFile {
  const zodvexClientImport = options?.mini ? 'zodvex/mini' : 'zodvex'
  // --- JS ---
  const jsImports = [
    "import { createZodvexHooks } from 'zodvex/react'",
    "import { createZodvexReactClient } from 'zodvex/react'",
    "import { createZodvexClient } from 'zodvex/client'",
    `import { createBoundaryHelpers } from '${zodvexClientImport}'`,
    "import { zodvexRegistry } from './api.js'"
  ]

  const jsExports = [
    'export const { useZodQuery, useZodMutation, useZodPaginatedQuery, useQuery_experimental } = createZodvexHooks(zodvexRegistry)',
    '',
    'export const createClient = (options) =>',
    '  createZodvexClient(zodvexRegistry, options)',
    '',
    'export const createReactClient = (options) =>',
    '  createZodvexReactClient(zodvexRegistry, options)',
    '',
    'export const { encodeArgs, decodeResult } = createBoundaryHelpers(zodvexRegistry)'
  ]

  const js = `${HEADER}\n${jsImports.join('\n')}\n\n${jsExports.join('\n')}\n`

  // --- DTS ---
  const dtsImports = [
    "import type { ZodvexHooks } from 'zodvex/react'",
    "import type { ZodvexClientOptions, ZodvexClient } from 'zodvex/client'",
    "import type { ZodvexReactClientOptions, ZodvexReactClient } from 'zodvex/react'",
    `import type { BoundaryHelpers } from '${zodvexClientImport}'`
  ]

  const dtsDeclarations = [
    "export declare const useZodQuery: ZodvexHooks['useZodQuery']",
    "export declare const useZodPaginatedQuery: ZodvexHooks['useZodPaginatedQuery']",
    "export declare const useQuery_experimental: ZodvexHooks['useQuery_experimental']",
    "export declare const useZodMutation: ZodvexHooks['useZodMutation']",
    '',
    'export declare const createClient: (options: ZodvexClientOptions) => ZodvexClient',
    '',
    'export declare const createReactClient: (options: ZodvexReactClientOptions) => ZodvexReactClient',
    '',
    "export declare const encodeArgs: BoundaryHelpers['encodeArgs']",
    "export declare const decodeResult: BoundaryHelpers['decodeResult']"
  ]

  const dts = `${HEADER}\n${dtsImports.join('\n')}\n\n${dtsDeclarations.join('\n')}\n`

  return { js, dts }
}
