import { afterEach, describe, expect, it } from 'bun:test'
import fs from 'node:fs'
import path from 'node:path'
import { discoverModules } from '../src/codegen/discover'
import { generateSchemaFile, generateApiFile, generateClientFile } from '../src/codegen/generate'

const fixtureDir = path.resolve(__dirname, 'fixtures/codegen-project')
const outputDir = path.join(fixtureDir, '_zodvex')

afterEach(() => {
  if (fs.existsSync(outputDir)) {
    fs.rmSync(outputDir, { recursive: true })
  }
})

describe('codegen e2e', () => {
  it('full pipeline: discover → generate → write → verify', async () => {
    // 1. Discover
    const result = await discoverModules(fixtureDir)
    expect(result.models.length).toBe(1)
    expect(result.functions.length).toBeGreaterThanOrEqual(2)

    // 2. Generate
    const schemaContent = generateSchemaFile(result.models)
    const apiContent = generateApiFile(result.functions, result.models, result.codecs)
    const clientContent = generateClientFile()

    // 3. Write to _zodvex/
    fs.mkdirSync(outputDir, { recursive: true })
    fs.writeFileSync(path.join(outputDir, 'schema.ts'), schemaContent)
    fs.writeFileSync(path.join(outputDir, 'api.ts'), apiContent)
    fs.writeFileSync(path.join(outputDir, 'client.ts'), clientContent)

    // 4. Verify files exist
    expect(fs.existsSync(path.join(outputDir, 'schema.ts'))).toBe(true)
    expect(fs.existsSync(path.join(outputDir, 'api.ts'))).toBe(true)
    expect(fs.existsSync(path.join(outputDir, 'client.ts'))).toBe(true)

    // 5. Verify schema.ts content
    expect(schemaContent).toContain('// AUTO-GENERATED by zodvex')
    expect(schemaContent).toContain("export { UserModel } from '../models/user'")

    // 6. Verify api.ts content
    expect(apiContent).toContain('// AUTO-GENERATED by zodvex')
    expect(apiContent).toContain('export const zodvexRegistry')
    expect(apiContent).toContain("'users:get'")
    expect(apiContent).toContain("'users:list'")

    // 7. Verify ad-hoc schemas are serialized with zodToSource
    expect(apiContent).toContain('z.object(')
    expect(apiContent).toContain('z.string()')

    // 8. Verify client.ts content
    expect(clientContent).toContain('// AUTO-GENERATED by zodvex')
    expect(clientContent).toContain("import { createZodvexHooks } from 'zodvex/react'")
    expect(clientContent).toContain(
      "import { createZodvexClient, type ZodvexClientOptions } from 'zodvex/client'"
    )
    expect(clientContent).toContain("import { zodvexRegistry } from './api'")
    expect(clientContent).toContain('useZodQuery')
    expect(clientContent).toContain('useZodMutation')
    expect(clientContent).toContain('createClient')

    // 9. Verify codec discovery
    expect(result.codecs.length).toBeGreaterThanOrEqual(1)
    expect(result.codecs.some(c => c.exportName === 'zDuration')).toBe(true)

    // 10. Verify codec handling in api.ts — no unsupported pipe fallback
    expect(apiContent).not.toContain('unsupported: pipe')
  })

  it('schema.ts has correct import paths relative to _zodvex/', async () => {
    const result = await discoverModules(fixtureDir)
    const schemaContent = generateSchemaFile(result.models)

    // Import path should go up from _zodvex/ to the source file
    expect(schemaContent).toContain("from '../models/user'")
  })

  it('api.ts imports zod when ad-hoc schemas are present', async () => {
    const result = await discoverModules(fixtureDir)
    const apiContent = generateApiFile(result.functions, result.models, result.codecs)

    expect(apiContent).toContain("import { z } from 'zod'")
  })

  it('client.ts imports from zodvex/react, zodvex/client, and ./api', () => {
    const clientContent = generateClientFile()
    expect(clientContent).toContain("from 'zodvex/react'")
    expect(clientContent).toContain("from 'zodvex/client'")
    expect(clientContent).toContain("from './api'")
  })

  it('skips _generated/ and _zodvex/ during discovery', async () => {
    // Create a dummy file in _zodvex/ to ensure it's skipped
    fs.mkdirSync(outputDir, { recursive: true })
    fs.writeFileSync(path.join(outputDir, 'schema.ts'), '// dummy')

    const result = await discoverModules(fixtureDir)

    const allPaths = [
      ...result.models.map(m => m.sourceFile),
      ...result.functions.map(f => f.sourceFile)
    ]
    for (const p of allPaths) {
      expect(p).not.toContain('_zodvex')
      expect(p).not.toContain('_generated')
    }
  })
})
