import { describe, expect, it } from 'bun:test'
import { z } from 'zod'
import type { DiscoveredFunction, DiscoveredModel } from '../src/codegen/discover'
import {
  type CodecForGeneration,
  generateApiFile,
  generateClientFile,
  generateSchemaFile
} from '../src/codegen/generate'
import { zx } from '../src/zx'

const userDocSchema = z.object({ _id: z.string(), name: z.string(), email: z.string() })

const userPaginatedDocSchema = z.object({
  page: z.array(userDocSchema),
  isDone: z.boolean(),
  continueCursor: z.string().nullable().optional()
})

const sampleModels: DiscoveredModel[] = [
  {
    exportName: 'UserModel',
    tableName: 'users',
    sourceFile: 'models/user.ts',
    schemas: {
      doc: userDocSchema,
      insert: z.object({ name: z.string(), email: z.string() }),
      update: z.object({ name: z.string().optional() }),
      docArray: z.array(userDocSchema),
      paginatedDoc: userPaginatedDocSchema
    }
  }
]

const sampleFunctions: DiscoveredFunction[] = [
  {
    functionPath: 'users:get',
    exportName: 'get',
    sourceFile: 'users.ts',
    zodArgs: z.object({ id: zx.id('users') }),
    zodReturns: userDocSchema // Same object reference as model's doc schema
  },
  {
    functionPath: 'users:create',
    exportName: 'create',
    sourceFile: 'users.ts',
    zodArgs: z.object({ name: z.string(), email: z.string() }),
    zodReturns: zx.id('users')
  },
  {
    functionPath: 'users:list',
    exportName: 'list',
    sourceFile: 'users.ts',
    zodArgs: z.object({}),
    zodReturns: undefined
  }
]

describe('generateSchemaFile', () => {
  it('generates model re-exports with header', () => {
    const output = generateSchemaFile(sampleModels)

    expect(output).toContain('// AUTO-GENERATED by zodvex')
    expect(output).toContain("export { UserModel } from '../models/user'")
  })

  it('generates multiple model re-exports', () => {
    const models: DiscoveredModel[] = [
      ...sampleModels,
      {
        exportName: 'PostModel',
        tableName: 'posts',
        sourceFile: 'models/post.ts',
        schemas: sampleModels[0].schemas // Doesn't matter for schema file
      }
    ]
    const output = generateSchemaFile(models)

    expect(output).toContain("export { UserModel } from '../models/user'")
    expect(output).toContain("export { PostModel } from '../models/post'")
  })
})

describe('generateApiFile', () => {
  it('generates registry with function path keys', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    expect(output).toContain('// AUTO-GENERATED by zodvex')
    expect(output).toContain('export const zodvexRegistry')
    expect(output).toContain("'users:get'")
    expect(output).toContain("'users:create'")
    expect(output).toContain("'users:list'")
  })

  it('uses model reference for identity-matched schemas', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    // users:get returns userDocSchema which is === sampleModels[0].schemas.doc
    expect(output).toContain('UserModel.schema.doc')
  })

  it('uses zodToSource for ad-hoc schemas', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    // users:create returns zx.id('users') which is NOT identity-matched to a model
    expect(output).toContain('zx.id("users")')
  })

  it('generates correct imports', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    expect(output).toContain("import { z } from 'zod'")
    expect(output).toContain("import { zx } from 'zodvex/core'")
    expect(output).toContain("import { UserModel } from '../models/user'")
  })

  it('handles functions with no returns schema', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    // users:list has no returns
    expect(output).toContain("'users:list'")
    expect(output).toContain('returns: undefined')
  })
})

describe('wrapper-aware identity matching', () => {
  it('.nullable() of model doc schema uses Model.schema.doc.nullable()', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({ id: zx.id('users') }),
        zodReturns: userDocSchema.nullable()
      }
    ]
    const output = generateApiFile(funcs, sampleModels)
    expect(output).toContain('UserModel.schema.doc.nullable()')
  })

  it('.optional() of model doc schema uses Model.schema.doc.optional()', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({ id: zx.id('users') }),
        zodReturns: userDocSchema.optional()
      }
    ]
    const output = generateApiFile(funcs, sampleModels)
    expect(output).toContain('UserModel.schema.doc.optional()')
  })

  it('.nullable().optional() wraps correctly', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({}),
        zodReturns: userDocSchema.nullable().optional()
      }
    ]
    const output = generateApiFile(funcs, sampleModels)
    // The outer wrapper is .optional(), inner is .nullable(), unwrapping peels them
    expect(output).toContain('UserModel.schema.doc.nullable().optional()')
  })
})

describe('codec integration', () => {
  it('codec in function args generates import and reference', () => {
    const testCodec = zx.codec(z.number(), z.object({ hours: z.number(), minutes: z.number() }), {
      decode: (n: number) => ({ hours: Math.floor(n / 60), minutes: n % 60 }),
      encode: (d: { hours: number; minutes: number }) => d.hours * 60 + d.minutes
    })
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'tasks:create',
        exportName: 'create',
        sourceFile: 'tasks.ts',
        zodArgs: z.object({ estimate: testCodec }),
        zodReturns: zx.id('tasks')
      }
    ]
    const output = generateApiFile(funcs, sampleModels, [
      {
        exportName: 'zDuration',
        sourceFile: 'codecs.ts',
        schema: testCodec
      }
    ])
    expect(output).toContain('zDuration')
    expect(output).toContain("import { zDuration } from '../codecs'")
  })

  it('backward compat: generateApiFile works without codecs param', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)
    expect(output).toContain('export const zodvexRegistry')
  })
})

describe('paginatedDoc identity matching', () => {
  it('uses Model.schema.paginatedDoc for identity-matched paginated returns', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:list',
        exportName: 'list',
        sourceFile: 'users.ts',
        zodArgs: z.object({}),
        zodReturns: userPaginatedDocSchema // Same reference as model's paginatedDoc
      }
    ]
    const output = generateApiFile(funcs, sampleModels)
    expect(output).toContain('UserModel.schema.paginatedDoc')
  })
})

describe('generateClientFile', () => {
  it('should generate client file with pre-bound hooks and client factory', () => {
    const content = generateClientFile()
    expect(content).toContain("import { createZodvexHooks } from 'zodvex/react'")
    expect(content).toContain(
      "import { createZodvexClient, type ZodvexClientOptions } from 'zodvex/client'"
    )
    expect(content).toContain("import { zodvexRegistry } from './api'")
    expect(content).toContain('useZodQuery')
    expect(content).toContain('useZodMutation')
    expect(content).toContain('createClient')
    expect(content).toContain('AUTO-GENERATED')
  })
})
