import fs from 'node:fs'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { z } from 'zod'
import { discoverModules } from '../src/public/codegen/discover'
import {
  generateApiFile,
  generateClientFile,
  generateSchemaFile
} from '../src/public/codegen/generate'

const fixtureDir = path.resolve(__dirname, 'fixtures/codegen-project')
const outputDir = path.join(fixtureDir, '_zodvex')

afterEach(() => {
  if (fs.existsSync(outputDir)) {
    fs.rmSync(outputDir, { recursive: true })
  }
})

describe('codegen e2e', () => {
  it('full pipeline: discover → generate → write → verify', async () => {
    // 1. Discover
    const result = await discoverModules(fixtureDir)
    expect(result.models.length).toBe(2) // UserModel + EventModel
    expect(result.functions.length).toBeGreaterThanOrEqual(3) // get, list, update

    // 2. Generate
    const schema = generateSchemaFile(result.models)
    const api = generateApiFile(result.functions, result.models, result.codecs, result.modelCodecs)
    const client = generateClientFile()

    // 3. Write to _zodvex/
    fs.mkdirSync(outputDir, { recursive: true })
    fs.writeFileSync(path.join(outputDir, 'schema.js'), schema.js)
    fs.writeFileSync(path.join(outputDir, 'schema.d.ts'), schema.dts)
    fs.writeFileSync(path.join(outputDir, 'api.js'), api.js)
    fs.writeFileSync(path.join(outputDir, 'api.d.ts'), api.dts)
    fs.writeFileSync(path.join(outputDir, 'client.js'), client.js)
    fs.writeFileSync(path.join(outputDir, 'client.d.ts'), client.dts)

    // 4. Verify files exist
    expect(fs.existsSync(path.join(outputDir, 'schema.js'))).toBe(true)
    expect(fs.existsSync(path.join(outputDir, 'schema.d.ts'))).toBe(true)
    expect(fs.existsSync(path.join(outputDir, 'api.js'))).toBe(true)
    expect(fs.existsSync(path.join(outputDir, 'api.d.ts'))).toBe(true)
    expect(fs.existsSync(path.join(outputDir, 'client.js'))).toBe(true)
    expect(fs.existsSync(path.join(outputDir, 'client.d.ts'))).toBe(true)

    // 5. Verify schema.js content
    expect(schema.js).toContain('// AUTO-GENERATED by zodvex')
    expect(schema.js).toContain("export { UserModel } from '../models/user.js'")
    expect(schema.js).toContain("export { EventModel } from '../models/event.js'")

    // 6. Verify api.js content
    expect(api.js).toContain('// AUTO-GENERATED by zodvex')
    expect(api.js).toContain('export const zodvexRegistry')
    expect(api.js).toContain("'users:get'")
    expect(api.js).toContain("'users:list'")
    expect(api.js).toContain("'users:update'")

    // 7. Verify ad-hoc schemas are serialized with zodToSource
    expect(api.js).toContain('z.object(')
    expect(api.js).toContain('z.string()')

    // 8. Verify client.js content
    expect(client.js).toContain('// AUTO-GENERATED by zodvex')
    expect(client.js).toContain("import { createZodvexHooks } from 'zodvex/react'")
    expect(client.js).toContain("import { createZodvexReactClient } from 'zodvex/react'")
    expect(client.js).toContain("import { createZodvexClient } from 'zodvex/client'")
    expect(client.js).toContain("import { createBoundaryHelpers } from 'zodvex'")
    expect(client.js).toContain("import { zodvexRegistry } from './api.js'")
    expect(client.js).toContain('useZodQuery')
    expect(client.js).toContain('useZodMutation')
    expect(client.js).toContain('createClient')
    expect(client.js).toContain('createReactClient')
    expect(client.js).toContain('encodeArgs')
    expect(client.js).toContain('decodeResult')

    // 9. Verify codec discovery
    expect(result.codecs.length).toBeGreaterThanOrEqual(1)
    expect(result.codecs.some(c => c.exportName === 'zDuration')).toBe(true)

    // 10. Verify codec handling in api.js — no unsupported pipe fallback
    expect(api.js).not.toContain('unsupported: pipe')
  })

  it('schema.js has correct import paths relative to _zodvex/', async () => {
    const result = await discoverModules(fixtureDir)
    const { js: schemaJs } = generateSchemaFile(result.models)

    // Import path should go up from _zodvex/ to the source file
    expect(schemaJs).toContain("from '../models/user.js'")
  })

  it('api.js imports zod when ad-hoc schemas are present', async () => {
    const result = await discoverModules(fixtureDir)
    const { js: apiJs } = generateApiFile(
      result.functions,
      result.models,
      result.codecs,
      result.modelCodecs
    )

    expect(apiJs).toContain("import { z } from 'zod'")
  })

  it('client.js imports from zodvex/react, zodvex/client, zodvex, and ./api.js', () => {
    const { js: clientJs } = generateClientFile()
    expect(clientJs).toContain("from 'zodvex/react'")
    expect(clientJs).toContain("from 'zodvex/client'")
    expect(clientJs).toContain("from 'zodvex'")
    expect(clientJs).toContain("from './api.js'")
  })

  it('discovers union models and generates identity-matched references', async () => {
    const result = await discoverModules(fixtureDir)

    // Should discover both models
    const eventModel = result.models.find(m => m.exportName === 'EventModel')
    expect(eventModel).toBeDefined()
    expect(eventModel?.tableName).toBe('events')

    // Generate schema file should re-export EventModel
    const { js: schemaJs } = generateSchemaFile(result.models)
    expect(schemaJs).toContain("export { EventModel } from '../models/event.js'")

    // Generate api file should include EventModel import when referenced
    const { js: apiJs } = generateApiFile(
      result.functions,
      result.models,
      result.codecs,
      result.modelCodecs
    )
    expect(apiJs).toContain('export const zodvexRegistry')
  })

  it('union model schemas are included in identity map', async () => {
    const result = await discoverModules(fixtureDir)

    const eventModel = result.models.find(m => m.exportName === 'EventModel')
    if (!eventModel) throw new Error('EventModel not found')

    // Create a function that returns the event model's paginatedDoc
    const funcs = [
      {
        functionPath: 'events:list',
        exportName: 'list',
        sourceFile: 'events.ts',
        zodArgs: z.object({}),
        zodReturns: eventModel.schemas.paginatedDoc
      }
    ]

    const { js: apiJs } = generateApiFile(funcs, result.models, result.codecs, result.modelCodecs)
    expect(apiJs).toContain('EventModel.schema.paginatedDoc')
  })

  it('discovers model-embedded codecs from fixture models', async () => {
    const result = await discoverModules(fixtureDir)
    // UserModel now has a tagged codec in the email field
    expect(result.modelCodecs.length).toBeGreaterThanOrEqual(1)
    const emailCodec = result.modelCodecs.find(mc => mc.accessPath === '.shape.email')
    expect(emailCodec).toBeDefined()
    expect(emailCodec?.modelExportName).toBe('UserModel')
  })

  it('model-embedded codecs in .partial() args produce extractCodec references', async () => {
    const result = await discoverModules(fixtureDir)
    const { js: apiJs } = generateApiFile(
      result.functions,
      result.models,
      result.codecs,
      result.modelCodecs
    )

    // Should NOT contain "transforms lost" for model-derived codecs
    expect(apiJs).not.toContain('transforms lost')
    // Should contain extractCodec references
    expect(apiJs).toContain('extractCodec')
    expect(apiJs).toContain("from 'zodvex'")
    expect(apiJs).toContain('extractCodec')
  })

  it('schema.js has no duplicate exports when barrel files exist', async () => {
    const result = await discoverModules(fixtureDir)
    const { js: schemaJs } = generateSchemaFile(result.models)

    // Count occurrences of each export
    const userExports = schemaJs.match(/export \{ UserModel \}/g)
    const eventExports = schemaJs.match(/export \{ EventModel \}/g)
    expect(userExports?.length).toBe(1)
    expect(eventExports?.length).toBe(1)

    // Should use direct module paths, not barrel
    expect(schemaJs).toContain("from '../models/user.js'")
    expect(schemaJs).toContain("from '../models/event.js'")
    expect(schemaJs).not.toContain("from '../models/index'")
  })

  it('skips _generated/ and _zodvex/ during discovery', async () => {
    // Create a dummy file in _zodvex/ to ensure it's skipped
    fs.mkdirSync(outputDir, { recursive: true })
    fs.writeFileSync(path.join(outputDir, 'schema.ts'), '// dummy')

    const result = await discoverModules(fixtureDir)

    const allPaths = [
      ...result.models.map(m => m.sourceFile),
      ...result.functions.map(f => f.sourceFile)
    ]
    for (const p of allPaths) {
      expect(p).not.toContain('_zodvex')
      expect(p).not.toContain('_generated')
    }
  })
})
