import { describe, expect, it } from 'bun:test'
import { z } from 'zod'
import type {
  DiscoveredFunction,
  DiscoveredModel,
  FunctionEmbeddedCodec,
  ModelEmbeddedCodec
} from '../src/codegen/discover'
import {
  type CodecForGeneration,
  generateApiFile,
  generateClientFile,
  generateSchemaFile,
  generateServerFile
} from '../src/codegen/generate'
import { zx } from '../src/zx'

const userDocSchema = z.object({ _id: z.string(), name: z.string(), email: z.string() })

const userPaginatedDocSchema = z.object({
  page: z.array(userDocSchema),
  isDone: z.boolean(),
  continueCursor: z.string().nullable().optional()
})

const sampleModels: DiscoveredModel[] = [
  {
    exportName: 'UserModel',
    tableName: 'users',
    sourceFile: 'models/user.ts',
    schemas: {
      doc: userDocSchema,
      insert: z.object({ name: z.string(), email: z.string() }),
      update: z.object({ name: z.string().optional() }),
      docArray: z.array(userDocSchema),
      paginatedDoc: userPaginatedDocSchema
    }
  }
]

const sampleFunctions: DiscoveredFunction[] = [
  {
    functionPath: 'users:get',
    exportName: 'get',
    sourceFile: 'users.ts',
    zodArgs: z.object({ id: zx.id('users') }),
    zodReturns: userDocSchema // Same object reference as model's doc schema
  },
  {
    functionPath: 'users:create',
    exportName: 'create',
    sourceFile: 'users.ts',
    zodArgs: z.object({ name: z.string(), email: z.string() }),
    zodReturns: zx.id('users')
  },
  {
    functionPath: 'users:list',
    exportName: 'list',
    sourceFile: 'users.ts',
    zodArgs: z.object({}),
    zodReturns: undefined
  }
]

describe('generateSchemaFile', () => {
  it('generates model re-exports with header', () => {
    const output = generateSchemaFile(sampleModels)

    expect(output).toContain('// AUTO-GENERATED by zodvex')
    expect(output).toContain("export { UserModel } from '../models/user'")
  })

  it('generates multiple model re-exports', () => {
    const models: DiscoveredModel[] = [
      ...sampleModels,
      {
        exportName: 'PostModel',
        tableName: 'posts',
        sourceFile: 'models/post.ts',
        schemas: sampleModels[0].schemas // Doesn't matter for schema file
      }
    ]
    const output = generateSchemaFile(models)

    expect(output).toContain("export { UserModel } from '../models/user'")
    expect(output).toContain("export { PostModel } from '../models/post'")
  })
})

describe('generateApiFile', () => {
  it('generates registry with function path keys', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    expect(output).toContain('// AUTO-GENERATED by zodvex')
    expect(output).toContain('export const zodvexRegistry')
    expect(output).toContain("'users:get'")
    expect(output).toContain("'users:create'")
    expect(output).toContain("'users:list'")
  })

  it('uses model reference for identity-matched schemas', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    // users:get returns userDocSchema which is === sampleModels[0].schemas.doc
    expect(output).toContain('UserModel.schema.doc')
  })

  it('uses zodToSource for ad-hoc schemas', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    // users:create returns zx.id('users') which is NOT identity-matched to a model
    expect(output).toContain('zx.id("users")')
  })

  it('generates correct imports', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    expect(output).toContain("import { z } from 'zod'")
    expect(output).toContain("import { zx } from 'zodvex/core'")
    expect(output).toContain("import { UserModel } from '../models/user'")
  })

  it('handles functions with no returns schema', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    // users:list has no returns
    expect(output).toContain("'users:list'")
    expect(output).toContain('returns: undefined')
  })
})

describe('wrapper-aware identity matching', () => {
  it('.nullable() of model doc schema uses Model.schema.doc.nullable()', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({ id: zx.id('users') }),
        zodReturns: userDocSchema.nullable()
      }
    ]
    const output = generateApiFile(funcs, sampleModels)
    expect(output).toContain('UserModel.schema.doc.nullable()')
  })

  it('.optional() of model doc schema uses Model.schema.doc.optional()', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({ id: zx.id('users') }),
        zodReturns: userDocSchema.optional()
      }
    ]
    const output = generateApiFile(funcs, sampleModels)
    expect(output).toContain('UserModel.schema.doc.optional()')
  })

  it('.nullable().optional() wraps correctly', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({}),
        zodReturns: userDocSchema.nullable().optional()
      }
    ]
    const output = generateApiFile(funcs, sampleModels)
    // The outer wrapper is .optional(), inner is .nullable(), unwrapping peels them
    expect(output).toContain('UserModel.schema.doc.nullable().optional()')
  })
})

describe('codec integration', () => {
  it('codec in function args generates import and reference', () => {
    const testCodec = zx.codec(z.number(), z.object({ hours: z.number(), minutes: z.number() }), {
      decode: (n: number) => ({ hours: Math.floor(n / 60), minutes: n % 60 }),
      encode: (d: { hours: number; minutes: number }) => d.hours * 60 + d.minutes
    })
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'tasks:create',
        exportName: 'create',
        sourceFile: 'tasks.ts',
        zodArgs: z.object({ estimate: testCodec }),
        zodReturns: zx.id('tasks')
      }
    ]
    const output = generateApiFile(funcs, sampleModels, [
      {
        exportName: 'zDuration',
        sourceFile: 'codecs.ts',
        schema: testCodec
      }
    ])
    expect(output).toContain('zDuration')
    expect(output).toContain("import { zDuration } from '../codecs'")
  })

  it('backward compat: generateApiFile works without codecs param', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)
    expect(output).toContain('export const zodvexRegistry')
  })
})

describe('paginatedDoc identity matching', () => {
  it('uses Model.schema.paginatedDoc for identity-matched paginated returns', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:list',
        exportName: 'list',
        sourceFile: 'users.ts',
        zodArgs: z.object({}),
        zodReturns: userPaginatedDocSchema // Same reference as model's paginatedDoc
      }
    ]
    const output = generateApiFile(funcs, sampleModels)
    expect(output).toContain('UserModel.schema.paginatedDoc')
  })
})

describe('generateClientFile', () => {
  it('should generate client file with pre-bound hooks and client factory', () => {
    const content = generateClientFile()
    expect(content).toContain("import { createZodvexHooks } from 'zodvex/react'")
    expect(content).toContain(
      "import { createZodvexClient, type ZodvexClientOptions } from 'zodvex/client'"
    )
    expect(content).toContain("import { zodvexRegistry } from './api'")
    expect(content).toContain('useZodQuery')
    expect(content).toContain('useZodMutation')
    expect(content).toContain('createClient')
    expect(content).toContain('AUTO-GENERATED')
  })
})

describe('generateServerFile', () => {
  it('generates concrete context type aliases', () => {
    const content = generateServerFile()
    expect(content).toContain('AUTO-GENERATED')
    expect(content).toContain("import type { DataModel } from '../_generated/dataModel'")
    expect(content).toContain(
      "import type { ZodvexActionCtx, ZodvexMutationCtx, ZodvexQueryCtx } from 'zodvex/server'"
    )
    expect(content).toContain("import type schema from '../schema'")
    expect(content).toContain("type DecodedDocs = (typeof schema)['__decodedDocs']")
    expect(content).toContain('export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>')
    expect(content).toContain('export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>')
    expect(content).toContain('export type ActionCtx = ZodvexActionCtx<DataModel>')
  })
})

describe('model-embedded codec resolution', () => {
  const testCodec = zx.codec(
    z.object({ value: z.string(), tag: z.string() }),
    z.object({ value: z.string(), tag: z.string(), display: z.string() }),
    {
      decode: (w: any) => ({ ...w, display: `[${w.tag}] ${w.value}` }),
      encode: (r: any) => ({ value: r.value, tag: r.tag })
    }
  )

  const codecModel: DiscoveredModel = {
    exportName: 'UserModel',
    tableName: 'users',
    sourceFile: 'models/user.ts',
    schemas: {
      doc: z.object({ _id: z.string(), name: z.string(), email: testCodec.optional() }),
      insert: z.object({ name: z.string(), email: testCodec.optional() }),
      update: z.object({ name: z.string().optional(), email: testCodec.optional() }),
      docArray: z.array(
        z.object({ _id: z.string(), name: z.string(), email: testCodec.optional() })
      ),
      paginatedDoc: z.object({
        page: z.array(z.object({ _id: z.string(), name: z.string(), email: testCodec.optional() })),
        isDone: z.boolean(),
        continueCursor: z.string().nullable().optional()
      })
    }
  }

  const modelCodecs: ModelEmbeddedCodec[] = [
    {
      codec: testCodec,
      modelExportName: 'UserModel',
      modelSourceFile: 'models/user.ts',
      schemaKey: 'doc',
      accessPath: '.shape.email'
    }
  ]

  it('resolves model-embedded codec in .partial() args', () => {
    const partialArgs = (codecModel.schemas.doc as z.ZodObject<any>).partial()
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:update',
        exportName: 'update',
        sourceFile: 'users.ts',
        zodArgs: partialArgs,
        zodReturns: undefined
      }
    ]
    const output = generateApiFile(funcs, [codecModel], [], modelCodecs)

    // Should NOT contain "transforms lost"
    expect(output).not.toContain('transforms lost')
    // Should contain extractCodec import and helper var
    expect(output).toContain("import { extractCodec } from 'zodvex/codegen'")
    expect(output).toContain("import { UserModel } from '../models/user'")
    expect(output).toContain('extractCodec(UserModel.schema.doc.shape.email)')
  })

  it('model-embedded codec in .extend() args preserves transforms', () => {
    const extendedArgs = (codecModel.schemas.doc as z.ZodObject<any>).extend({ extra: z.string() })
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:update',
        exportName: 'update',
        sourceFile: 'users.ts',
        zodArgs: extendedArgs,
        zodReturns: undefined
      }
    ]
    const output = generateApiFile(funcs, [codecModel], [], modelCodecs)
    expect(output).not.toContain('transforms lost')
  })

  it('still uses exported codec when both model-embedded and exported exist', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'tasks:create',
        exportName: 'create',
        sourceFile: 'tasks.ts',
        zodArgs: z.object({ estimate: testCodec }),
        zodReturns: undefined
      }
    ]
    // Pass same codec as both exported and model-embedded
    const exportedCodecs: CodecForGeneration[] = [
      { exportName: 'zTagged', sourceFile: 'codecs.ts', schema: testCodec }
    ]
    const output = generateApiFile(funcs, [codecModel], exportedCodecs, modelCodecs)

    // Exported codec takes precedence (simpler reference)
    expect(output).toContain('zTagged')
    expect(output).toContain("import { zTagged } from '../codecs'")
  })
})

describe('function-embedded codec resolution', () => {
  // A codec that only exists in function args (not in any model or export)
  const inlineCodec = zx.codec(z.string(), z.string(), {
    decode: (w: string) => w.toUpperCase(),
    encode: (r: string) => r.toLowerCase()
  })

  it('resolves function-embedded codec in args', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:search',
        exportName: 'search',
        sourceFile: 'users.ts',
        zodArgs: z.object({ query: inlineCodec }),
        zodReturns: undefined
      }
    ]
    const fnCodecs: FunctionEmbeddedCodec[] = [
      {
        codec: inlineCodec,
        functionExportName: 'search',
        functionSourceFile: 'users.ts',
        schemaSource: 'zodArgs',
        accessPath: '.shape.query'
      }
    ]
    const output = generateApiFile(funcs, [], [], [], fnCodecs)

    expect(output).not.toContain('transforms lost')
    expect(output).toContain('readFnArgs')
    expect(output).toContain("import { extractCodec, readFnArgs } from 'zodvex/codegen'")
    expect(output).toContain("import { search } from '../users'")
    expect(output).toContain('extractCodec(readFnArgs(search).shape.query)')
  })

  it('resolves function-embedded codec in returns', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({}),
        zodReturns: z.object({ data: inlineCodec })
      }
    ]
    const fnCodecs: FunctionEmbeddedCodec[] = [
      {
        codec: inlineCodec,
        functionExportName: 'get',
        functionSourceFile: 'users.ts',
        schemaSource: 'zodReturns',
        accessPath: '.shape.data'
      }
    ]
    const output = generateApiFile(funcs, [], [], [], fnCodecs)

    expect(output).not.toContain('transforms lost')
    expect(output).toContain('readFnReturns')
    expect(output).toContain("import { extractCodec, readFnReturns } from 'zodvex/codegen'")
    expect(output).toContain('extractCodec(readFnReturns(get).shape.data)')
  })

  it('model codec takes precedence over function codec for same instance', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:update',
        exportName: 'update',
        sourceFile: 'users.ts',
        zodArgs: z.object({ email: inlineCodec }),
        zodReturns: undefined
      }
    ]
    const modelCodecs: ModelEmbeddedCodec[] = [
      {
        codec: inlineCodec,
        modelExportName: 'UserModel',
        modelSourceFile: 'models/user.ts',
        schemaKey: 'doc',
        accessPath: '.shape.email'
      }
    ]
    const fnCodecs: FunctionEmbeddedCodec[] = [
      {
        codec: inlineCodec,
        functionExportName: 'update',
        functionSourceFile: 'users.ts',
        schemaSource: 'zodArgs',
        accessPath: '.shape.email'
      }
    ]
    const output = generateApiFile(funcs, [], [], modelCodecs, fnCodecs)

    // Model codec should win — uses extractCodec(UserModel.schema...) not readFnArgs
    expect(output).toContain('UserModel.schema.doc')
    expect(output).not.toContain('readFnArgs')
  })

  it('exported codec takes precedence over function codec', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'test:fn',
        exportName: 'fn',
        sourceFile: 'test.ts',
        zodArgs: z.object({ val: inlineCodec }),
        zodReturns: undefined
      }
    ]
    const exportedCodecs: CodecForGeneration[] = [
      { exportName: 'myCodec', sourceFile: 'codecs.ts', schema: inlineCodec }
    ]
    const fnCodecs: FunctionEmbeddedCodec[] = [
      {
        codec: inlineCodec,
        functionExportName: 'fn',
        functionSourceFile: 'test.ts',
        schemaSource: 'zodArgs',
        accessPath: '.shape.val'
      }
    ]
    const output = generateApiFile(funcs, [], exportedCodecs, [], fnCodecs)

    // Exported codec wins
    expect(output).toContain('myCodec')
    expect(output).not.toContain('readFnArgs')
  })
})
