import { describe, expect, it } from 'vitest'
import { z } from 'zod'
import type {
  DiscoveredFunction,
  DiscoveredModel,
  FunctionEmbeddedCodec,
  ModelEmbeddedCodec
} from '../src/codegen/discover'
import {
  type CodecForGeneration,
  type GeneratedFile,
  generateApiFile,
  generateClientFile,
  generateSchemaFile,
  generateServerFile
} from '../src/codegen/generate'
import { zx } from '../src/zx'

const userDocSchema = z.object({ _id: z.string(), name: z.string(), email: z.string() })

const userPaginatedDocSchema = z.object({
  page: z.array(userDocSchema),
  isDone: z.boolean(),
  continueCursor: z.string().nullable().optional()
})

const sampleModels: DiscoveredModel[] = [
  {
    exportName: 'UserModel',
    tableName: 'users',
    sourceFile: 'models/user.ts',
    schemas: {
      doc: userDocSchema,
      insert: z.object({ name: z.string(), email: z.string() }),
      update: z.object({ name: z.string().optional() }),
      docArray: z.array(userDocSchema),
      paginatedDoc: userPaginatedDocSchema
    }
  }
]

const sampleFunctions: DiscoveredFunction[] = [
  {
    functionPath: 'users:get',
    exportName: 'get',
    sourceFile: 'users.ts',
    zodArgs: z.object({ id: zx.id('users') }),
    zodReturns: userDocSchema // Same object reference as model's doc schema
  },
  {
    functionPath: 'users:create',
    exportName: 'create',
    sourceFile: 'users.ts',
    zodArgs: z.object({ name: z.string(), email: z.string() }),
    zodReturns: zx.id('users')
  },
  {
    functionPath: 'users:list',
    exportName: 'list',
    sourceFile: 'users.ts',
    zodArgs: z.object({}),
    zodReturns: undefined
  }
]

describe('generateSchemaFile', () => {
  it('returns js and dts with model re-exports using .js extensions', () => {
    const { js, dts } = generateSchemaFile(sampleModels)

    // JS file: value re-exports with .js extensions
    expect(js).toContain('// AUTO-GENERATED by zodvex')
    expect(js).toContain("export { UserModel } from '../models/user.js'")
    expect(js).not.toContain('.ts')

    // DTS file: same re-exports (TS resolves types from .js targets)
    expect(dts).toContain('// AUTO-GENERATED by zodvex')
    expect(dts).toContain("export { UserModel } from '../models/user.js'")
  })

  it('generates multiple model re-exports in both js and dts', () => {
    const models: DiscoveredModel[] = [
      ...sampleModels,
      {
        exportName: 'PostModel',
        tableName: 'posts',
        sourceFile: 'models/post.ts',
        schemas: sampleModels[0].schemas
      }
    ]
    const { js, dts } = generateSchemaFile(models)

    expect(js).toContain("export { UserModel } from '../models/user.js'")
    expect(js).toContain("export { PostModel } from '../models/post.js'")
    expect(dts).toContain("export { UserModel } from '../models/user.js'")
    expect(dts).toContain("export { PostModel } from '../models/post.js'")
  })
})

describe('generateApiFile', () => {
  it('generates registry with function path keys', () => {
    const { js: output } = generateApiFile(sampleFunctions, sampleModels)

    expect(output).toContain('// AUTO-GENERATED by zodvex')
    expect(output).toContain('export const zodvexRegistry')
    expect(output).toContain("'users:get'")
    expect(output).toContain("'users:create'")
    expect(output).toContain("'users:list'")
  })

  it('uses model reference for identity-matched schemas', () => {
    const { js: output } = generateApiFile(sampleFunctions, sampleModels)

    // users:get returns userDocSchema which is === sampleModels[0].schemas.doc
    expect(output).toContain('UserModel.schema.doc')
  })

  it('uses zodToSource for ad-hoc schemas', () => {
    const { js: output } = generateApiFile(sampleFunctions, sampleModels)

    // users:create returns zx.id('users') which is NOT identity-matched to a model
    expect(output).toContain('zx.id("users")')
  })

  it('generates correct imports with .js extensions', () => {
    const { js: output } = generateApiFile(sampleFunctions, sampleModels)

    expect(output).toContain("import { z } from 'zod'")
    expect(output).toContain("import { zx } from 'zodvex/core'")
    expect(output).toContain("import { UserModel } from '../models/user.js'")
    expect(output).not.toContain("from '../models/user'\"")
  })

  it('handles functions with no returns schema', () => {
    const { js: output } = generateApiFile(sampleFunctions, sampleModels)

    // users:list has no returns
    expect(output).toContain("'users:list'")
    expect(output).toContain('returns: undefined')
  })

  it('does not include as const in JS output', () => {
    const { js } = generateApiFile(sampleFunctions, sampleModels)
    expect(js).not.toContain('as const')
  })

  it('dts declares zodvexRegistry with loose type', () => {
    const { dts } = generateApiFile(sampleFunctions, sampleModels)
    expect(dts).toContain('// AUTO-GENERATED by zodvex')
    expect(dts).toContain("import type { ZodTypeAny } from 'zod'")
    expect(dts).toContain(
      'export declare const zodvexRegistry: Record<string, { args: ZodTypeAny; returns: ZodTypeAny | undefined }>'
    )
  })
})

describe('wrapper-aware identity matching', () => {
  it('.nullable() of model doc schema uses Model.schema.doc.nullable()', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({ id: zx.id('users') }),
        zodReturns: userDocSchema.nullable()
      }
    ]
    const { js: output } = generateApiFile(funcs, sampleModels)
    expect(output).toContain('UserModel.schema.doc.nullable()')
  })

  it('.optional() of model doc schema uses Model.schema.doc.optional()', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({ id: zx.id('users') }),
        zodReturns: userDocSchema.optional()
      }
    ]
    const { js: output } = generateApiFile(funcs, sampleModels)
    expect(output).toContain('UserModel.schema.doc.optional()')
  })

  it('.nullable().optional() wraps correctly', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:get',
        exportName: 'get',
        sourceFile: 'users.ts',
        zodArgs: z.object({}),
        zodReturns: userDocSchema.nullable().optional()
      }
    ]
    const { js: output } = generateApiFile(funcs, sampleModels)
    // The outer wrapper is .optional(), inner is .nullable(), unwrapping peels them
    expect(output).toContain('UserModel.schema.doc.nullable().optional()')
  })
})

describe('codec integration', () => {
  it('codec in function args generates import and reference', () => {
    const testCodec = zx.codec(z.number(), z.object({ hours: z.number(), minutes: z.number() }), {
      decode: (n: number) => ({ hours: Math.floor(n / 60), minutes: n % 60 }),
      encode: (d: { hours: number; minutes: number }) => d.hours * 60 + d.minutes
    })
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'tasks:create',
        exportName: 'create',
        sourceFile: 'tasks.ts',
        zodArgs: z.object({ estimate: testCodec }),
        zodReturns: zx.id('tasks')
      }
    ]
    const { js: output } = generateApiFile(funcs, sampleModels, [
      {
        exportName: 'zDuration',
        sourceFile: 'codecs.ts',
        schema: testCodec
      }
    ])
    expect(output).toContain('zDuration')
    expect(output).toContain("import { zDuration } from '../codecs.js'")
  })

  it('backward compat: generateApiFile works without codecs param', () => {
    const { js: output } = generateApiFile(sampleFunctions, sampleModels)
    expect(output).toContain('export const zodvexRegistry')
  })
})

describe('paginatedDoc identity matching', () => {
  it('uses Model.schema.paginatedDoc for identity-matched paginated returns', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:list',
        exportName: 'list',
        sourceFile: 'users.ts',
        zodArgs: z.object({}),
        zodReturns: userPaginatedDocSchema // Same reference as model's paginatedDoc
      }
    ]
    const { js: output } = generateApiFile(funcs, sampleModels)
    expect(output).toContain('UserModel.schema.paginatedDoc')
  })
})

describe('generateClientFile', () => {
  it('returns js without type annotations and dts with typed declarations', () => {
    const { js, dts } = generateClientFile()

    // JS: runtime code, no type annotations, .js import extensions
    expect(js).toContain('// AUTO-GENERATED by zodvex')
    expect(js).toContain("import { createZodvexHooks } from 'zodvex/react'")
    expect(js).toContain("import { createZodvexReactClient } from 'zodvex/react'")
    expect(js).toContain("import { createZodvexClient } from 'zodvex/client'")
    expect(js).toContain("import { createBoundaryHelpers } from 'zodvex/core'")
    expect(js).toContain("import { zodvexRegistry } from './api.js'")
    expect(js).toContain(
      'export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)'
    )
    expect(js).toContain('export const createClient = (options) =>')
    expect(js).toContain('export const createReactClient = (options) =>')
    expect(js).toContain(
      'export const { encodeArgs, decodeResult } = createBoundaryHelpers(zodvexRegistry)'
    )
    // No type annotations in JS
    expect(js).not.toContain('ZodvexClientOptions')
    expect(js).not.toContain('ZodvexReactClientOptions')
    expect(js).not.toContain('import type')

    // DTS: typed declarations
    expect(dts).toContain('// AUTO-GENERATED by zodvex')
    expect(dts).toContain("export declare const useZodQuery: ZodvexHooks['useZodQuery']")
    expect(dts).toContain("export declare const useZodMutation: ZodvexHooks['useZodMutation']")
    expect(dts).toContain('export declare const createClient:')
    expect(dts).toContain('export declare const createReactClient:')
    expect(dts).toContain('export declare const encodeArgs:')
    expect(dts).toContain('export declare const decodeResult:')
  })

  it('does not include mantineResolver', () => {
    const { js, dts } = generateClientFile()
    expect(js).not.toContain('mantineResolver')
    expect(dts).not.toContain('mantineResolver')
  })
})

describe('generateServerFile', () => {
  it('returns empty js and full dts with context type aliases', () => {
    const { js, dts } = generateServerFile()

    // JS: just header (no runtime code)
    expect(js).toContain('// AUTO-GENERATED by zodvex')
    expect(js).not.toContain('import')
    expect(js).not.toContain('export')

    // DTS: full type definitions with .js extensions on relative imports
    expect(dts).toContain('// AUTO-GENERATED by zodvex')
    expect(dts).toContain("import type { DataModel } from '../_generated/dataModel.js'")
    expect(dts).toContain(
      "import type { ZodvexActionCtx, ZodvexMutationCtx, ZodvexQueryCtx } from 'zodvex/server'"
    )
    expect(dts).toContain("import type schema from '../schema.js'")
    expect(dts).toContain("type DecodedDocs = (typeof schema)['__decodedDocs']")
    expect(dts).toContain('export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>')
    expect(dts).toContain('export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>')
    expect(dts).toContain('export type ActionCtx = ZodvexActionCtx<DataModel>')
  })
})

describe('model-embedded codec resolution', () => {
  const testCodec = zx.codec(
    z.object({ value: z.string(), tag: z.string() }),
    z.object({ value: z.string(), tag: z.string(), display: z.string() }),
    {
      decode: (w: any) => ({ ...w, display: `[${w.tag}] ${w.value}` }),
      encode: (r: any) => ({ value: r.value, tag: r.tag })
    }
  )

  const codecModel: DiscoveredModel = {
    exportName: 'UserModel',
    tableName: 'users',
    sourceFile: 'models/user.ts',
    schemas: {
      doc: z.object({ _id: z.string(), name: z.string(), email: testCodec.optional() }),
      insert: z.object({ name: z.string(), email: testCodec.optional() }),
      update: z.object({ name: z.string().optional(), email: testCodec.optional() }),
      docArray: z.array(
        z.object({ _id: z.string(), name: z.string(), email: testCodec.optional() })
      ),
      paginatedDoc: z.object({
        page: z.array(z.object({ _id: z.string(), name: z.string(), email: testCodec.optional() })),
        isDone: z.boolean(),
        continueCursor: z.string().nullable().optional()
      })
    }
  }

  const modelCodecs: ModelEmbeddedCodec[] = [
    {
      codec: testCodec,
      modelExportName: 'UserModel',
      modelSourceFile: 'models/user.ts',
      schemaKey: 'doc',
      accessPath: '.shape.email'
    }
  ]

  it('resolves model-embedded codec in .partial() args via partial matching', () => {
    const partialArgs = (codecModel.schemas.doc as z.ZodObject<any>).partial()
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:update',
        exportName: 'update',
        sourceFile: 'users.ts',
        zodArgs: partialArgs,
        zodReturns: undefined
      }
    ]
    const { js: output } = generateApiFile(funcs, [codecModel], [], modelCodecs)

    // Partial matching emits compact reference — codecs preserved implicitly
    expect(output).not.toContain('transforms lost')
    expect(output).toContain("import { UserModel } from '../models/user.js'")
    expect(output).toContain('UserModel.schema.doc.partial()')
  })

  it('model-embedded codec in .extend() args preserves transforms', () => {
    const extendedArgs = (codecModel.schemas.doc as z.ZodObject<any>).extend({ extra: z.string() })
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:update',
        exportName: 'update',
        sourceFile: 'users.ts',
        zodArgs: extendedArgs,
        zodReturns: undefined
      }
    ]
    const { js: output } = generateApiFile(funcs, [codecModel], [], modelCodecs)
    expect(output).not.toContain('transforms lost')
  })

  it('still uses exported codec when both model-embedded and exported exist', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'tasks:create',
        exportName: 'create',
        sourceFile: 'tasks.ts',
        zodArgs: z.object({ estimate: testCodec }),
        zodReturns: undefined
      }
    ]
    // Pass same codec as both exported and model-embedded
    const exportedCodecs: CodecForGeneration[] = [
      { exportName: 'zTagged', sourceFile: 'codecs.ts', schema: testCodec }
    ]
    const { js: output } = generateApiFile(funcs, [codecModel], exportedCodecs, modelCodecs)

    // Exported codec takes precedence (simpler reference)
    expect(output).toContain('zTagged')
    expect(output).toContain("import { zTagged } from '../codecs.js'")
  })

  it('uses descriptive variable names derived from model and field path', () => {
    // Use a non-partial schema so it falls through to zodToSource (tests codec var naming)
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:update',
        exportName: 'update',
        sourceFile: 'users.ts',
        zodArgs: z.object({ name: z.string(), email: testCodec }),
        zodReturns: undefined
      }
    ]
    const { js: output } = generateApiFile(funcs, [codecModel], [], modelCodecs)

    // Should use descriptive name, not _mc0
    expect(output).toContain('_userEmail')
    expect(output).not.toMatch(/_mc\d/)
  })

  it('derives names from nested access paths', () => {
    const nestedCodec = zx.codec(
      z.object({ value: z.string() }),
      z.object({ value: z.string(), display: z.string() }),
      {
        decode: (w: any) => ({ ...w, display: w.value }),
        encode: (r: any) => ({ value: r.value })
      }
    )
    const nestedModel: DiscoveredModel = {
      exportName: 'ActivityModel',
      tableName: 'activities',
      sourceFile: 'models/activity.ts',
      schemas: {
        doc: z.object({
          _id: z.string(),
          payload: z.union([
            z.object({ type: z.literal('a'), email: nestedCodec }),
            z.object({ type: z.literal('b') })
          ])
        }),
        insert: z.object({}),
        update: z.object({}),
        docArray: z.array(z.object({})),
        paginatedDoc: z.object({
          page: z.array(z.object({})),
          isDone: z.boolean(),
          continueCursor: z.string().nullable().optional()
        })
      }
    }
    const nestedModelCodecs: ModelEmbeddedCodec[] = [
      {
        codec: nestedCodec,
        modelExportName: 'ActivityModel',
        modelSourceFile: 'models/activity.ts',
        schemaKey: 'doc',
        accessPath: '.shape.payload._zod.def.options[0].shape.email'
      }
    ]
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'activities:update',
        exportName: 'update',
        sourceFile: 'activities.ts',
        zodArgs: z.object({ email: nestedCodec }),
        zodReturns: undefined
      }
    ]
    const { js: output } = generateApiFile(funcs, [nestedModel], [], nestedModelCodecs)

    // Should derive from model name + field path segments
    expect(output).toContain('_activityPayloadEmail')
    expect(output).not.toMatch(/_mc\d/)
  })

  it('handles models without Model suffix', () => {
    const codec = zx.codec(z.string(), z.string(), {
      decode: (w: string) => w.toUpperCase(),
      encode: (r: string) => r.toLowerCase()
    })
    const model: DiscoveredModel = {
      exportName: 'patients',
      tableName: 'patients',
      sourceFile: 'models/patients.ts',
      schemas: {
        doc: z.object({ _id: z.string(), firstName: codec }),
        insert: z.object({ firstName: codec }),
        update: z.object({ firstName: codec.optional() }),
        docArray: z.array(z.object({ _id: z.string(), firstName: codec })),
        paginatedDoc: z.object({
          page: z.array(z.object({})),
          isDone: z.boolean(),
          continueCursor: z.string().nullable().optional()
        })
      }
    }
    const mCodecs: ModelEmbeddedCodec[] = [
      {
        codec,
        modelExportName: 'patients',
        modelSourceFile: 'models/patients.ts',
        schemaKey: 'doc',
        accessPath: '.shape.firstName'
      }
    ]
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'patients:update',
        exportName: 'update',
        sourceFile: 'patients.ts',
        // Extra field prevents partial matching, so codec var naming is exercised
        zodArgs: z.object({ firstName: codec.optional(), reason: z.string() }),
        zodReturns: undefined
      }
    ]
    const { js: output } = generateApiFile(funcs, [model], [], mCodecs)

    expect(output).toContain('_patientsFirstName')
    expect(output).not.toMatch(/_mc\d/)
  })
})

describe('partial-aware identity matching', () => {
  it('matches .partial() of a model schema', () => {
    const partialDoc = (sampleModels[0].schemas.doc as z.ZodObject<any>).partial()
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:update',
        exportName: 'update',
        sourceFile: 'users.ts',
        zodArgs: partialDoc,
        zodReturns: undefined
      }
    ]
    const { js: output } = generateApiFile(funcs, sampleModels)

    // Should emit .partial() reference, not distribute .optional() on each field
    expect(output).toContain('UserModel.schema.doc.partial()')
    expect(output).not.toContain('.optional().optional()')
  })

  it('emits z.partial() in mini mode', () => {
    const partialDoc = (sampleModels[0].schemas.doc as z.ZodObject<any>).partial()
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:update',
        exportName: 'update',
        sourceFile: 'users.ts',
        zodArgs: partialDoc,
        zodReturns: undefined
      }
    ]
    const { js: output } = generateApiFile(funcs, sampleModels, undefined, undefined, undefined, {
      mini: true
    })

    // Mini mode: z.partial(ref) instead of ref.partial()
    expect(output).toContain('z.partial(UserModel.schema.doc)')
    expect(output).not.toContain('.partial()')
  })

  it('doc.partial().extend() double-wraps already-optional fields', () => {
    // Zod's .partial() wraps every field in ZodOptional, even already-optional ones.
    // .extend() then breaks tryMatchPartial (not all fields are optional-wrapped),
    // forcing field-by-field serialization that faithfully emits both optional layers.
    // Consumers should use Model.schema.update instead of doc.partial().extend().
    const docSchema = z.object({
      _id: z.string(),
      _creationTime: z.number(),
      name: z.string(),
      email: z.string().optional()
    })

    const extended = (docSchema as z.ZodObject<any>).partial().extend({
      _id: zx.id('users')
    })
    const shape = extended.shape as Record<string, z.ZodTypeAny>

    // email is now ZodOptional<ZodOptional<ZodString>> — double wrapped
    expect(shape.email).toBeInstanceOf(z.ZodOptional)
    const inner = (shape.email as any)._zod?.def?.innerType
    expect(inner).toBeInstanceOf(z.ZodOptional)
  })
})

describe('function-embedded codec resolution', () => {
  // A codec that only exists in function args (not in any model or export)
  const inlineCodec = zx.codec(z.string(), z.string(), {
    decode: (w: string) => w.toUpperCase(),
    encode: (r: string) => r.toLowerCase()
  })

  it('warns and falls back when function codec has no model/standalone match', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:search',
        exportName: 'search',
        sourceFile: 'users.ts',
        zodArgs: z.object({ query: inlineCodec }),
        zodReturns: undefined
      }
    ]
    const fnCodecs: FunctionEmbeddedCodec[] = [
      {
        codec: inlineCodec,
        functionExportName: 'search',
        functionSourceFile: 'users.ts',
        schemaSource: 'zodArgs',
        accessPath: '.shape.query'
      }
    ]
    const { js: output } = generateApiFile(funcs, [], [], [], fnCodecs)

    // No function imports — avoids circular dependency
    expect(output).not.toContain('import { search }')
    expect(output).not.toContain('readFnArgs')
    // Codec falls through to wire schema
    expect(output).toContain('transforms lost')
  })

  it('fingerprint-matches function codec to structurally equivalent model codec', () => {
    // Two different instances of the same codec factory (like tagged() or encrypted())
    const modelCodecInstance = zx.codec(z.string(), z.string(), {
      decode: (w: string) => w.toUpperCase(),
      encode: (r: string) => r.toLowerCase()
    })
    const fnCodecInstance = zx.codec(z.string(), z.string(), {
      decode: (w: string) => w.toUpperCase(),
      encode: (r: string) => r.toLowerCase()
    })
    expect(modelCodecInstance).not.toBe(fnCodecInstance) // different instances

    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:search',
        exportName: 'search',
        sourceFile: 'users.ts',
        zodArgs: z.object({ query: fnCodecInstance }),
        zodReturns: undefined
      }
    ]
    const modelCodecs: ModelEmbeddedCodec[] = [
      {
        codec: modelCodecInstance,
        modelExportName: 'UserModel',
        modelSourceFile: 'models/user.ts',
        schemaKey: 'doc',
        accessPath: '.shape.query'
      }
    ]
    const fnCodecs: FunctionEmbeddedCodec[] = [
      {
        codec: fnCodecInstance,
        functionExportName: 'search',
        functionSourceFile: 'users.ts',
        schemaSource: 'zodArgs',
        accessPath: '.shape.query'
      }
    ]
    const { js: output } = generateApiFile(funcs, [], [], modelCodecs, fnCodecs)

    // Should resolve via model codec, not function import
    expect(output).not.toContain('transforms lost')
    expect(output).not.toContain('readFnArgs')
    expect(output).not.toContain('import { search }')
    expect(output).toContain('UserModel.schema.doc')
    expect(output).toContain('extractCodec')
  })

  it('model codec takes precedence over function codec for same instance', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'users:update',
        exportName: 'update',
        sourceFile: 'users.ts',
        zodArgs: z.object({ email: inlineCodec }),
        zodReturns: undefined
      }
    ]
    const modelCodecs: ModelEmbeddedCodec[] = [
      {
        codec: inlineCodec,
        modelExportName: 'UserModel',
        modelSourceFile: 'models/user.ts',
        schemaKey: 'doc',
        accessPath: '.shape.email'
      }
    ]
    const fnCodecs: FunctionEmbeddedCodec[] = [
      {
        codec: inlineCodec,
        functionExportName: 'update',
        functionSourceFile: 'users.ts',
        schemaSource: 'zodArgs',
        accessPath: '.shape.email'
      }
    ]
    const { js: output } = generateApiFile(funcs, [], [], modelCodecs, fnCodecs)

    // Model codec should win — uses extractCodec(UserModel.schema...) not readFnArgs
    expect(output).toContain('UserModel.schema.doc')
    expect(output).not.toContain('readFnArgs')
  })

  it('exported codec takes precedence over function codec', () => {
    const funcs: DiscoveredFunction[] = [
      {
        functionPath: 'test:fn',
        exportName: 'fn',
        sourceFile: 'test.ts',
        zodArgs: z.object({ val: inlineCodec }),
        zodReturns: undefined
      }
    ]
    const exportedCodecs: CodecForGeneration[] = [
      { exportName: 'myCodec', sourceFile: 'codecs.ts', schema: inlineCodec }
    ]
    const fnCodecs: FunctionEmbeddedCodec[] = [
      {
        codec: inlineCodec,
        functionExportName: 'fn',
        functionSourceFile: 'test.ts',
        schemaSource: 'zodArgs',
        accessPath: '.shape.val'
      }
    ]
    const { js: output } = generateApiFile(funcs, [], exportedCodecs, [], fnCodecs)

    // Exported codec wins
    expect(output).toContain('myCodec')
    expect(output).not.toContain('readFnArgs')
  })
})
