#!/usr/bin/env node
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { analyze } from './analyze'
import type { TableGraph } from './types'

type ParsedArgs = {
  convexDir: string
  output?: string
  format: 'json' | 'ts'
  quiet: boolean
}

function parseArgs(argv: string[]): ParsedArgs {
  const args: ParsedArgs = {
    convexDir: 'convex',
    format: 'json',
    quiet: false
  }

  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!
    if (a === '--dir' || a === '-d') {
      args.convexDir = argv[++i] ?? args.convexDir
    } else if (a === '--output' || a === '-o') {
      args.output = argv[++i]
    } else if (a === '--format' || a === '-f') {
      const next = argv[++i]
      if (next === 'json' || next === 'ts') args.format = next
    } else if (a === '--quiet' || a === '-q') {
      args.quiet = true
    } else if (a === '--help' || a === '-h') {
      printHelp()
      process.exit(0)
    } else if (!a.startsWith('-')) {
      args.convexDir = a
    }
  }

  return args
}

function printHelp(): void {
  console.log(`Usage: convex-table-graph [options] [convex-dir]

Static analyzer that extracts Convex function → table dependency relationships.

Options:
  -d, --dir <path>     Path to convex/ directory (default: ./convex)
  -o, --output <path>  Write graph to file instead of stdout
  -f, --format <fmt>   Output format: json | ts (default: json)
  -q, --quiet          Suppress diagnostic output on stderr
  -h, --help           Show this help message

Examples:
  convex-table-graph ./my-app/convex
  convex-table-graph -d ./convex -o table-graph.json
  convex-table-graph -d ./convex -o convex-table-graph.generated.ts -f ts
`)
}

function formatAsTs(graph: TableGraph): string {
  const lines: string[] = []
  lines.push('// Generated by convex-table-graph. Do not edit by hand.')
  lines.push('')
  lines.push('export const tableGraph = {')
  lines.push(`  version: ${graph.version},`)
  lines.push('  functions: {')
  const paths = Object.keys(graph.functions).sort()
  for (const p of paths) {
    const info = graph.functions[p]!
    lines.push(`    ${JSON.stringify(p)}: {`)
    lines.push(`      kind: ${JSON.stringify(info.kind)},`)
    lines.push(`      visibility: ${JSON.stringify(info.visibility)},`)
    lines.push(`      reads: ${JSON.stringify(info.reads)} as const,`)
    lines.push(`      writes: ${JSON.stringify(info.writes)} as const,`)
    lines.push(`      confidence: ${JSON.stringify(info.confidence)}`)
    lines.push(`    },`)
  }
  lines.push('  }')
  lines.push('} as const')
  lines.push('')
  lines.push('export type TableGraph = typeof tableGraph')
  return lines.join('\n')
}

function printDiagnostics(graph: TableGraph, quiet: boolean): void {
  if (quiet || graph.diagnostics.length === 0) return
  for (const d of graph.diagnostics) {
    const loc = `${d.file}:${d.line}:${d.column}`
    const fn = d.function ? ` [${d.function}]` : ''
    const code = d.code ? ` (${d.code})` : ''
    process.stderr.write(`${d.severity}: ${loc}${fn} — ${d.message}${code}\n`)
  }
  process.stderr.write(`\n${graph.diagnostics.length} diagnostic(s)\n`)
}

function main(): void {
  const argv = process.argv.slice(2)
  const args = parseArgs(argv)

  const convexDir = path.resolve(args.convexDir)
  const graph = analyze({ convexDir })

  const output = args.format === 'ts' ? formatAsTs(graph) : JSON.stringify(graph, null, 2)

  if (args.output) {
    const outPath = path.resolve(args.output)
    writeFileSync(outPath, output + '\n', 'utf8')
    if (!args.quiet) process.stderr.write(`Wrote ${outPath}\n`)
  } else {
    process.stdout.write(output + '\n')
  }

  printDiagnostics(graph, args.quiet)
}

main()
