#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { analyze } from './analyze'
import { CliUsageError, loadConfigFile, parseArgs, resolveAnalyzeOptions } from './cli-args'
import type { TableGraph } from './types'

function printHelp(): void {
  console.log(`Usage: convex-table-graph [options] [convex-dir]

Static analyzer that extracts Convex function → table dependency relationships.

Options:
  -d, --dir <path>       Path to convex/ directory (default: ./convex)
  -o, --output <path>    Write graph to file instead of stdout
  -f, --format <fmt>     Output format: json | ts (default: json)
  -c, --config <path>    Config file (.json/.js/.mjs/.cjs). Without this flag,
                         convex-table-graph.config.{json,mjs,cjs,js} is auto-discovered
                         in the cwd, then next to the convex/ directory.
  -b, --builder <spec>   Extra builder names as <kind>=<name>[,<name>...]. Repeatable.
                         Kinds: query, mutation, action, internalQuery,
                         internalMutation, internalAction, httpAction
      --db-factory <n>   Names of functions returning a db-like object when passed
                         a db (e.g. zodvexStream). Comma-separated, repeatable.
      --tsconfig <path>  tsconfig.json used for type resolution
      --max-depth <n>    Max call-graph depth for the taint walk (default: 3)
  -q, --quiet            Suppress diagnostic output on stderr
  -v, --version          Print version
  -h, --help             Show this help message

Config file shape (JSON, or JS default export):
  {
    "builders": { "query": ["zq", "myQuery"], "mutation": ["zm"] },
    "dbFactories": ["zodvexStream"],
    "overrides": { "tasks:bulk": { "reads": ["tasks"], "writes": ["tasks"] } },
    "maxDepth": 3,
    "tsConfigFilePath": "./convex/tsconfig.json"
  }

Examples:
  convex-table-graph ./my-app/convex
  convex-table-graph -d ./convex -o table-graph.json
  convex-table-graph -d ./convex -o convex-table-graph.generated.ts -f ts
  convex-table-graph --builder query=zq,hotpotQuery --builder mutation=zm
`)
}

function printVersion(): void {
  const pkgPath = path.resolve(fileURLToPath(import.meta.url), '../../package.json')
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
  console.log(pkg.version)
}

function formatAsTs(graph: TableGraph): string {
  const lines: string[] = []
  lines.push('// Generated by convex-table-graph. Do not edit by hand.')
  lines.push('')
  lines.push('export const tableGraph = {')
  lines.push(`  version: ${graph.version},`)
  lines.push('  functions: {')
  const paths = Object.keys(graph.functions).sort()
  for (const p of paths) {
    const info = graph.functions[p]!
    lines.push(`    ${JSON.stringify(p)}: {`)
    lines.push(`      kind: ${JSON.stringify(info.kind)},`)
    lines.push(`      visibility: ${JSON.stringify(info.visibility)},`)
    lines.push(`      reads: ${JSON.stringify(info.reads)} as const,`)
    lines.push(`      writes: ${JSON.stringify(info.writes)} as const,`)
    lines.push(`      confidence: ${JSON.stringify(info.confidence)}`)
    lines.push(`    },`)
  }
  lines.push('  }')
  lines.push('} as const')
  lines.push('')
  lines.push('export type TableGraph = typeof tableGraph')
  return lines.join('\n')
}

function printDiagnostics(graph: TableGraph, quiet: boolean): void {
  if (quiet || graph.diagnostics.length === 0) return
  for (const d of graph.diagnostics) {
    const loc = `${d.file}:${d.line}:${d.column}`
    const fn = d.function ? ` [${d.function}]` : ''
    const code = d.code ? ` (${d.code})` : ''
    process.stderr.write(`${d.severity}: ${loc}${fn} — ${d.message}${code}\n`)
  }
  process.stderr.write(`\n${graph.diagnostics.length} diagnostic(s)\n`)
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2)
  const args = parseArgs(argv)

  if (args.help) {
    printHelp()
    return
  }
  if (args.version) {
    printVersion()
    return
  }

  const config = await loadConfigFile(args.configPath, args.convexDir)
  const options = resolveAnalyzeOptions(args, config)
  const graph = analyze(options)

  const output = args.format === 'ts' ? formatAsTs(graph) : JSON.stringify(graph, null, 2)

  if (args.output) {
    const outPath = path.resolve(args.output)
    writeFileSync(outPath, output + '\n', 'utf8')
    if (!args.quiet) process.stderr.write(`Wrote ${outPath}\n`)
  } else {
    process.stdout.write(output + '\n')
  }

  printDiagnostics(graph, args.quiet)
}

main().catch((err) => {
  if (err instanceof CliUsageError) {
    process.stderr.write(`error: ${err.message}\n\n`)
    printHelp()
  } else {
    process.stderr.write(`${err?.stack ?? err}\n`)
  }
  process.exit(1)
})
