// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import type { $ZodType } from 'zod/v4/core'

export declare const zodvexArgsRegistry: Record<string, { args: $ZodType }>
