// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import type { zodvexRegistry as RegistryData } from './api'

export declare const zodvexRegistry: () => Promise<typeof RegistryData>
