// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod/mini'
import { zx } from 'zodvex/mini'
import { CommentModel } from '../models/comment.js'
import { zDuration } from '../codecs.js'

export const zodvexRegistry = {
  'comments:create': {
    args: z.object({ taskId: z.string(), authorId: z.string(), body: z.string() }),
    returns: z.string(),
  },
  'comments:list': {
    args: z.object({ taskId: z.string() }),
    returns: CommentModel.schema.docArray,
  },
  'filters:namedRecentUsers': {
    args: z.object({ after: zx.date() }),
    returns: undefined,
  },
  'filters:recentUsers': {
    args: z.object({ after: zx.date() }),
    returns: undefined,
  },
  'filters:recentUsersWithHelper': {
    args: z.object({ after: zx.date() }),
    returns: undefined,
  },
  'actions:health': {
    args: undefined,
    returns: z.string(),
  },
  'actions:ping': {
    args: z.object({ message: z.string() }),
    returns: z.string(),
  },
  'securedTasks:listOwnTasks': {
    args: z.object({ ownerId: z.string() }),
    returns: z.array(z.object({ title: z.string(), description: z.optional(z.string()), status: z.enum(["todo", "in_progress", "done"]), priority: z.nullable(z.enum(["low", "medium", "high"])), ownerId: z.string(), assigneeId: z.optional(z.string()), dueDate: z.optional(zx.date()), completedAt: z.optional(zx.date()), estimate: z.optional(zDuration), createdAt: zx.date(), _id: z.string(), _creationTime: z.number() })),
  },
  'securedTasks:updateOwnTask': {
    args: z.object({ taskId: z.string(), title: z.optional(z.string()), status: z.optional(z.enum(["todo", "in_progress", "done"])), actorId: z.string() }),
    returns: undefined,
  },
  'componentFunctions:getTaskById': {
    args: z.object({ taskId: z.string() }),
    returns: undefined,
  },
  'componentFunctions:retryableAction': {
    args: z.object({ taskId: z.string(), attempt: z.optional(z.number()) }),
    returns: undefined,
  },
}
