// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod/mini'
import { zx } from 'zodvex/mini'
import { zDuration } from '../codecs.js'
import { taggedEmail, taggedTag } from '../tagged.js'

export const zodvexReturnsRegistry = {
  'activities:get': {
    returns: z.nullable(z.looseObject({ createdAt: zx.date(), payload: z.union([z.looseObject({ type: z.literal("task_completed"), duration: zDuration, }), z.looseObject({ type: z.literal("user_invited"), email: taggedEmail, }), z.looseObject({})]), tags: z.optional(z.array(taggedTag)), })),
  },
  'activities:listByActor': {
    returns: z.array(z.looseObject({ createdAt: zx.date(), payload: z.union([z.looseObject({ type: z.literal("task_completed"), duration: zDuration, }), z.looseObject({ type: z.literal("user_invited"), email: taggedEmail, }), z.looseObject({})]), tags: z.optional(z.array(taggedTag)), })),
  },
  'api/reports:taskById': {
    returns: z.nullable(z.looseObject({ completedAt: z.optional(zx.date()), createdAt: zx.date(), dueDate: z.optional(zx.date()), estimate: z.optional(zDuration), })),
  },
  'comments:list': {
    returns: z.array(z.looseObject({ createdAt: zx.date(), })),
  },
  'notifications:get': {
    returns: z.nullable(z.union([z.looseObject({ kind: z.literal("email"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("push"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("in_app"), createdAt: zx.date(), }), z.looseObject({})])),
  },
  'notifications:listByCreated': {
    returns: z.array(z.union([z.looseObject({ kind: z.literal("email"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("push"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("in_app"), createdAt: zx.date(), }), z.looseObject({})])),
  },
  'notifications:listByKind': {
    returns: z.array(z.union([z.looseObject({ kind: z.literal("email"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("push"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("in_app"), createdAt: zx.date(), }), z.looseObject({})])),
  },
  'notifications:listByRecipient': {
    returns: z.array(z.union([z.looseObject({ kind: z.literal("email"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("push"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("in_app"), createdAt: zx.date(), }), z.looseObject({})])),
  },
  'notifications:listByRecipientAndKind': {
    returns: z.array(z.union([z.looseObject({ kind: z.literal("email"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("push"), createdAt: zx.date(), sentAt: zx.date(), }), z.looseObject({ kind: z.literal("in_app"), createdAt: zx.date(), }), z.looseObject({})])),
  },
  'securedTasks:listOwnTasks': {
    returns: z.array(z.looseObject({ completedAt: z.optional(zx.date()), createdAt: zx.date(), dueDate: z.optional(zx.date()), estimate: z.optional(zDuration), })),
  },
  'tasks:get': {
    returns: z.nullable(z.looseObject({ completedAt: z.optional(zx.date()), createdAt: zx.date(), dueDate: z.optional(zx.date()), estimate: z.optional(zDuration), })),
  },
  'tasks:list': {
    returns: z.looseObject({ page: z.array(z.looseObject({ completedAt: z.optional(zx.date()), createdAt: zx.date(), dueDate: z.optional(zx.date()), estimate: z.optional(zDuration), })), }),
  },
  'tasks:listByCreated': {
    returns: z.array(z.looseObject({ completedAt: z.optional(zx.date()), createdAt: zx.date(), dueDate: z.optional(zx.date()), estimate: z.optional(zDuration), })),
  },
  'tasks:listByStatuses': {
    returns: z.looseObject({ page: z.array(z.looseObject({ completedAt: z.optional(zx.date()), createdAt: zx.date(), dueDate: z.optional(zx.date()), estimate: z.optional(zDuration), })), }),
  },
  'users:get': {
    returns: z.nullable(z.looseObject({ createdAt: zx.date(), email: z.optional(taggedEmail), })),
  },
  'users:getByEmail': {
    returns: z.nullable(z.looseObject({ createdAt: zx.date(), email: z.optional(taggedEmail), })),
  },
}
