// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { initZodvex as _libInitZodvex } from 'zodvex/mini/server'
import type {
  ZodvexActionCtx,
  ZodvexBuilder,
  ZodvexMutationCtx,
  ZodvexQueryCtx,
} from 'zodvex/mini/server'
import type {
  ActionBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  MutationBuilder,
  QueryBuilder,
} from 'convex/server'
import type { DataModel } from '../_generated/dataModel.js'
import _baseSchema from '../schema.js'

// --- Context types ---

// Decoded doc types are imported directly from the codegen-emitted
// tables.ts so userland `schema.ts` can use Convex's canonical
// `defineSchema(tables)` without carrying a zodvex-specific token.
import type { DecodedDocs as _DecodedDocs } from './tables'
type DecodedDocs = _DecodedDocs

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>

// --- Lazy registry ---
// Dynamic import keeps the registry's transitive schema graph out of any
// entrypoint that statically imports this file. esbuild hoists the target
// into a chunk under `_deps/`.

let _cachedRegistry: Promise<typeof import('./api.js').zodvexRegistry> | undefined
const _registry = () => (_cachedRegistry ??= import('./api.js').then(m => m.zodvexRegistry))

// --- Lazy table map ---
// Sourced from `./api.js` (same dynamic import as the registry) because
// Convex's runtime forbids dynamic imports that cross out of the
// marker-defined `_zodvex/` boundary. Same-directory `import('./api.js')`
// works; `import('../models/foo.js')` does not.

let _cachedTableMap: Promise<typeof import('./api.js').zodTableMap> | undefined
const _tableMap = () => (_cachedTableMap ??= import('./api.js').then(m => m.zodTableMap))

// --- Pre-wired initZodvex ---
// Calls the library's initZodvex with schema + lazy registry/tableMap
// already wired. Consumers pass only the Convex server builders.
// Override registry/tableMap/wrapDb via options if needed.

type Server = {
  query: QueryBuilder<DataModel, 'public'>
  mutation: MutationBuilder<DataModel, 'public'>
  action: ActionBuilder<DataModel, 'public'>
  internalQuery: QueryBuilder<DataModel, 'internal'>
  internalMutation: MutationBuilder<DataModel, 'internal'>
  internalAction: ActionBuilder<DataModel, 'internal'>
}

type Bundle = {
  zq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'public'>
  zm: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'public'>
  za: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'public'>
  ziq: ZodvexBuilder<'query', { db: QueryCtx['db'] }, GenericQueryCtx<DataModel>, 'internal'>
  zim: ZodvexBuilder<'mutation', { db: MutationCtx['db'] }, GenericMutationCtx<DataModel>, 'internal'>
  zia: ZodvexBuilder<'action', {}, GenericActionCtx<DataModel>, 'internal'>
}

export function initZodvex(server: Server, options: {
  wrapDb?: boolean
  registry?: () => any
  tableMap?: () => any
} = {}): Bundle {
  return (_libInitZodvex as any)(_baseSchema, server, {
    ...options,
    registry: options.registry ?? _registry,
    tableMap: options.tableMap ?? _tableMap,
  }) as Bundle
}

// --- Codec-aware schema re-export ---
// Userland code that wants `createZodDbReader`/`createZodDbWriter` outside
// a zq/zm handler imports `schema` from here (not from `../schema`). This
// object is the base schema with the lazy tableMap thunk attached as
// `__zodTableMap` plus a type-only `__decodedDocs` token. Both helpers
// detect the thunk and return a `Promise<...DatabaseReader/Writer>` — await
// once at the call site.

type ZodvexSchema = typeof _baseSchema & {
  __zodTableMap: typeof _tableMap
  __decodedDocs: DecodedDocs
}

export const schema: ZodvexSchema = Object.assign(_baseSchema, {
  __zodTableMap: _tableMap,
  __decodedDocs: undefined as unknown as DecodedDocs,
})
