// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { defineTable } from 'convex/server'
import { v } from 'convex/values'

import type { ActivityModel } from '../models/activity.js'
import type { CommentModel } from '../models/comment.js'
import type { NotificationModel } from '../models/notification.js'
import type { TaskModel } from '../models/task.js'
import type { UserModel } from '../models/user.js'
import type { DecodedDocFor } from 'zodvex/server'

export default {
  "activities": defineTable(v.object({ "actorId": v.string(), "payload": v.union(v.object({ "type": v.literal("task_completed"), "taskId": v.string(), "duration": v.float64() }), v.object({ "type": v.literal("user_invited"), "email": v.object({ "value": v.string(), "tag": v.string() }) })), "tags": v.optional(v.array(v.object({ "value": v.string(), "tag": v.string() }))), "createdAt": v.float64() }))
    .index("by_actor", ["actorId"])
    .index("by_created", ["createdAt"]),
  "comments": defineTable(v.object({ "taskId": v.string(), "authorId": v.string(), "body": v.string(), "createdAt": v.float64() }))
    .index("by_task", ["taskId"])
    .index("by_created", ["createdAt"]),
  "notifications": defineTable(v.union(v.object({ "kind": v.literal("email"), "recipientId": v.string(), "subject": v.string(), "body": v.string(), "sentAt": v.float64(), "createdAt": v.float64() }), v.object({ "kind": v.literal("push"), "recipientId": v.string(), "title": v.string(), "badge": v.optional(v.float64()), "sentAt": v.float64(), "createdAt": v.float64() }), v.object({ "kind": v.literal("in_app"), "recipientId": v.string(), "message": v.string(), "linkTo": v.optional(v.string()), "read": v.boolean(), "createdAt": v.float64() })))
    .index("by_recipient", ["recipientId"])
    .index("by_kind", ["kind"])
    .index("by_created", ["createdAt"])
    .index("by_recipient_and_kind", ["recipientId","kind"]),
  "tasks": defineTable(v.object({ "title": v.string(), "description": v.optional(v.string()), "status": v.union(v.literal("todo"), v.literal("in_progress"), v.literal("done")), "priority": v.union(v.union(v.literal("low"), v.literal("medium"), v.literal("high")), v.null()), "ownerId": v.string(), "assigneeId": v.optional(v.string()), "dueDate": v.optional(v.float64()), "completedAt": v.optional(v.float64()), "estimate": v.optional(v.float64()), "createdAt": v.float64() }))
    .index("by_owner", ["ownerId"])
    .index("by_status", ["status"])
    .index("by_assignee", ["assigneeId"])
    .index("by_created", ["createdAt"])
    .index("by_completed", ["completedAt"]),
  "users": defineTable(v.object({ "name": v.string(), "email": v.optional(v.object({ "value": v.string(), "tag": v.string() })), "avatarUrl": v.optional(v.string()), "createdAt": v.float64() }))
    .index("by_email", ["email.value"])
    .index("by_created", ["createdAt"]),
}

/**
 * Decoded document types per table — derived from each model's zod doc
 * schema. Used by `defineZodvexSchema` to attach `__decodedDocs` so
 * ctx.db return types in queries/mutations reflect codec-decoded shapes
 * (e.g. `Date` instead of `number` for `zx.date()` fields).
 *
 * Type-only — does NOT load zod at module init. Schema-eval stays thin.
 */
export type DecodedDocs = DecodedDocFor<{
  "activities": typeof ActivityModel
  "comments": typeof CommentModel
  "notifications": typeof NotificationModel
  "tasks": typeof TaskModel
  "users": typeof UserModel
}>
