import type { z } from 'zod'
import type { DiscoveredFunction, DiscoveredModel } from './discover'
import { zodToSource } from './zodToSource'

const HEADER = `// AUTO-GENERATED by zodvex — do not edit
// Run \`zodvex generate\` to regenerate
`

/**
 * Generates the schema.ts file content — re-exports of all discovered models.
 */
export function generateSchemaFile(models: DiscoveredModel[]): string {
  const exports = models
    .map(m => {
      const importPath = `../${m.sourceFile.replace(/\.ts$/, '')}`
      return `export { ${m.exportName} } from '${importPath}'`
    })
    .join('\n')

  return `${HEADER}\n${exports}\n`
}

type SchemaRef = {
  importPath: string
  exportName: string
  schemaKey: string
}

/**
 * Generates the api.ts file content — function-to-schema registry.
 */
export function generateApiFile(
  functions: DiscoveredFunction[],
  models: DiscoveredModel[]
): string {
  // Build identity map: runtime schema object → model reference string
  const identityMap = new Map<z.ZodTypeAny, SchemaRef>()
  const neededModelImports = new Set<string>()

  for (const model of models) {
    const importPath = `../${model.sourceFile.replace(/\.ts$/, '')}`
    for (const key of ['doc', 'insert', 'update', 'docArray'] as const) {
      identityMap.set(model.schemas[key] as z.ZodTypeAny, {
        importPath,
        exportName: model.exportName,
        schemaKey: key
      })
    }
  }

  // Track which imports we need
  let needsZod = false
  let needsZx = false

  // Resolve each schema to either a model reference or serialized source
  function resolveSchema(schema: z.ZodTypeAny | undefined): string {
    if (!schema) return 'undefined'

    const ref = identityMap.get(schema)
    if (ref) {
      neededModelImports.add(ref.exportName)
      return `${ref.exportName}.schema.${ref.schemaKey}`
    }

    const source = zodToSource(schema)
    if (source.includes('z.')) needsZod = true
    if (source.includes('zx.')) needsZx = true
    return source
  }

  // Build registry entries
  const entries = functions
    .map(fn => {
      const args = resolveSchema(fn.zodArgs)
      const returns = resolveSchema(fn.zodReturns)
      return `  '${fn.functionPath}': {\n    args: ${args},\n    returns: ${returns},\n  }`
    })
    .join(',\n')

  // Build imports
  const imports: string[] = []
  if (needsZod) imports.push("import { z } from 'zod'")
  if (needsZx) imports.push("import { zx } from 'zodvex/core'")
  for (const exportName of neededModelImports) {
    const model = models.find(m => m.exportName === exportName)
    if (model) {
      const importPath = `../${model.sourceFile.replace(/\.ts$/, '')}`
      imports.push(`import { ${exportName} } from '${importPath}'`)
    }
  }

  const importSection = imports.length > 0 ? `${imports.join('\n')}\n\n` : ''

  return `${HEADER}\n${importSection}export const zodvexRegistry = {\n${entries},\n} as const\n`
}
