import { z } from 'zod'
import type {
  DiscoveredFunction,
  DiscoveredModel,
  FunctionEmbeddedCodec,
  ModelEmbeddedCodec
} from './discover'
import { type CodecRef, type ZodToSourceContext, zodToSource } from './zodToSource'

const HEADER = `// AUTO-GENERATED by zodvex — do not edit
// Run \`zodvex generate\` to regenerate
`

/**
 * Generates the schema.ts file content — re-exports of all discovered models.
 */
export function generateSchemaFile(models: DiscoveredModel[]): string {
  const exports = models
    .map(m => {
      const importPath = `../${m.sourceFile.replace(/\.ts$/, '')}`
      return `export { ${m.exportName} } from '${importPath}'`
    })
    .join('\n')

  return `${HEADER}\n${exports}\n`
}

type SchemaRef = {
  importPath: string
  exportName: string
  schemaKey: string
}

export type CodecForGeneration = {
  exportName: string
  sourceFile: string
  schema: z.ZodTypeAny
}

/**
 * Peels .optional() and .nullable() wrappers from a schema and checks
 * the identity map at each level. Returns the matched ref plus the
 * suffix string to reconstruct the wrappers in source output.
 */
function tryUnwrapToIdentity(
  schema: z.ZodTypeAny,
  identityMap: Map<z.ZodTypeAny, SchemaRef>
): { ref: SchemaRef; suffix: string } | null {
  let current = schema
  const suffixes: string[] = []
  const maxDepth = 5

  for (let i = 0; i < maxDepth; i++) {
    const def = current._zod?.def as any
    if (current instanceof z.ZodOptional) {
      suffixes.push('.optional()')
      current = def.innerType
    } else if (current instanceof z.ZodNullable) {
      suffixes.push('.nullable()')
      current = def.innerType
    } else {
      break
    }

    const ref = identityMap.get(current)
    if (ref) {
      // Reverse: suffixes were collected outermost-first, but source reads innermost-first
      return { ref, suffix: suffixes.reverse().join('') }
    }
  }

  return null
}

/**
 * Generates the api.ts file content — function-to-schema registry.
 */
export function generateApiFile(
  functions: DiscoveredFunction[],
  models: DiscoveredModel[],
  codecs?: CodecForGeneration[],
  modelCodecs?: ModelEmbeddedCodec[],
  functionCodecs?: FunctionEmbeddedCodec[]
): string {
  // Build identity map: runtime schema object → model reference string
  const identityMap = new Map<z.ZodTypeAny, SchemaRef>()
  const neededModelImports = new Set<string>()

  for (const model of models) {
    const importPath = `../${model.sourceFile.replace(/\.ts$/, '')}`
    for (const key of ['doc', 'insert', 'update', 'docArray', 'paginatedDoc'] as const) {
      identityMap.set(model.schemas[key] as z.ZodTypeAny, {
        importPath,
        exportName: model.exportName,
        schemaKey: key
      })
    }
  }

  // Build codec identity map for zodToSource
  const codecMap = new Map<z.ZodTypeAny, CodecRef>()
  if (codecs) {
    for (const codec of codecs) {
      const importPath = `../${codec.sourceFile.replace(/\.ts$/, '')}`
      codecMap.set(codec.schema, {
        exportName: codec.exportName,
        sourceFile: importPath
      })
    }
  }

  // Add model-embedded codecs to the codecMap (exported codecs take precedence)
  const modelCodecVars: { varName: string; expression: string; modelExportName: string }[] = []
  const MODEL_CODEC_SENTINEL = '__model_codec__'
  if (modelCodecs) {
    let mcIndex = 0
    for (const mc of modelCodecs) {
      // Skip if this codec is already in codecMap (exported codec takes precedence)
      if (codecMap.has(mc.codec)) continue

      const varName = `_mc${mcIndex++}`
      const expression = `extractCodec(${mc.modelExportName}.schema.${mc.schemaKey}${mc.accessPath})`
      modelCodecVars.push({ varName, expression, modelExportName: mc.modelExportName })
      codecMap.set(mc.codec, {
        exportName: varName,
        sourceFile: MODEL_CODEC_SENTINEL
      })
    }
  }

  // Add function-embedded codecs to the codecMap (exported + model codecs take precedence)
  const fnCodecVars: {
    varName: string
    expression: string
    fnExportName: string
    fnSourceFile: string
  }[] = []
  const FN_CODEC_SENTINEL = '__fn_codec__'
  if (functionCodecs) {
    let fcIndex = 0
    for (const fc of functionCodecs) {
      // Skip if this codec is already in codecMap (exported or model codec takes precedence)
      if (codecMap.has(fc.codec)) continue

      const accessor = fc.schemaSource === 'zodArgs' ? 'readFnArgs' : 'readFnReturns'
      const varName = `_fc${fcIndex++}`
      const expression = `extractCodec(${accessor}(${fc.functionExportName})${fc.accessPath})`
      fnCodecVars.push({
        varName,
        expression,
        fnExportName: fc.functionExportName,
        fnSourceFile: fc.functionSourceFile
      })
      codecMap.set(fc.codec, {
        exportName: varName,
        sourceFile: FN_CODEC_SENTINEL
      })
    }
  }

  const zodToSourceCtx: ZodToSourceContext = {
    codecMap,
    neededCodecImports: new Map(),
    undiscoverableCodecs: []
  }

  // Track which imports we need
  let needsZod = false
  let needsZx = false

  // Resolve each schema to either a model reference or serialized source
  function resolveSchema(schema: z.ZodTypeAny | undefined): string {
    if (!schema) return 'undefined'

    // 1. Direct identity match
    const ref = identityMap.get(schema)
    if (ref) {
      neededModelImports.add(ref.exportName)
      return `${ref.exportName}.schema.${ref.schemaKey}`
    }

    // 2. Wrapper-aware identity match (peel .nullable()/.optional())
    const unwrapped = tryUnwrapToIdentity(schema, identityMap)
    if (unwrapped) {
      neededModelImports.add(unwrapped.ref.exportName)
      return `${unwrapped.ref.exportName}.schema.${unwrapped.ref.schemaKey}${unwrapped.suffix}`
    }

    // 3. Fall back to zodToSource (with codec context)
    const source = zodToSource(schema, zodToSourceCtx)
    if (source.includes('z.')) needsZod = true
    if (source.includes('zx.')) needsZx = true
    return source
  }

  // Build registry entries
  const entries = functions
    .map(fn => {
      const args = resolveSchema(fn.zodArgs)
      const returns = resolveSchema(fn.zodReturns)
      return `  '${fn.functionPath}': {\n    args: ${args},\n    returns: ${returns},\n  }`
    })
    .join(',\n')

  // Determine which model codec vars were actually used (referenced by zodToSource)
  const usedModelCodecVars = modelCodecVars.filter(mc => {
    const sentinelExports = zodToSourceCtx.neededCodecImports.get(MODEL_CODEC_SENTINEL)
    return sentinelExports?.has(mc.varName)
  })

  // Determine which function codec vars were actually used
  const usedFnCodecVars = fnCodecVars.filter(fc => {
    const sentinelExports = zodToSourceCtx.neededCodecImports.get(FN_CODEC_SENTINEL)
    return sentinelExports?.has(fc.varName)
  })

  // Add model imports for models referenced by used model codec vars
  if (usedModelCodecVars.length > 0) {
    for (const mc of usedModelCodecVars) {
      neededModelImports.add(mc.modelExportName)
    }
  }

  // Build imports
  const imports: string[] = []
  if (needsZod) imports.push("import { z } from 'zod'")
  if (needsZx) imports.push("import { zx } from 'zodvex/core'")

  // Build zodvex/codegen import with needed utilities
  const codegenImports: string[] = []
  if (usedModelCodecVars.length > 0 || usedFnCodecVars.length > 0) {
    codegenImports.push('extractCodec')
  }
  const needsReadFnArgs = usedFnCodecVars.some(fc => fc.expression.includes('readFnArgs'))
  const needsReadFnReturns = usedFnCodecVars.some(fc => fc.expression.includes('readFnReturns'))
  if (needsReadFnArgs) codegenImports.push('readFnArgs')
  if (needsReadFnReturns) codegenImports.push('readFnReturns')
  if (codegenImports.length > 0) {
    imports.push(`import { ${codegenImports.join(', ')} } from 'zodvex/codegen'`)
  }

  for (const exportName of neededModelImports) {
    const model = models.find(m => m.exportName === exportName)
    if (model) {
      const importPath = `../${model.sourceFile.replace(/\.ts$/, '')}`
      imports.push(`import { ${exportName} } from '${importPath}'`)
    }
  }

  // Function imports for function-embedded codecs (group by source file)
  if (usedFnCodecVars.length > 0) {
    const fnImportMap = new Map<string, Set<string>>()
    for (const fc of usedFnCodecVars) {
      const importPath = `../${fc.fnSourceFile.replace(/\.ts$/, '')}`
      if (!fnImportMap.has(importPath)) fnImportMap.set(importPath, new Set())
      fnImportMap.get(importPath)?.add(fc.fnExportName)
    }
    for (const [importPath, exportNames] of fnImportMap) {
      const names = Array.from(exportNames).sort().join(', ')
      imports.push(`import { ${names} } from '${importPath}'`)
    }
  }

  // Codec imports (collected by zodToSource via context)
  for (const [importPath, exportNames] of zodToSourceCtx.neededCodecImports) {
    if (importPath === MODEL_CODEC_SENTINEL || importPath === FN_CODEC_SENTINEL) continue
    const names = Array.from(exportNames).sort().join(', ')
    imports.push(`import { ${names} } from '${importPath}'`)
  }

  const importSection = imports.length > 0 ? `${imports.join('\n')}\n\n` : ''

  // Build codec helper var declarations (model + function)
  const allCodecVars = [
    ...usedModelCodecVars.map(mc => `const ${mc.varName} = ${mc.expression}`),
    ...usedFnCodecVars.map(fc => `const ${fc.varName} = ${fc.expression}`)
  ]
  const codecVarSection = allCodecVars.length > 0 ? `${allCodecVars.join('\n')}\n\n` : ''

  return `${HEADER}\n${importSection}${codecVarSection}export const zodvexRegistry = {\n${entries},\n} as const\n`
}

/**
 * Generates the server.ts file content — concrete context types for the app's schema.
 *
 * These parallel Convex's _generated/server.ts exports (QueryCtx, MutationCtx, ActionCtx)
 * but with zodvex's codec-wrapped db types baked in.
 */
export function generateServerFile(): string {
  return `${HEADER}
import type { DataModel } from '../_generated/dataModel'
import type { ZodvexActionCtx, ZodvexMutationCtx, ZodvexQueryCtx } from 'zodvex/server'
import type schema from '../schema'

type DecodedDocs = (typeof schema)['__decodedDocs']

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>
`
}

/**
 * Generates the client.ts file content — pre-bound hooks and client factory.
 */
export function generateClientFile(): string {
  return `${HEADER}
import { createZodvexHooks } from 'zodvex/react'
import { createZodvexClient, type ZodvexClientOptions } from 'zodvex/client'
import { zodvexRegistry } from './api'

export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)

export const createClient = (options: ZodvexClientOptions) =>
  createZodvexClient(zodvexRegistry, options)
`
}
