import { z } from 'zod'
import type { DiscoveredFunction, DiscoveredModel } from './discover'
import { type CodecRef, type ZodToSourceContext, zodToSource } from './zodToSource'

const HEADER = `// AUTO-GENERATED by zodvex — do not edit
// Run \`zodvex generate\` to regenerate
`

/**
 * Generates the schema.ts file content — re-exports of all discovered models.
 */
export function generateSchemaFile(models: DiscoveredModel[]): string {
  const exports = models
    .map(m => {
      const importPath = `../${m.sourceFile.replace(/\.ts$/, '')}`
      return `export { ${m.exportName} } from '${importPath}'`
    })
    .join('\n')

  return `${HEADER}\n${exports}\n`
}

type SchemaRef = {
  importPath: string
  exportName: string
  schemaKey: string
}

export type CodecForGeneration = {
  exportName: string
  sourceFile: string
  schema: z.ZodTypeAny
}

/**
 * Peels .optional() and .nullable() wrappers from a schema and checks
 * the identity map at each level. Returns the matched ref plus the
 * suffix string to reconstruct the wrappers in source output.
 */
function tryUnwrapToIdentity(
  schema: z.ZodTypeAny,
  identityMap: Map<z.ZodTypeAny, SchemaRef>
): { ref: SchemaRef; suffix: string } | null {
  let current = schema
  const suffixes: string[] = []
  const maxDepth = 5

  for (let i = 0; i < maxDepth; i++) {
    const def = current._zod?.def as any
    if (current instanceof z.ZodOptional) {
      suffixes.push('.optional()')
      current = def.innerType
    } else if (current instanceof z.ZodNullable) {
      suffixes.push('.nullable()')
      current = def.innerType
    } else {
      break
    }

    const ref = identityMap.get(current)
    if (ref) {
      // Reverse: suffixes were collected outermost-first, but source reads innermost-first
      return { ref, suffix: suffixes.reverse().join('') }
    }
  }

  return null
}

/**
 * Generates the api.ts file content — function-to-schema registry.
 */
export function generateApiFile(
  functions: DiscoveredFunction[],
  models: DiscoveredModel[],
  codecs?: CodecForGeneration[]
): string {
  // Build identity map: runtime schema object → model reference string
  const identityMap = new Map<z.ZodTypeAny, SchemaRef>()
  const neededModelImports = new Set<string>()

  for (const model of models) {
    const importPath = `../${model.sourceFile.replace(/\.ts$/, '')}`
    for (const key of ['doc', 'insert', 'update', 'docArray', 'paginatedDoc'] as const) {
      identityMap.set(model.schemas[key] as z.ZodTypeAny, {
        importPath,
        exportName: model.exportName,
        schemaKey: key
      })
    }
  }

  // Build codec identity map for zodToSource
  const codecMap = new Map<z.ZodTypeAny, CodecRef>()
  if (codecs) {
    for (const codec of codecs) {
      const importPath = `../${codec.sourceFile.replace(/\.ts$/, '')}`
      codecMap.set(codec.schema, {
        exportName: codec.exportName,
        sourceFile: importPath
      })
    }
  }

  const zodToSourceCtx: ZodToSourceContext = {
    codecMap,
    neededCodecImports: new Map()
  }

  // Track which imports we need
  let needsZod = false
  let needsZx = false

  // Resolve each schema to either a model reference or serialized source
  function resolveSchema(schema: z.ZodTypeAny | undefined): string {
    if (!schema) return 'undefined'

    // 1. Direct identity match
    const ref = identityMap.get(schema)
    if (ref) {
      neededModelImports.add(ref.exportName)
      return `${ref.exportName}.schema.${ref.schemaKey}`
    }

    // 2. Wrapper-aware identity match (peel .nullable()/.optional())
    const unwrapped = tryUnwrapToIdentity(schema, identityMap)
    if (unwrapped) {
      neededModelImports.add(unwrapped.ref.exportName)
      return `${unwrapped.ref.exportName}.schema.${unwrapped.ref.schemaKey}${unwrapped.suffix}`
    }

    // 3. Fall back to zodToSource (with codec context)
    const source = zodToSource(schema, zodToSourceCtx)
    if (source.includes('z.')) needsZod = true
    if (source.includes('zx.')) needsZx = true
    return source
  }

  // Build registry entries
  const entries = functions
    .map(fn => {
      const args = resolveSchema(fn.zodArgs)
      const returns = resolveSchema(fn.zodReturns)
      return `  '${fn.functionPath}': {\n    args: ${args},\n    returns: ${returns},\n  }`
    })
    .join(',\n')

  // Build imports
  const imports: string[] = []
  if (needsZod) imports.push("import { z } from 'zod'")
  if (needsZx) imports.push("import { zx } from 'zodvex/core'")
  for (const exportName of neededModelImports) {
    const model = models.find(m => m.exportName === exportName)
    if (model) {
      const importPath = `../${model.sourceFile.replace(/\.ts$/, '')}`
      imports.push(`import { ${exportName} } from '${importPath}'`)
    }
  }

  // Codec imports (collected by zodToSource via context)
  for (const [importPath, exportNames] of zodToSourceCtx.neededCodecImports) {
    const names = Array.from(exportNames).sort().join(', ')
    imports.push(`import { ${names} } from '${importPath}'`)
  }

  const importSection = imports.length > 0 ? `${imports.join('\n')}\n\n` : ''

  return `${HEADER}\n${importSection}export const zodvexRegistry = {\n${entries},\n} as const\n`
}

/**
 * Generates the server.ts file content — concrete context types for the app's schema.
 *
 * These parallel Convex's _generated/server.ts exports (QueryCtx, MutationCtx, ActionCtx)
 * but with zodvex's codec-wrapped db types baked in.
 */
export function generateServerFile(): string {
  return `${HEADER}
import type { DataModel } from '../_generated/dataModel'
import type { ZodvexActionCtx, ZodvexMutationCtx, ZodvexQueryCtx } from 'zodvex/server'
import type schema from '../schema'

type DecodedDocs = (typeof schema)['__decodedDocs']

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>
`
}

/**
 * Generates the client.ts file content — pre-bound hooks and client factory.
 */
export function generateClientFile(): string {
  return `${HEADER}
import { createZodvexHooks } from 'zodvex/react'
import { createZodvexClient, type ZodvexClientOptions } from 'zodvex/client'
import { zodvexRegistry } from './api'

export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)

export const createClient = (options: ZodvexClientOptions) =>
  createZodvexClient(zodvexRegistry, options)
`
}
