import { z } from 'zod'
import type {
  DiscoveredFunction,
  DiscoveredModel,
  FunctionEmbeddedCodec,
  ModelEmbeddedCodec
} from './discover'
import { type CodecRef, type ZodToSourceContext, zodToSource } from './zodToSource'

const HEADER = `// AUTO-GENERATED by zodvex — do not edit
// Run \`zodvex generate\` to regenerate
`

/**
 * Produces a structural fingerprint for a ZodCodec by serializing its
 * wire (in) and runtime (out) schemas. Two factory-created codec instances
 * with the same arguments produce the same fingerprint, enabling dedup
 * even when object identity differs.
 */
function fingerprintCodec(schema: z.ZodTypeAny): string {
  const def = (schema as any)._zod?.def
  if (!def?.in || !def?.out) return ''
  return `${zodToSource(def.in)}|${zodToSource(def.out)}`
}

/**
 * Generates the schema.ts file content — re-exports of all discovered models.
 */
export function generateSchemaFile(models: DiscoveredModel[]): string {
  const exports = models
    .map(m => {
      const importPath = `../${m.sourceFile.replace(/\.ts$/, '')}`
      return `export { ${m.exportName} } from '${importPath}'`
    })
    .join('\n')

  return `${HEADER}\n${exports}\n`
}

type SchemaRef = {
  importPath: string
  exportName: string
  schemaKey: string
}

export type CodecForGeneration = {
  exportName: string
  sourceFile: string
  schema: z.ZodTypeAny
}

/**
 * Peels .optional() and .nullable() wrappers from a schema and checks
 * the identity map at each level. Returns the matched ref plus the
 * suffix string to reconstruct the wrappers in source output.
 */
function tryUnwrapToIdentity(
  schema: z.ZodTypeAny,
  identityMap: Map<z.ZodTypeAny, SchemaRef>
): { ref: SchemaRef; suffix: string } | null {
  let current = schema
  const suffixes: string[] = []
  const maxDepth = 5

  for (let i = 0; i < maxDepth; i++) {
    const def = current._zod?.def as any
    if (current instanceof z.ZodOptional) {
      suffixes.push('.optional()')
      current = def.innerType
    } else if (current instanceof z.ZodNullable) {
      suffixes.push('.nullable()')
      current = def.innerType
    } else {
      break
    }

    const ref = identityMap.get(current)
    if (ref) {
      // Reverse: suffixes were collected outermost-first, but source reads innermost-first
      return { ref, suffix: suffixes.reverse().join('') }
    }
  }

  return null
}

/**
 * Generates the api.ts file content — function-to-schema registry.
 */
export function generateApiFile(
  functions: DiscoveredFunction[],
  models: DiscoveredModel[],
  codecs?: CodecForGeneration[],
  modelCodecs?: ModelEmbeddedCodec[],
  functionCodecs?: FunctionEmbeddedCodec[]
): string {
  // Build identity map: runtime schema object → model reference string
  const identityMap = new Map<z.ZodTypeAny, SchemaRef>()
  const neededModelImports = new Set<string>()

  for (const model of models) {
    const importPath = `../${model.sourceFile.replace(/\.ts$/, '')}`
    for (const key of ['doc', 'insert', 'update', 'docArray', 'paginatedDoc'] as const) {
      identityMap.set(model.schemas[key] as z.ZodTypeAny, {
        importPath,
        exportName: model.exportName,
        schemaKey: key
      })
    }
  }

  // Build codec identity map for zodToSource
  const codecMap = new Map<z.ZodTypeAny, CodecRef>()
  if (codecs) {
    for (const codec of codecs) {
      const importPath = `../${codec.sourceFile.replace(/\.ts$/, '')}`
      codecMap.set(codec.schema, {
        exportName: codec.exportName,
        sourceFile: importPath
      })
    }
  }

  // Add model-embedded codecs to the codecMap (exported codecs take precedence)
  const modelCodecVars: { varName: string; expression: string; modelExportName: string }[] = []
  const MODEL_CODEC_SENTINEL = '__model_codec__'
  if (modelCodecs) {
    let mcIndex = 0
    for (const mc of modelCodecs) {
      // Skip if this codec is already in codecMap (exported codec takes precedence)
      if (codecMap.has(mc.codec)) continue

      const varName = `_mc${mcIndex++}`
      const expression = `extractCodec(${mc.modelExportName}.schema.${mc.schemaKey}${mc.accessPath})`
      modelCodecVars.push({ varName, expression, modelExportName: mc.modelExportName })
      codecMap.set(mc.codec, {
        exportName: varName,
        sourceFile: MODEL_CODEC_SENTINEL
      })
    }
  }

  // Resolve function-embedded codecs against existing codecs by structural fingerprint.
  // Factory-created codecs (like tagged(), sensitive()) produce new instances each call,
  // so identity matching fails. Fingerprinting matches by wire+runtime schema structure,
  // allowing us to reference the model/standalone codec instead of importing the function.
  // This avoids circular imports: functions.ts → _zodvex/api.ts → functionFile.ts → functions.ts
  if (functionCodecs) {
    const fingerprintMap = new Map<string, CodecRef>()
    for (const [codecSchema, ref] of codecMap) {
      const fp = fingerprintCodec(codecSchema)
      if (fp) fingerprintMap.set(fp, ref)
    }

    for (const fc of functionCodecs) {
      if (codecMap.has(fc.codec)) continue

      const fp = fingerprintCodec(fc.codec)
      const matchingRef = fp ? fingerprintMap.get(fp) : undefined
      if (matchingRef) {
        codecMap.set(fc.codec, matchingRef)
      } else {
        console.warn(
          `[zodvex] Warning: Codec in ${fc.functionExportName}() (${fc.accessPath}) has no matching model or exported codec. ` +
            `Export it standalone for full client-side codec support.`
        )
      }
    }
  }

  const zodToSourceCtx: ZodToSourceContext = {
    codecMap,
    neededCodecImports: new Map(),
    undiscoverableCodecs: []
  }

  // Track which imports we need
  let needsZod = false
  let needsZx = false

  // Resolve each schema to either a model reference or serialized source
  function resolveSchema(schema: z.ZodTypeAny | undefined): string {
    if (!schema) return 'undefined'

    // 1. Direct identity match
    const ref = identityMap.get(schema)
    if (ref) {
      neededModelImports.add(ref.exportName)
      return `${ref.exportName}.schema.${ref.schemaKey}`
    }

    // 2. Wrapper-aware identity match (peel .nullable()/.optional())
    const unwrapped = tryUnwrapToIdentity(schema, identityMap)
    if (unwrapped) {
      neededModelImports.add(unwrapped.ref.exportName)
      return `${unwrapped.ref.exportName}.schema.${unwrapped.ref.schemaKey}${unwrapped.suffix}`
    }

    // 3. Fall back to zodToSource (with codec context)
    const source = zodToSource(schema, zodToSourceCtx)
    if (source.includes('z.')) needsZod = true
    if (source.includes('zx.')) needsZx = true
    return source
  }

  // Build registry entries
  const entries = functions
    .map(fn => {
      const args = resolveSchema(fn.zodArgs)
      const returns = resolveSchema(fn.zodReturns)
      return `  '${fn.functionPath}': {\n    args: ${args},\n    returns: ${returns},\n  }`
    })
    .join(',\n')

  // Determine which model codec vars were actually used (referenced by zodToSource)
  const usedModelCodecVars = modelCodecVars.filter(mc => {
    const sentinelExports = zodToSourceCtx.neededCodecImports.get(MODEL_CODEC_SENTINEL)
    return sentinelExports?.has(mc.varName)
  })

  // Add model imports for models referenced by used model codec vars
  if (usedModelCodecVars.length > 0) {
    for (const mc of usedModelCodecVars) {
      neededModelImports.add(mc.modelExportName)
    }
  }

  // Build imports
  const imports: string[] = []
  if (needsZod) imports.push("import { z } from 'zod'")

  // Build single zodvex/core import (zx, extractCodec)
  const coreImports: string[] = []
  if (needsZx) coreImports.push('zx')
  if (usedModelCodecVars.length > 0) coreImports.push('extractCodec')
  if (coreImports.length > 0) {
    imports.push(`import { ${coreImports.join(', ')} } from 'zodvex/core'`)
  }

  for (const exportName of neededModelImports) {
    const model = models.find(m => m.exportName === exportName)
    if (model) {
      const importPath = `../${model.sourceFile.replace(/\.ts$/, '')}`
      imports.push(`import { ${exportName} } from '${importPath}'`)
    }
  }

  // Codec imports (collected by zodToSource via context)
  for (const [importPath, exportNames] of zodToSourceCtx.neededCodecImports) {
    if (importPath === MODEL_CODEC_SENTINEL) continue
    const names = Array.from(exportNames).sort().join(', ')
    imports.push(`import { ${names} } from '${importPath}'`)
  }

  const importSection = imports.length > 0 ? `${imports.join('\n')}\n\n` : ''

  // Build codec helper var declarations
  const allCodecVars = usedModelCodecVars.map(mc => `const ${mc.varName} = ${mc.expression}`)
  const codecVarSection = allCodecVars.length > 0 ? `${allCodecVars.join('\n')}\n\n` : ''

  return `${HEADER}\n${importSection}${codecVarSection}export const zodvexRegistry = {\n${entries},\n} as const\n`
}

/**
 * Generates the server.ts file content — concrete context types for the app's schema.
 *
 * These parallel Convex's _generated/server.ts exports (QueryCtx, MutationCtx, ActionCtx)
 * but with zodvex's codec-wrapped db types baked in.
 */
export function generateServerFile(): string {
  return `${HEADER}
import type { DataModel } from '../_generated/dataModel'
import type { ZodvexActionCtx, ZodvexMutationCtx, ZodvexQueryCtx } from 'zodvex/server'
import type schema from '../schema'

type DecodedDocs = (typeof schema)['__decodedDocs']

/** Query context with codec-wrapped db (decoded types on reads). */
export type QueryCtx = ZodvexQueryCtx<DataModel, DecodedDocs>

/** Mutation context with codec-wrapped db (decoded reads, encoded writes). */
export type MutationCtx = ZodvexMutationCtx<DataModel, DecodedDocs>

/** Action context (no db, but runQuery/runMutation may be codec-wrapped). */
export type ActionCtx = ZodvexActionCtx<DataModel>
`
}

export interface ClientFileOptions {
  form?: { mantine?: boolean }
}

/**
 * Generates the client.ts file content — pre-bound hooks and client factory.
 */
export function generateClientFile(options: ClientFileOptions = {}): string {
  const mantineSection = options.form?.mantine
    ? `
import { mantineResolver as _mantineResolver } from 'zodvex/form/mantine'
import type { FunctionReference } from 'convex/server'

export const mantineResolver = (ref: FunctionReference<any, any, any, any>) =>
  _mantineResolver(zodvexRegistry, ref)
`
    : ''

  return `${HEADER}
import { createZodvexHooks } from 'zodvex/react'
import { createZodvexReactClient, type ZodvexReactClientOptions } from 'zodvex/react'
import { createZodvexClient, type ZodvexClientOptions } from 'zodvex/client'
import { createBoundaryHelpers } from 'zodvex/core'
import { zodvexRegistry } from './api'

export const { useZodQuery, useZodMutation } = createZodvexHooks(zodvexRegistry)

export const createClient = (options: ZodvexClientOptions) =>
  createZodvexClient(zodvexRegistry, options)

export const createReactClient = (options: ZodvexReactClientOptions) =>
  createZodvexReactClient(zodvexRegistry, options)

export const { encodeArgs, decodeResult } = createBoundaryHelpers(zodvexRegistry)
${mantineSection}`
}
