// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import type { $ZodType } from 'zod/v4/core'

export declare const zodvexTableMap: Record<string, { doc: $ZodType; insert: $ZodType }>
export declare const zodvexTableMapFingerprint: string
