// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import type { $ZodType } from 'zod/v4/core'

declare const _default: { doc: $ZodType; insert: $ZodType }
export default _default
