// AUTO-GENERATED by zodvex — do not edit
// Run `zodvex generate` to regenerate

import { z } from 'zod/mini'
import { zx } from 'zodvex/mini'
import { zDuration } from '../../codecs.js'

// Minimal schema: codec subtrees only; unknown keys pass through (loose).
const schema = z.looseObject({ completedAt: z.optional(zx.date()), createdAt: zx.date(), dueDate: z.optional(zx.date()), estimate: z.optional(zDuration), })

export default { doc: schema, insert: schema }
