// Generated by convex-table-graph. Do not edit by hand.

export const tableGraph = {
  version: 1,
  functions: {
    "actions:health": {
      kind: "action",
      visibility: "public",
      reads: [] as const,
      writes: [] as const,
      confidence: "full"
    },
    "actions:ping": {
      kind: "action",
      visibility: "public",
      reads: [] as const,
      writes: [] as const,
      confidence: "full"
    },
    "activities:get": {
      kind: "query",
      visibility: "public",
      reads: ["activities"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "activities:listByActor": {
      kind: "query",
      visibility: "public",
      reads: ["activities"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"activities","direction":"asc","byCreationTime":false}] as const,
      confidence: "full"
    },
    "activities:update": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["activities"] as const,
      confidence: "full"
    },
    "api/reports:summary": {
      kind: "query",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "api/reports:taskById": {
      kind: "query",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "audited:internalTouch": {
      kind: "internalMutation",
      visibility: "internal",
      reads: [] as const,
      writes: [] as const,
      confidence: "full"
    },
    "audited:touch": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: [] as const,
      confidence: "full"
    },
    "cleanup:deleteOldDocs": {
      kind: "internalMutation",
      visibility: "internal",
      reads: ["activities","comments","notifications","tasks","users"] as const,
      writes: ["activities","comments","notifications","tasks","users"] as const,
      confidence: "full"
    },
    "cleanup:queryCompletedTasks": {
      kind: "internalMutation",
      visibility: "internal",
      reads: ["tasks"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "comments:create": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["comments"] as const,
      confidence: "full"
    },
    "comments:list": {
      kind: "query",
      visibility: "public",
      reads: ["comments"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"comments","direction":"desc","byCreationTime":false}] as const,
      confidence: "full"
    },
    "componentFunctions:getTaskById": {
      kind: "query",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "componentFunctions:retryableAction": {
      kind: "action",
      visibility: "public",
      reads: [] as const,
      writes: [] as const,
      confidence: "full"
    },
    "filters:namedRecentUsers": {
      kind: "query",
      visibility: "public",
      reads: ["users"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"users","direction":"asc","byCreationTime":true}] as const,
      confidence: "full"
    },
    "filters:recentUsers": {
      kind: "query",
      visibility: "public",
      reads: ["users"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"users","direction":"asc","byCreationTime":true}] as const,
      confidence: "full"
    },
    "filters:recentUsersWithHelper": {
      kind: "query",
      visibility: "public",
      reads: ["users"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"users","direction":"asc","byCreationTime":true}] as const,
      confidence: "full"
    },
    "notifications:cleanupOld": {
      kind: "internalMutation",
      visibility: "internal",
      reads: ["notifications"] as const,
      writes: ["notifications"] as const,
      confidence: "full"
    },
    "notifications:createEmail": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["notifications"] as const,
      confidence: "full"
    },
    "notifications:createInApp": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["notifications"] as const,
      confidence: "full"
    },
    "notifications:createPush": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["notifications"] as const,
      confidence: "full"
    },
    "notifications:get": {
      kind: "query",
      visibility: "public",
      reads: ["notifications"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "notifications:listByCreated": {
      kind: "query",
      visibility: "public",
      reads: ["notifications"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"notifications","direction":"asc","byCreationTime":false}] as const,
      confidence: "full"
    },
    "notifications:listByKind": {
      kind: "query",
      visibility: "public",
      reads: ["notifications"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"notifications","direction":"asc","byCreationTime":false}] as const,
      confidence: "full"
    },
    "notifications:listByRecipient": {
      kind: "query",
      visibility: "public",
      reads: ["notifications"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"notifications","direction":"asc","byCreationTime":false}] as const,
      confidence: "full"
    },
    "notifications:listByRecipientAndKind": {
      kind: "query",
      visibility: "public",
      reads: ["notifications"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"notifications","direction":"asc","byCreationTime":false}] as const,
      confidence: "full"
    },
    "securedTasks:listOwnTasks": {
      kind: "query",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"tasks","direction":"asc","byCreationTime":true}] as const,
      confidence: "full"
    },
    "securedTasks:updateOwnTask": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["tasks"] as const,
      confidence: "full"
    },
    "tasks:complete": {
      kind: "mutation",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: ["tasks"] as const,
      confidence: "full"
    },
    "tasks:create": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["tasks"] as const,
      confidence: "full"
    },
    "tasks:get": {
      kind: "query",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "tasks:list": {
      kind: "query",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "tasks:listByCreated": {
      kind: "query",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"tasks","direction":"asc","byCreationTime":false}] as const,
      confidence: "full"
    },
    "tasks:listByStatuses": {
      kind: "query",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "tasks:recent": {
      kind: "query",
      visibility: "public",
      reads: ["tasks"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"tasks","direction":"desc","byCreationTime":true}] as const,
      confidence: "full"
    },
    "tasks:remove": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["tasks"] as const,
      confidence: "full"
    },
    "tasks:update": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["tasks"] as const,
      confidence: "full"
    },
    "users:countByEmail": {
      kind: "query",
      visibility: "public",
      reads: ["users"] as const,
      writes: [] as const,
      resultOrderings: [{"table":"users","direction":"asc","byCreationTime":false}] as const,
      confidence: "full"
    },
    "users:create": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["users"] as const,
      confidence: "full"
    },
    "users:get": {
      kind: "query",
      visibility: "public",
      reads: ["users"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "users:getByEmail": {
      kind: "query",
      visibility: "public",
      reads: ["users"] as const,
      writes: [] as const,
      confidence: "full"
    },
    "users:update": {
      kind: "mutation",
      visibility: "public",
      reads: [] as const,
      writes: ["users"] as const,
      confidence: "full"
    },
  }
} as const

export type TableGraph = typeof tableGraph
