import { afterEach, describe, expect, it } from 'bun:test'
import fs from 'node:fs'
import path from 'node:path'
import { discoverModules } from '../src/codegen/discover'
import { generateSchemaFile, generateValidatorsFile } from '../src/codegen/generate'

const fixtureDir = path.resolve(__dirname, 'fixtures/codegen-project')
const outputDir = path.join(fixtureDir, '_zodvex')

afterEach(() => {
  if (fs.existsSync(outputDir)) {
    fs.rmSync(outputDir, { recursive: true })
  }
})

describe('codegen e2e', () => {
  it('full pipeline: discover → generate → write → verify', async () => {
    // 1. Discover
    const result = await discoverModules(fixtureDir)
    expect(result.models.length).toBe(1)
    expect(result.functions.length).toBeGreaterThanOrEqual(2)

    // 2. Generate
    const schemaContent = generateSchemaFile(result.models)
    const validatorsContent = generateValidatorsFile(result.functions, result.models)

    // 3. Write to _zodvex/
    fs.mkdirSync(outputDir, { recursive: true })
    fs.writeFileSync(path.join(outputDir, 'schema.ts'), schemaContent)
    fs.writeFileSync(path.join(outputDir, 'validators.ts'), validatorsContent)

    // 4. Verify files exist
    expect(fs.existsSync(path.join(outputDir, 'schema.ts'))).toBe(true)
    expect(fs.existsSync(path.join(outputDir, 'validators.ts'))).toBe(true)

    // 5. Verify schema.ts content
    expect(schemaContent).toContain('// AUTO-GENERATED by zodvex')
    expect(schemaContent).toContain("export { UserModel } from '../models/user'")

    // 6. Verify validators.ts content
    expect(validatorsContent).toContain('// AUTO-GENERATED by zodvex')
    expect(validatorsContent).toContain('export const zodvexRegistry')
    expect(validatorsContent).toContain("'users:get'")
    expect(validatorsContent).toContain("'users:list'")

    // 7. Verify ad-hoc schemas are serialized with zodToSource
    expect(validatorsContent).toContain('z.object(')
    expect(validatorsContent).toContain('z.string()')
  })

  it('schema.ts has correct import paths relative to _zodvex/', async () => {
    const result = await discoverModules(fixtureDir)
    const schemaContent = generateSchemaFile(result.models)

    // Import path should go up from _zodvex/ to the source file
    expect(schemaContent).toContain("from '../models/user'")
  })

  it('validators.ts imports zod when ad-hoc schemas are present', async () => {
    const result = await discoverModules(fixtureDir)
    const validatorsContent = generateValidatorsFile(result.functions, result.models)

    expect(validatorsContent).toContain("import { z } from 'zod'")
  })

  it('skips _generated/ and _zodvex/ during discovery', async () => {
    // Create a dummy file in _zodvex/ to ensure it's skipped
    fs.mkdirSync(outputDir, { recursive: true })
    fs.writeFileSync(path.join(outputDir, 'schema.ts'), '// dummy')

    const result = await discoverModules(fixtureDir)

    const allPaths = [
      ...result.models.map(m => m.sourceFile),
      ...result.functions.map(f => f.sourceFile)
    ]
    for (const p of allPaths) {
      expect(p).not.toContain('_zodvex')
      expect(p).not.toContain('_generated')
    }
  })
})
