import { describe, expect, it } from 'bun:test'
import { z } from 'zod'
import { zx } from '../src/zx'
import type { DiscoveredFunction, DiscoveredModel } from '../src/codegen/discover'
import { generateSchemaFile, generateApiFile } from '../src/codegen/generate'

const userDocSchema = z.object({ _id: z.string(), name: z.string(), email: z.string() })

const sampleModels: DiscoveredModel[] = [
  {
    exportName: 'UserModel',
    tableName: 'users',
    sourceFile: 'models/user.ts',
    schemas: {
      doc: userDocSchema,
      insert: z.object({ name: z.string(), email: z.string() }),
      update: z.object({ name: z.string().optional() }),
      docArray: z.array(userDocSchema)
    }
  }
]

const sampleFunctions: DiscoveredFunction[] = [
  {
    functionPath: 'users:get',
    exportName: 'get',
    sourceFile: 'users.ts',
    zodArgs: z.object({ id: zx.id('users') }),
    zodReturns: userDocSchema // Same object reference as model's doc schema
  },
  {
    functionPath: 'users:create',
    exportName: 'create',
    sourceFile: 'users.ts',
    zodArgs: z.object({ name: z.string(), email: z.string() }),
    zodReturns: zx.id('users')
  },
  {
    functionPath: 'users:list',
    exportName: 'list',
    sourceFile: 'users.ts',
    zodArgs: z.object({}),
    zodReturns: undefined
  }
]

describe('generateSchemaFile', () => {
  it('generates model re-exports with header', () => {
    const output = generateSchemaFile(sampleModels)

    expect(output).toContain('// AUTO-GENERATED by zodvex')
    expect(output).toContain("export { UserModel } from '../models/user'")
  })

  it('generates multiple model re-exports', () => {
    const models: DiscoveredModel[] = [
      ...sampleModels,
      {
        exportName: 'PostModel',
        tableName: 'posts',
        sourceFile: 'models/post.ts',
        schemas: sampleModels[0].schemas // Doesn't matter for schema file
      }
    ]
    const output = generateSchemaFile(models)

    expect(output).toContain("export { UserModel } from '../models/user'")
    expect(output).toContain("export { PostModel } from '../models/post'")
  })
})

describe('generateApiFile', () => {
  it('generates registry with function path keys', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    expect(output).toContain('// AUTO-GENERATED by zodvex')
    expect(output).toContain('export const zodvexRegistry')
    expect(output).toContain("'users:get'")
    expect(output).toContain("'users:create'")
    expect(output).toContain("'users:list'")
  })

  it('uses model reference for identity-matched schemas', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    // users:get returns userDocSchema which is === sampleModels[0].schemas.doc
    expect(output).toContain('UserModel.schema.doc')
  })

  it('uses zodToSource for ad-hoc schemas', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    // users:create returns zx.id('users') which is NOT identity-matched to a model
    expect(output).toContain('zx.id("users")')
  })

  it('generates correct imports', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    expect(output).toContain("import { z } from 'zod'")
    expect(output).toContain("import { zx } from 'zodvex/core'")
    expect(output).toContain("import { UserModel } from '../models/user'")
  })

  it('handles functions with no returns schema', () => {
    const output = generateApiFile(sampleFunctions, sampleModels)

    // users:list has no returns
    expect(output).toContain("'users:list'")
    expect(output).toContain('returns: undefined')
  })
})
