import fs from 'node:fs'
import path from 'node:path'
import { discoverModules } from '../codegen/discover'
import {
  generateApiFile,
  generateApiLazyFile,
  generateClientFile,
  generateSchemaFile,
  generateServerFile,
  generateTableMapLazyFile,
  generateTablesFile
} from '../codegen/generate'

/**
 * One-shot codegen. Discovers modules, generates files.
 */
export async function generate(convexDir?: string, options?: { mini?: boolean }): Promise<void> {
  const resolved = resolveConvexDir(convexDir)
  const zodvexDir = path.join(resolved, '_zodvex')

  // Ensure _zodvex/api.js exists before discovery. User modules (e.g., functions.ts)
  // may import zodvexRegistry from it. Without a stub, dynamic import() fails and
  // codegen can't discover those modules — a chicken-and-egg problem.
  writeStubApi(zodvexDir)

  const result = await discoverModules(resolved)

  const schemaContent = generateSchemaFile(result.models)
  const apiContent = generateApiFile(
    result.functions,
    result.models,
    result.codecs,
    result.modelCodecs,
    result.functionCodecs,
    { mini: options?.mini }
  )
  const clientContent = generateClientFile({ mini: options?.mini })
  const serverContent = generateServerFile()
  const apiLazyContent = generateApiLazyFile()
  const tablesContent = generateTablesFile(result.models)
  const tableMapLazyContent = generateTableMapLazyFile(result.models)

  fs.mkdirSync(zodvexDir, { recursive: true })
  writeIfChanged(path.join(zodvexDir, 'schema.js'), schemaContent.js)
  writeIfChanged(path.join(zodvexDir, 'schema.d.ts'), schemaContent.dts)
  writeIfChanged(path.join(zodvexDir, 'api.js'), apiContent.js)
  writeIfChanged(path.join(zodvexDir, 'api.d.ts'), apiContent.dts)
  writeIfChanged(path.join(zodvexDir, 'api.lazy.js'), apiLazyContent.js)
  writeIfChanged(path.join(zodvexDir, 'api.lazy.d.ts'), apiLazyContent.dts)
  // tables is emitted as TypeScript so the literal types flow through —
  // see generateTablesFile for rationale.
  writeIfChanged(path.join(zodvexDir, 'tables.ts'), tablesContent.js)
  // Remove any legacy .js/.d.ts pair from older zodvex versions.
  for (const stale of ['tables.js', 'tables.d.ts']) {
    const p = path.join(zodvexDir, stale)
    try {
      fs.unlinkSync(p)
    } catch {
      /* not present */
    }
  }
  writeIfChanged(path.join(zodvexDir, 'tableMap.lazy.js'), tableMapLazyContent.js)
  writeIfChanged(path.join(zodvexDir, 'tableMap.lazy.d.ts'), tableMapLazyContent.dts)
  writeIfChanged(path.join(zodvexDir, 'client.js'), clientContent.js)
  writeIfChanged(path.join(zodvexDir, 'client.d.ts'), clientContent.dts)
  writeIfChanged(path.join(zodvexDir, 'server.js'), serverContent.js)
  writeIfChanged(path.join(zodvexDir, 'server.d.ts'), serverContent.dts)

  const totalCodecs =
    result.codecs.length + result.modelCodecs.length + result.functionCodecs.length
  console.log(
    `[zodvex] Generated ${result.models.length} model(s), ${result.functions.length} function(s), ${totalCodecs} codec(s)`
  )
}

/**
 * Watch mode. Runs generate() once, then watches for changes.
 */
export async function dev(convexDir?: string, options?: { mini?: boolean }): Promise<void> {
  const resolved = resolveConvexDir(convexDir)

  console.log('[zodvex] Starting watch mode...')
  await generate(resolved, options)

  let debounceTimer: ReturnType<typeof setTimeout> | null = null

  const watcher = fs.watch(resolved, { recursive: true }, (_event, filename) => {
    if (!filename) return
    // Skip generated directories and non-TS files
    if (
      filename.startsWith('_zodvex') ||
      filename.startsWith('_generated') ||
      (!filename.endsWith('.ts') && !filename.endsWith('.js'))
    ) {
      return
    }

    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(async () => {
      console.log('[zodvex] Regenerating...')
      try {
        await generate(resolved, options)
      } catch (err) {
        console.error('[zodvex] Generation failed:', (err as Error).message)
      }
    }, 300)
  })

  // Keep process alive
  process.on('SIGINT', () => {
    if (debounceTimer) clearTimeout(debounceTimer)
    watcher.close()
    process.exit(0)
  })
}

/** Writes minimal stub _zodvex/api.js + api.d.ts (and api.lazy.{js,d.ts}) before
 *  discovery to break circular imports. Previous generations may contain stale
 *  imports that cause cycles during re-discovery. */
function writeStubApi(zodvexDir: string): void {
  fs.mkdirSync(zodvexDir, { recursive: true })

  fs.writeFileSync(
    path.join(zodvexDir, 'api.js'),
    '// AUTO-GENERATED by zodvex — do not edit\n// Stub created for codegen bootstrap\n\nexport const zodvexRegistry = {}\n'
  )

  fs.writeFileSync(
    path.join(zodvexDir, 'api.d.ts'),
    '// AUTO-GENERATED by zodvex — do not edit\n// Stub created for codegen bootstrap\n\nexport declare const zodvexRegistry: Record<string, any>\n'
  )

  fs.writeFileSync(
    path.join(zodvexDir, 'api.lazy.js'),
    "// AUTO-GENERATED by zodvex — do not edit\n// Stub created for codegen bootstrap\n\nlet _cached\nexport const zodvexRegistry = () => (_cached ??= import('./api.js').then(m => m.zodvexRegistry))\n"
  )

  fs.writeFileSync(
    path.join(zodvexDir, 'api.lazy.d.ts'),
    '// AUTO-GENERATED by zodvex — do not edit\n// Stub created for codegen bootstrap\n\nexport declare const zodvexRegistry: () => Promise<Record<string, any>>\n'
  )

  // tables.{js,d.ts} and tableMap.lazy.{js,d.ts} are STAMPED ONLY IF MISSING.
  // Convex reads tables.js during schema-eval — overwriting a real schema
  // mid-generate with an empty stub would cause the convex dev watcher to
  // observe "all tables removed" and try to apply that change. Once real
  // content has been written by a previous generate, leave it alone; the
  // real `writeIfChanged` call at the end of generate() will update it.
  writeIfMissing(
    path.join(zodvexDir, 'tables.ts'),
    "// AUTO-GENERATED by zodvex — do not edit\n// Stub created for codegen bootstrap\n\nexport default {} as Record<string, import('convex/server').TableDefinition>\n"
  )
  writeIfMissing(
    path.join(zodvexDir, 'tableMap.lazy.js'),
    '// AUTO-GENERATED by zodvex — do not edit\n// Stub created for codegen bootstrap\n\nexport const zodTableMap = () => Promise.resolve({})\n'
  )
  writeIfMissing(
    path.join(zodvexDir, 'tableMap.lazy.d.ts'),
    '// AUTO-GENERATED by zodvex — do not edit\n// Stub created for codegen bootstrap\n\nexport declare const zodTableMap: () => Promise<Record<string, { doc: any; insert: any }>>\n'
  )
}

function writeIfMissing(filePath: string, content: string): void {
  if (fs.existsSync(filePath)) return
  fs.writeFileSync(filePath, content)
}

/** Only write if content differs from what's on disk — prevents file watcher loops. */
function writeIfChanged(filePath: string, content: string): void {
  try {
    const existing = fs.readFileSync(filePath, 'utf-8')
    if (existing === content) return
  } catch {
    // File doesn't exist yet — write it
  }
  fs.writeFileSync(filePath, content)
}

function resolveConvexDir(dir?: string): string {
  if (dir) {
    const resolved = path.resolve(dir)
    if (!fs.existsSync(resolved)) {
      throw new Error(`Convex directory not found: ${resolved}`)
    }
    return resolved
  }

  // Default: look for ./convex/ in cwd
  const defaultDir = path.resolve('convex')
  if (!fs.existsSync(defaultDir)) {
    throw new Error('No convex/ directory found. Specify the path: zodvex generate <path>')
  }
  return defaultDir
}
